### ISSUE TITLE
Water and lava should be set passable/impassable independently for creatures

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#101]

**Comment by hwoarangmy** [comment]
I've been thinking that instead of using tile passability, we could add in creatures.def a speed modificator on water and speed modificator on lava. For creatures that are actually allowed on walkable tile only, the speed for both would be 0 and the creature should not be allowed to pass. But we could imagine to have creatures that could go through water with a 0.5 speed penalty or others such as lava golem that do not have penalty on lava but cannot go through water.
What do you think ?

**Comment by akien-mga** [comment]
That could be interesting for the gameplay, and as you say it could help differentiate creatures that can't go on water and/or on the lava. We could even have water creatures that can't leave the water and fire elementals that can't leave the lava, in scenarios where your dungeon is partly surrounded by lava/water :-)

Depending on the implementation, I can already foresee potential flaws though: if the speed modificator is processed only when the creature arrives on the tile, then most creatures would step in water and then get stuck with 0 velocity. So there should be a check before moving towards the tile to prevent such glitches.

Same thing for the pathfinding: it should be adapted to take into account the speed modificator (note that we could also have speed modificators depending on the ground tile if we implement different biomes with sand, forest soil, etc.) so that the creature chooses the quickest way and does not start to cross a small pond at 0.05 speed when it could have walked around it :-)

**Comment by Bertram25** [comment]
The idea given here is interesting enough and could provide some good strategical cases. :)

I don't completely know about the implementation, but a speed factor of 0 should make the tile type be treated like a wall in this case, indeed. For optimization purpose, we might want to keep boolean for collision detection somehow, though.
Also, what @akien-mga said about path optimization depending on the speed is true, while it can be done in a second step.

Also, default movement speed parameter could become a dirt tile type speed factor as well in this case.

For simple pathfinding performance reason, I know the game internally keeps an array of areas, used when one creature just need to know whether a path is valid without computing it each time,
by checking whether the current position and the destination are in the same area. This part might need to be adapted as well.

**Comment by hwoarangmy** [comment]
> I know the game internally keeps an array of areas

I guess you are talking about floodfill. I've seen that in the code but didn't look how it works yet. That may be a problem... I think it deserves a little bit more of relexion to find a nice way to handle that...

> if the speed modificator is processed only when the creature arrives on the tile

No worries, of course, it has to be processed during the find path ;) Even if I think that we should use the same algorithm as the actual one, at least for now, to not care about this penalty (except when it is 0, again).

**Comment by hwoarangmy** [comment]
Ok, I've seen what floodfill is. In fact, it is just a matter of tagging walkable tiles to know if there is a way to go from a tile to another for a walkable creature. The optimization is to not search if there is no path (which is not stupid since that's the case where A\* algorithm would be the worst).
So, to improve floodfill, I can do the same for
- walkable tiles (already done)
- walkable  + water tiles
- walkable  + lava tiles
- walkable  + water+ lava tiles
  This way, we could have the same for all creatures.

That would also mean that we could not do as @akien-mga said about having creatures that stay on water.

**Comment by Bertram25** [comment]
All that seems cool to hear. :)

**Comment by hwoarangmy** [comment]
ok, I'm gonna give a try. I will also try to add some console commands to force a creature to go somewhere to debug this.

**Comment by hwoarangmy** [comment]
BTW, now that I am at it, I am also doing some tests to see if we can improve the A\* algo (by using more appropritate classes). If someone has an idea, that's the right time to tell :)

**Comment by Bertram25** [comment]
The console command is a good idea. :)
All I can say is that at the moment, IIRC, whenever a path is longer than, say 20 tiles, an empty path is returned. I think this is wrong because if a creature wants to go somewhere, I'd prefer it to reach its goal using two or three small pathfind calls, rather than stay idle because the API returns an empty path in that case. My two cents. :)

**Comment by Bertram25** [comment]
Ah, also, workers have a hard time going through 1-tile wide corridors from one room to another, preventing them from claiming tile efficiently for instance. The bug disappears once the same corridor is 2 tile wide. That's why I made the AI dig 3 tile wide paths to make sure it would work. I also suspect the cutCorners() functions to have a role in this bug according to my partial investiguations. Hopefully, this will help you. :)

**Comment by hwoarangmy** [comment]
From what I've seen so far, there is no limitation is the path length when the path is calculated. I've done a special map for that based on small map (changinf dirt till fullness to 0). That means I only have the gold tiles with 2 holes. I've added in code a call to find the path function in a loop to see how long it takes when changing the lists. I am trying with path from 1;1 to 49;49 and it works. I will keep the best I can found.
If there is a limitation, it must be in some other function (I've not looked at cutCorners yet).

**Comment by Bertram25** [comment]
Yeah, I might have dreamt it, or even removed that limitation myself, I can't remember. ;) Sorry, all that was from my humanly failing memory.
I'm quite certain there is a bug around narrow (1-tile wide) paths, though. As it happened again yesterday while playing.
The limitation I have mis-seen might as well come from that bug. ?

**Comment by hwoarangmy** [comment]
I did not say there was no limitation. I just said it was not in the path finding function. But it may be somewhere else. For now, I'm focusing on the path function. I will see the others after. I will tell you if I find something about the bug you are talking about.

**Comment by hwoarangmy** [comment]
@Bertram25 Do you know if there is an easy way to display some text on ogre nodes ? I would like to add a console command to display floodfill on tiles but I couldn't find an easy way to display that. For now, I use a command that export to the logs the floodfill but it is not easy to read :)

**Comment by Bertram25** [comment]
@hwoarangmy Like this? http://www.ogre3d.org/tikiwiki/tiki-index.php?page=MovableText

**Comment by hwoarangmy** [comment]
Yes, I've seen that but it requires to add a new dedicated class. I was hoping there was a way out of the box to do that as I'm not sure about licenses when including code from somewhere else. Never matters, I will use that. Do you think there is a license problem if we push that ?

**Comment by Bertram25** [comment]
> Do you think there is a license problem if we push that ?

For the code, it is MIT, as stated in the license agreement, AFAIK. So there shouldn't be any problem. :) But beware of the fonts, though. Don't use them.

**Comment by Bertram25** [comment]
Correction:
From the website:

> As an exception, any source code contributed within the content is released into the Public Domain.

**Comment by hwoarangmy** [comment]
ok. I prefer to ask :)
I will try and if it works, I will push it

**Comment by hwoarangmy** [comment]
As you said, there is a problem with font and it doesn't compile. Well, I think I'm going to stick on Logs and that will be enough.

**Comment by Bertram25** [comment]
Ah, dang it. That's what happens when snippets aren't updated. I'll have a look on my own but I can't promise anything soon.

**Comment by hwoarangmy** [comment]
Btw, I am also having a look at creature action behaviour as I have some weird issues due to them (like creatures crossing walls :) ).

**Comment by Bertram25** [comment]
If it's not a ghost tile problem, then cut corners might also be the culprit in that case.
I'm more and more thinking we should stop cutting corners. It might be not that important after all, IMHO.

**Comment by hwoarangmy** [comment]
lol. Funny, I was thinking that I should ask for removing it too :)
I've tried to stub it and I do not see any problem with 1 tile passageway.
I've been thinking that we could use diagonals after calculating the path (if the 4 tiles are passable) and that might be enough. What do you think ?

**Comment by Bertram25** [comment]
I completely agree.

**Comment by hwoarangmy** [comment]
Ok. I will do that then
