### ISSUE TITLE
Creatures stop moving after a while - problem with action list

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#104]
I let a game play during some time and I've seen strange things in action list like the one posted. I guess the root comes from maneuver action that is not popped for an unknown reason (I've not had look yet)

![bug](https://cloud.githubusercontent.com/assets/7493706/3999303/50560276-294f-11e4-8320-a4a8b87b60ce.png)

**Comment by hwoarangmy** [comment]
I've let a game play for 3 hours with the 3 AI fighting each other. After that time (don't know exactly when it started) almost all AI creatures were frozen. There is definitely a problem with maneuver action as most of them had their action list full with that. But some not moving had a list that seemed normal (idle and walktotile) but they did not move either.

**Comment by akien-mga** [comment]
I guess I found the culprit: `Awakeness: 0`
I have three creatures with 0 awakeness who are standing at the edge of my dormitory, and idling with the "sleep" action. My guess is that there is no room for their bed in the dormitory, so they're just idling of exhaustion :-)

_Edit:_ I picked one of them and dropping him in the dormitory, and he went to his bed to sleep. So there is something broken in the "let's go to sleep" logic it seems.

_Edit2:_ It seems those creatures we just stuck because a wall was on their path. I removed the wall, and they instantly went to bed.

**Comment by Bertram25** [comment]
> Edit2: It seems those creatures we just stuck because a wall was on their path. I removed the wall, and they instantly went to bed.

While this is another problem, I think it's next important one to deal with. Have you got a way to reproduce more or less? Or a screenie? :)

**Comment by Bertram25** [comment]
> But some not moving had a list that seemed normal (idle and walktotile) but they did not move either.

Yeah, I confirm. Might be linked to paths also.

**Comment by hwoarangmy** [comment]
With my latest pull request, the path finding logic has changed and there should be no problem anymore with 1 tile wide corridors. As far as I've seen, now, the only frozen creatures are the ones with ennemies around (with maneuver in the action list).

**Comment by Bertram25** [comment]
> With my latest pull request, the path finding logic has changed and there should be no problem anymore with 1 tile wide corridors. As far as I've seen, now, the only frozen creatures are the ones with ennemies around (with maneuver in the action list).

Hurray :D One down ;)
