### ISSUE TITLE
Segfaulted games are not removed from the masterserver

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#1040]
Check the current status of the masterserver: http://od-odms.rhcloud.com/
It still sees our games from Saturday as "In progress", likely because due to the segfault they could never send the "we're done" signal.

I'd expect those to timeout and move in the corresponding section.

**Comment by hwoarangmy** [comment]
In reality, that's because we only care about games not launched (status = 0). Once the game is launched, it only notifies the server when the game is finished. And we cannot know if the game is still ongoing or not (after all, we could be still playing). And more important, we don't care. If we have a need for some reason, it might be a good idea to add a timeout. But if we do want to care, we would need to have a push system to tell the server the game is ongoing (like for status =0).

**Comment by Bertram25** [comment]
> But if we do want to care, we would need to have a push system to tell the server the game is ongoing (like for status =0).

Well, I must say I care. But I don't think I care enough to ask for a true keep alive.
What about a one-day timeout?

**Comment by hwoarangmy** [comment]
that's ok for me. Note that this case can also happen if the server gets disconnected so we must assume it will not be that rare...

**Comment by akien-mga** [comment]
Should we add this one-day timeout for the 0.7.0 release?

**Comment by hwoarangmy** [comment]
Closed by a PR in the master server project
