### ISSUE TITLE
Key bindings not working on Linux X11

### ISSUE THREAD

**Issue by erdmannp** [OpenDungeons/OpenDungeons#1041]
The keybindings do not work in 0.6.0. 

Windowed Mode, Debian and two displays.

**Comment by erdmannp** [comment]
Tried it with one monitor. It works until i switched from the game to another application.

**Comment by hwoarangmy** [comment]
I know there are some issues with input grabbing with Linux. Pinging @akien-mga as he knows more about that

**Comment by akien-mga** [comment]
This one is tricky, as we always get some users with issues either with mouse grab or keyboard grab, while all of us active developers have no issue at all, so it's hard to track down.

Last time we more or less narrowed it down to some window managers on Linux, i.e. it works great with KDE/Kwin and I think it's fine too on GNOME, but some other WMs are more troublesome.

In the end it's most likely an OIS bug though, and since upstream is basically dead...
Well there has been some activity upstream though and many (unmerged) pull requests. I'll try to build a 64-bit binary with the code from this new repo and maybe some of the PRs to see if it behaves better.

If it doesn't, we might want to start considering non-dead alternatives. Should we try e.g. SFML http://www.sfml-dev.org/tutorials/2.3/window-inputs.php?

**Comment by hwoarangmy** [comment]
> If it doesn't, we might want to start considering non-dead alternatives. Should we try e.g. SFML

I've had a look at SFML code to see how it works and it is pretty well done IMHO. I won't be against using it as much as we can.

**Comment by akien-mga** [comment]
> I've had a look at SFML code to see how it works and it is pretty well done IMHO. I won't be against using it as much as we can.

Yes the API looks very neat from last time I had a look at it (I ported the old game FreeTumble from SFML 1.x to 2.x: https://github.com/LibreGameArchive/freetumble). The only question is how well it handles keyboard input for e.g. non-latin characters, but I guess we would soon find out if we start working on dropping OIS in a feature branch.

I'll give a try to the OIS fork first of course so that we know where we're going from.

**Comment by oyvindln** [comment]
I also have issues with this, and I'm using XFCE. It works fine if I turn on keyboard grab in the options though (and restart).

**Comment by akien-mga** [comment]
@erdmannp @oyvindln Could you try this new binary? http://download.tuxfamily.org/opendungeons/WIP/OpenDungeons-git20151212-Linux64.tar.xz (will actually be online in 10 min, my upload is slow :p)
I linked it against the master branch of the new OIS repo: https://github.com/wgois/OIS + one big PR with keyboard improvements (https://github.com/wgois/OIS/pulls/14).

**Comment by Bertram25** [comment]
@oyvindln Love you new avatar. ;)

Is wgois fixing the issue? We could submodule or subtree-it and make it a static lib within OD if it does.

**Comment by oyvindln** [comment]
@akien-mga Keyboard seems to work fine with the snapshot (when doing alt-f11 to change to windowed mode), though it seems to have trouble creating/modifying config files, so the settings menu is broken.

**Comment by Bertram25** [comment]
Hey @oyvindln :D And happy new year!

>  though it seems to have trouble creating/modifying config files, so the settings menu is broken.

I would interested in your log in a new issue. :)

@OpenDungeons/developers  WDYT about using OIS fork as either a submodule or a subtree and adapt our CMake file?

**Comment by oyvindln** [comment]
I'm going to have a crack at moving to SFML for input and get rid of ois, which should hopefully solve this issue.
