### ISSUE TITLE
Waves portal and max number of creatures?

### ISSUE THREAD

**Issue by Danimal696** [OpenDungeons/OpenDungeons#1091]
I have a ton of rogues in the map (white team), but i also want to spawn waves in a rogue base; 
What are my options?
- lower feral creatures count? i refuse!
- Spawing them as an allied team of the rogues? how to do it?

**Comment by akien-mga** [comment]
What's the problem with just adding those waves to the existing rogue seat?

But if you want to make them for a distinct seat but allied of the rogues, you just need to add a second rogue team, make it ally with the first, and spawn waves for this new team.

See https://github.com/OpenDungeons/OpenDungeons/wiki/Making-wave-portals on how to attribute waves to a given team ;)

**Comment by Danimal696** [comment]
If i erase all rogues creatures waves start spawning, so its a matter of max numbers. ill need to use the second option

**Comment by akien-mga** [comment]
Oh right rogue seats would also be affected by the creature limitation indeed.

**Comment by hwoarangmy** [comment]
IIUC, you reached the creature limit number ? ATM, it is defined in the global.cfg file and set to 30 (item MaxCreaturesPerSeatAbsolute).

As you stated, you have 2 options: increase the number of creatures per seat (this will only delay the problem) or use a seat allied to the creatures feral in the map. However, if you spawn creatures with seat != 0, they will be affected by mood and will become rogue (seat = 0) after some time because they won't have gold/dormitory/food and that may not be what you want.
Note that this may be considered as a bug because the max number of creatures can be easily work arounded by spawning creatures with seat != 0 and letting them become rogue. But I don't see what we can do about it...

**Comment by Danimal696** [comment]
As long as they dont figth the original rogues im good. Wasnt that value in level file before? i dont think the migration to global was a good idea, is there no way to override it into the level file?

**Comment by hwoarangmy** [comment]
Well, they will fight original rogues as rogue team is not allowed for seats. AFAIK, the max number of creatures was hardcoded in portals before portal waves. But since portal waves, we moved it to global.

Note that the max number of creatures per seat is there for hardware limitation purposes and should not be changed per level (that's why it is global). However, if you find the value too low, you can increase it. But keep in mind that increasing it too much might make the game laggy/not work on weaker configurations.

**Comment by Bertram25** [comment]
Closing since @hwoarangmy answered the question. :)
