### ISSUE TITLE
Beef up the explosion spell

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#1128]
Right now it's not really worth researching, as it does very little damage.

I don't know if it should be modified only for the keeper, or also for creatures though. Maybe only the keeper?

**Comment by hwoarangmy** [comment]
Note that all of this can be done in the config files. Explosion spell for keeper is in config/spells.cfg (actually value is 5 per turn for 5 turns).
For creatures, it is defined in config/creatures.cfg for each skill "Explosion". IIRC, it is set to 15 damages for 1 turn for them.

Concerning the spell power value, ATM, creatures with good defense vs magic tier 4 start with 6.8 magical defense + 0.6 per level (Troll & Defender).
That means that a level 10 Troll will have 12.8 defense vs magic for 80 HP.

For tier 1 creatures with good defense vs magic (cavehornet), at level 1 they start with magical def 2.4 + 0.3 per level for 20 HP.
At level 10, they would have 5.4 defense vs magic for 30 HP.

Since explosion spell costs 5000 mana (not cheap) per target, I would propose to one shot tier 1 level 1 creatures, hurt badly tier 1 level 10 creatures good vs magic and deal some damages to tier 4 creatures good vs magic and deal few damages to tier 4 creatures level 10 good vs magic.

That would mean something around: 14 damages for 3 turns.

@OpenDungeons/developers WDYT ? For my part, it sounds pretty good.

**Comment by akien-mga** [comment]
That sounds pretty good to me :)

I'm starting to think that it might be interesting to have some keeper stats such as magic attack power than would influence the damage of such spells, and could be either researched in the library, or maybe in a dedicated structure (e.g. praying at the dungeon temple). Just a random idea, don't know if it would be good gameplay wise :)
