### ISSUE TITLE
Corrupt save game leads to not being able to start new game

### ISSUE THREAD

**Issue by Loobinex** [OpenDungeons/OpenDungeons#1145]
I tried to load a saved game that gave me an 'Invalid map' warning. It might be a saved game from an old version of the game.

When I did I got an error message that said: "Error: Could not start server for single player game!!!"
With the three exclamation marks I took the error message seriously so I gave up and tried to load my other saved games, however they now all gave the same error message. I then tried to start a new game, and again I got the same error message. I had to restart the application to be able to start a new game.
This is fully reproducible, whenever I try to load this saved game I cannot play anything until I do a restart.

A problem with a saved game should not hinder my ability to play working saved games or starting a new game. Screenshot:
![butiwantto](https://cloud.githubusercontent.com/assets/13840686/14062902/a04024ce-f3b0-11e5-8b7b-6df771c4c269.png)

Log file attached: ![ogre.7z](https://cloud.githubusercontent.com/assets/13840686/14062904/ca717964-f3b0-11e5-87b3-d555ffc7abed.jpg)

**Comment by Bertram25** [comment]
Hey @Loobinex :)
The bug comes from the fact that the game (be it for a lan, or a single game) starts a server part, the client part will try to discuss with over lan or using the local loop (in single player mode), this design permits to have almost the same behavior when you play single and multiplayer mode, reduce the need of lan tests and thus improves the overall quality of the game as testing is easier.

Long introduction done, when the game crashes, the server socket doesn't get freed, and it has to timeout before being free again. This can last up to a minute on Linux for instance.
Maybe we could at a stop server socket call at appquit() and link the appquit calls when a segfault is triggered?

@hwoarangmy Do you think it is possible to do something similar like the way we added a backtrace?

**Comment by hwoarangmy** [comment]
Well, I guess that we should not take the socket if the savegame/level is not read for any reason. This is a bug a should be fixed. However, until version 1.0, we already said we don't want to bother with compatibility and we accept that even minor upgrades (according to version numbers) break compatibility.
But indeed, broken saved games should only display a message saying that the game could not be loaded (and the logs should be as explicit as possible about what happened) and the game should be launchable with a new not broken level.

**Comment by Bertram25** [comment]
> But indeed, broken saved games should only display a message saying that the game could not be loaded (and the logs should be as explicit as possible about what happened) and the game should be launchable with a new not broken level.

Ah yes, that part is very true and deserves a fix.

**Comment by Svetomech** [comment]
I have this exact issue on a fresh install. Also, it doesn't go away thus rendering the game unplayable in SP.
