### ISSUE TITLE
3D Model size affects Weapon size

### ISSUE THREAD

**Issue by Danimal696** [OpenDungeons/OpenDungeons#1167]
I have run into a common blender problem (and not for the first time), the thing is once you scale an armature it goes crazy and you get a spagetti party for result. If i dont rescale it the animation works fine, but our code-added weapon uses the model as a reference for its own size; so for a model i define as 0.007 the sword/shield is so small you cant even see it. Can this be avoided? if the solution to the weapons size is easier codewise i beg for someone to fix it, since remaking animations from scratch is a living hell.

The cultist is just waiting for an answer to this:
https://www.youtube.com/watch?v=xyiEAO7U3x8

**Comment by hwoarangmy** [comment]
Well, in this case, we should first decide what we want. To answer the question, we can handle the weapon size on the code size.
However, the first question is do we want the weapon size to change according to its user ?
For example, if a goblin and a Troll-like creature both using sword use the same sword, do we want it to have the same size ?
If yes, that would mean that we need on the artist side to keep that in mind and do not allow too big/small creatures to use weapons that "normal" sized creatures might use.
If no, we can add a weapon size modifier in the creature definition to fix the issue.

For the record, after playing for some time with blender for the Lava spawn, I will open a forum issue with the wanted animations we want for our models (to help animators know what we need) with the correct spelling and everything needed to make (will it be played looped or not, ...).

Moreover, we also need to decide some stuff about the models. IMHO, the best would be to remove model resizing and resize directly the mesh files so that they are correctly displayed (I used a tool called MeshMagick to rotate the Skeleton and the Lich from Summoning Wars and it also allows to resize models - to be checked):
http://www.ogre3d.org/tikiwiki/MeshMagick

@Danimal696 I also had several issues with model/skeleton scaling. To avoid them, I've seen it is better to not use a scaled armature (to update the size, you can press CONTROL + A -> apply Rotation and scale and CONTROL + A -> apply Translation). That will avoid very weird animation problems (animation OK with blender but totally crazy with Ogre). However, it breaks existing animations in Blender.
I tried to work a bit on the DrArmpit model but could not get rid of this. As soon as I resize the armature, it changes position in Blender and I couldn't make it go to its original position in blender (the one in armature edit mode). I guess the skeleton is too advanced for me. The armature contains many not visible bones (I don't even know how it is done and what they do). In Pose mode, there are some "buttons" that allow to make actions without directly using the corresponding bone (like the mouth or the eyes).
So far, the only solution I see is to remove the armature and build a new one. But I guess it would be a waste as the one I would do would be much more basic than the existing one...

**Comment by Danimal696** [comment]
Thats my problem exactly, there is no point for me to use a pre-animated rig if i cant rescale it later to work on ogre (it goes crazy) and i just found a great one but has that flaw. If we can fix the weapon scale issue its a huge bonus not having to worry about remaking every single animation. i think the extra weapon scale value is a good solution that doesnt sacrifice anything (weapon still grows with character).

As for Dr. armpit i would erase the current armature, its far too advanced even for me.

**Comment by hwoarangmy** [comment]
Note that I've played a bit with ogre mesh magick and I confirm it is what you need here (and what can help us to avoid constant resizing).
You can grab it from ogre comand line tools:
http://www.ogre3d.org/download/tools

Assuming the weapon you want to use is at correct size for knight (which is scaled 0.5), you can do (it will overwrite your model and also resize the skeleton):
`OgreMeshMagick transform -scale=0.014/0.014/0.014 Cultist.mesh`

Then, ingame, you need to rescale him 0.5 0.5 0.5.

Note that this problem is similar for any creature. The weapons will only fit well if they are sized at 0.5 more or less in the config file. The good point with the current implementation is that we can play with OgreMeshMagick and resizing to have the weapons at the size we want. But I'm not sure that's what we should go for. IMHO, it would be better to resize all our models to 1/1/1 size and remove the resizing from the model. Then, only apply resize according to creature level (which will make the weapon bigger as well).

EDIT1: If you don't want to mess with this tool, just create a PR with the cultist using the invisible weapon and I will resize it.
EDIT2: Note that the same problems as for the weapons will occur for the bow/crossbow which will be displayed correctly if the creature is sized like Elf/DarkElf.

**Comment by Danimal696** [comment]
can we use it to resize to 1:1 all meshes? thats the best solution

**Comment by hwoarangmy** [comment]
> can we use it to resize to 1:1 all meshes? thats the best solution

yes. Have you tried ?

**Comment by hwoarangmy** [comment]
BTW, note that resizing to have all creatures at same scale is the best way to attach chickens to creatures when they eat (if one day we want to implement specific animations)

**Comment by Loobinex** [comment]
Or just make all creatures/heroes eat by falling face first on the chicken. ;-)

**Comment by Danimal696** [comment]
done :) 
Now i would like for us to settle on the animations, the knitgh is next on line for animation, lets not make it wait more than usual (a year or two...)

**Comment by hwoarangmy** [comment]
Note that I've created the PR with resizing of all our models

**Comment by hwoarangmy** [comment]
Also note that I've uploaded a new version of Ogre mesh magick (the version on their website uses Ogre 1.6 so I downloaded and compiled it with Ogre 1.9). If you want to give a try, you can download it here:
http://download.tuxfamily.org/opendungeons/Tools/OgreMeshMagick.zip

**Comment by hwoarangmy** [comment]
The wiki is done:
https://github.com/OpenDungeons/OpenDungeons/wiki/Adding-a-model-in-the-game

@akien-mga I've added in the wiki how to add a new model. I've added in our repo the tools to resize with windows (OgreMeshMagick). Could you please build the same with Linux and add a tarball ?
The tools available on the Ogre website are pretty outdated and compiled against Ogre 1.7 (at least for windows). The code is here:
https://bitbucket.org/ogreaddons/meshmagick

To compile, you will have a problem complaining that Ogre::String::BLANCK is not found. You will need to replace it with Ogre::StringUtils::BLANCK.

And that's all, it should compile like that ^^
