### ISSUE TITLE
Unclaimed portals should be visible on the map

### ISSUE THREAD

**Issue by Loobinex** [OpenDungeons/OpenDungeons#1174]
Unclaimed portals should be visible on the map (and by default portals on maps should be unclaimed). This way the player knows which way to dig to claim the initial portal, one of the first things he does on any map, and not dig into an enemy pocket before he has his first creature.

But also importantly, this allows him to see which player is spawned where on the map. When a player claims it, before the fog of war returns, it should turn red/green/blue on the map. Currently playing levels is a drawn out affair because the maps are big and you don't know where your enemy is, this change should help combat that.

If a mapmaker does want a player/portal to be hidden, he can make it claimed so it cannot be seen.

**Comment by Bertram25** [comment]
> Unclaimed portals should be visible on the map (and by default portals on maps should be unclaimed). This way the player knows which way to dig to claim the initial portal, one of the first things he does on any map, and not dig into an enemy pocket before he has his first creature.

Hey, I think the actual problem you had is that you had some hard time spotting your own portal on some map, right?

I personally disagree that unclaimed portal should be spotable on game because it makes something simple more complex without any proper gaming reason, IMHO.

What I do rather think is that the portal that should be claimable near your own temple should either be obvious through proper level design, or for special needs, we may have to make specific rooms visible to the players. But this is not only about portals IMHO.
Why not speaking about adding support to make a specific room visible instead, or event support?

**Comment by Loobinex** [comment]
I've had both problems,... the map I played two days ago I had to dig tunnels through the entire map until I finally found my enemy. A few weeks ago I played a level where I had to restart the game 2 times because I died before I found a portal.

Spotting unclaimed portals through fog of war has the same gaming reason as gold and rock being able to be spotted: You need this basic information about the level to plan your play.
Knowing where your enemies are is also important. It is only annoying for the player not to know, not something fun to find out.

Note that Dungeon Keeper also had the unclaimed portals visible.

**Comment by Bertram25** [comment]
> Spotting unclaimed portals through fog of war has the same gaming reason as gold and rock being able to be spotted: You need this basic information about the level to plan your play.
> Knowing where your enemies are is also important. It is only annoying for the player not to know, not something fun to find out

Interesting bits here. Seems you treat portals as resources, while I treat them as treasures (I mean the ones you discover). Both points of view are perfectly right, IMHO.
What about: Making portals visible on the full map view (yet to be implemented, though.), so that you have a general direction where to go and can plan, but don't actually spy there, without the corresponding spell?

**Comment by Loobinex** [comment]
Both points of view are indeed correct, that is why the mapmaker should have the option to use them both ways. Usually initial portals are not used as treasure, neither are 'contested portals'(the one in the center everybody fights over). But especially on campaign levels they can be a discoverable bonus.

Therefore unclaimed portals are visible(I think just exposed is the easiest way, but I'm open to whatever) and portals used as bonus are claimed by white and thus invisible until discovered.

**Comment by Bertram25** [comment]
> Therefore unclaimed portals are visible(I think just exposed is the easiest way, but I'm open to whatever) and portals used as bonus are claimed by white and thus invisible until discovered.

Can work. @OpenDungeons/developers WDYT?

**Comment by hwoarangmy** [comment]
> Therefore unclaimed portals are visible(I think just exposed is the easiest way, but I'm open to whatever) and portals used as bonus are claimed by white and thus invisible until discovered.

Being allowed to see some unclaimed portals and not some others would look like a bug to me. IMHO, we should go for a way or the other. I've nothing against being allowed to see unclaimed portals at game start. That would also avoid the problem with one of our levels where you start without a portal and, if you are unlucky, you may encounter hostile creatures before getting the portal (which means death).

Allowing to see the portals would also allow to make some maps with portals in the middle allowing brave players to rush for them. It would also allow to locate enemies. Moreover, it is pretty easy to understand that as a keeper, you can detect the link with heaven/hell or wherever the creatures come from a portal produces (ie it doesn't look weird storywise to know where portals are). Seems like a good idea to me.

**Comment by Loobinex** [comment]
> Being allowed to see some unclaimed portals and not some others would look like a bug to me.

I agree, that's why ALL unclaimed portals can be visible, and all claimed portals can be hidden.

**Comment by eugeneloza** [comment]
I think, that it's a bad idea, becasue it'll reveal enemy position. However, portals and other claimable objects can be visible IF they are no further than specific distance from your dungeon heart (e.g. 1/4-1/3 of the map size). 
This will reveal portal prepared for you to claim and hide enemy portals.

**Comment by Loobinex** [comment]
Why is it a bad thing to know where your enemy is? This isn't a rts where you can easily send scouts around the map,.....

**Comment by hwoarangmy** [comment]
> I agree, that's why ALL unclaimed portals can be visible, and all claimed portals can be hidden.

In this case, you will not know where your enemy is in many levels as they start with a claimed portal.

> I think, that it's a bad idea, becasue it'll reveal enemy position

Well, in a 400x400 map, it can be pretty annoying to search the whole map for a player turtling. Moreover, it makes a big difference between a player who knows the level and a player who doesn't.

> However, portals and other claimable objects can be visible IF they are no further than specific distance from your dungeon heart (e.g. 1/4-1/3 of the map size).

As I said, we should go a way or the other IMHO. Half solutions are never player friendly...

**Comment by Loobinex** [comment]
> In this case, you will not know where your enemy is in many levels as they start with a claimed portal.

That is a problem with the maps. And that's not surprising because currently there is no reason for mapmakers to leave the initial portal unclaimed except to annoy to player.
Like mentioned in the very first post here, by default portals should be unclaimed.

**Comment by Danimal696** [comment]
Yes, i also think you should now where they are at start.

**Comment by hwoarangmy** [comment]
Now that we are talking about portals, what about dungeon hearts ? Shall we also display them at game start ? It also doesn't look weird to me that a keeper can "feel" the other keepers dungeon hearts...

**Comment by Loobinex** [comment]
I'd say no,...

If you know where the portal is you know where to find your enemy, but then you still need to explore his dungeon to find his temple which is nice.

**Comment by Danimal696** [comment]
No as well, its too much of an advantage.

**Comment by hwoarangmy** [comment]
Concerning this issue, IMHO, it would be better to make all portals (claimed or not) visible or not visible. It seems like most people here requested to make them visible. Do we agree ?

**Comment by Loobinex** [comment]
Could you elaborate a bit on how you formed your opinion on why both those situations would be better than the one I'm proposing? Is there any advantage for the player, or is it just easier to implement?

Personally I think it would be a big waste, as making them always invisible makes it so you don't have a target to go for and can't see player locations on large 4 player maps, and making them always visible is making it impossible to have hidden portals that can be uncovered through exploration and makes it impossible to hide player locations on small 3-player maps.

But if I had to pick one, I'd say always visible, yes.

**Comment by hwoarangmy** [comment]
Because as a player, it would not seem straight forward to see some portals and not others. In a map where you wanna add a hiden portal, you will have to make it belong to some inactive player (otherwise, it would be rogue and, thus, visible). That means that if you don't want it to spawn creatures, we will have to find a trick for the portal not to spawn creatures.
Code wise, it would not be that difficult but it sounds not very user friendly to me. Usually, I prefer to go for the simplest solution and see later if we really have a need rather than adding complex stuff (be it in the editor or ingame - by complex, I mean the configuration needed to achieve the behaviour you described) that will make the game more less intuitive.

**Comment by Loobinex** [comment]
Has this behavior ever struck you as odd in the Dungeon Keeper games or any of the clones? Because the very first thing a player will do every single time when he plays a game is open the map to check the layout of the level and the location of his first portal, having the unclaimed portals as visible will be the most normal thing in the world.

As soon as the portals are claimed, fog of war will come over them, not giving you a continued look in the enemy dungeon giving people an innate understanding that claimed portals are not visible.

As for your complication, I think it would be a very wise idea to have a 'white player' anyway, that is never an active seat but can come with rival creatures, traps, pre-build dungeons or portals. White would always be the player to be a map feature.

**Comment by hwoarangmy** [comment]
> White would always be the player to be a map feature.

It exists. That's what we call "rogue seat". In code, its creatures do not behave exactly like the ones owned by other keepers. They do not become angry/hungry/sleepy. And when a creature becomes furious and cannot leave the dungeon (because of a closed door or because it is somewhere it cannot reach any portal), it becomes rogue.

> As soon as the portals are claimed, fog of war will come over them, not giving you a continued look in the enemy dungeon giving people an innate understanding that claimed portals are not visible.

I was only thinking about allowing the players to know where the portals are, not giving permanent vision until it is claimed. Giving vision is not a good thing IMHO as it would allow to see who and when another player claims it.

**Comment by Loobinex** [comment]
But that's the whole point: Seeing the location of your enemies/allies without actually knowing anything about their dungeon.

**Comment by hwoarangmy** [comment]
I will go for displaying every portal at game start as unclaimed portals (giving no vision). That will allow to locate enemies and see if there are portals reachable.
Then, if we want to, we can tune the behaviour.
