### ISSUE TITLE
Possible to place trap on rival ground

### ISSUE THREAD

**Issue by Loobinex** [OpenDungeons/OpenDungeons#1205]
I played git20160601 and placed a boulder trap, but moments before my worker could deliver the trap the tile it was placed on was taken over by a rival worker. This did not deter my worker and he still placed the trap on enemy ground, which should not happen. 

See screenshot:
![rivaltrap](https://cloud.githubusercontent.com/assets/13840686/15795746/fdb1b792-29f4-11e6-8100-642c9fc280b1.jpg)

**Comment by hwoarangmy** [comment]
I remember this one. It is not a trap. Before I claimed the tiles where the trap is, did you build a boulder trap here ?

My guess is that you built a trap and I claimed the tiles while your worker was carrying the trap. So, it dropped it there.
But when I saw it, I also made a try and saw that it did not triggered. Then, I built a boulder trap in the corridor and dropped a worker. It brought the trap to activate mine. A nice gift for me ^^

However, it might be good to somehow display something so that it is easier to know if it is an activated trap or a crafted trap. Maybe some particle effect on crafted traps ?

**Comment by Loobinex** [comment]
Could be, but then it went very smoothly because I was watching the whole time to see what would happen when you claimed the tile with my boulder trap. If the worker indeed dropped it allowing you to steal it, this would be fine.

Although you could argue that the trapbox should be returned to the workshop by the worker instead of dropping it.

**Comment by hwoarangmy** [comment]
> Although you could argue that the trapbox should be returned to the workshop by the worker instead of dropping it.

So far, if a crafted trap is left on the floor (because the worker was picked up or is killed), it stays there. But workers will consider bringing it to a trap that needs it.
I've nothing for or against bringing them back to the workshop, though.
