### ISSUE TITLE
Treasure room stopped being recognized by workers

### ISSUE THREAD

**Issue by Loobinex** [OpenDungeons/OpenDungeons#1206]
I played a multiplayer game in git20160601 and at some point I encountered a near blocking bug with my treasure room. I received the message that I had no treasure room and my workers would no longer bring gold there, causing me to quickly go broke. I could not build a new treasure room because I did not have the gold for it.
I sold rooms to build more treasure room and build bridges to be able to manually pick up some mined gold and I could continue playing. Several other times I received the warning that my treasure room was full when it was not the case.

See the screenshots below, and find the replay attached.

![treasure1](https://cloud.githubusercontent.com/assets/13840686/15795916/434950fc-29f6-11e6-9f5f-3793c1960f1a.jpg)
![treasure2](https://cloud.githubusercontent.com/assets/13840686/15795889/0c152912-29f6-11e6-8f7c-71f69cdd3bcd.jpg)

[replay_20160603_235510.zip](https://github.com/OpenDungeons/OpenDungeons/files/298563/replay_20160603_235510.zip)

**Comment by hwoarangmy** [comment]
I've had a look at the replay and you can see that no workers go between your rooms and the place where you dug gold.
This bug is linked to floodfill and is the same as #1199 even if the consequences are not the same.

The message no treasury available is displayed because the workers cannot find a way to the treasury.
