### ISSUE TITLE
Cannot destroy a room on reclaimed title

### ISSUE THREAD

**Issue by roman-yagodin** [OpenDungeons/OpenDungeons#1250]
Playing 0.7.0 (Linux version) I've noticed, that I cannot destroy rooms build on titles, that were reclaimed from another player. The destroy tool shows "retrieve 0 gold" and do nothing. The other strange thing (could be somewhat linked with the issue) is that workers seems ignore remaining enemy-claimed fortified walls if those are around my rooms.

**Comment by hwoarangmy** [comment]
Hi

> I cannot destroy rooms build on titles, that were reclaimed from another player

Which room have you tried to sell ? The only claimable rooms right now are portals and bridges. And portals cannot be sold (be it stolen from someone else or owned since game start) so I assume that's what you wanted to sell and that's why it didn't work.

> workers seems ignore remaining enemy-claimed fortified walls if those are around my rooms

Workers should claim enemy fortified walls as soon as there is no enemy claimed ground tile connected to the given claimed tile. Are you sure there was no claimed ground tile next to the enemy claimed wall ?

Note that if you notice strange behaviours, please also post the replay (when you exit the game, check "keep the replay" checkbox) and the logs so that we can know what happened. If you can't find those, please ask here. It should be somewhere like "~/.local/share/opendungeons/"

**Comment by roman-yagodin** [comment]
> Which room have you tried to sell ? The only claimable rooms right now are portals and bridges. 
> And portals cannot be sold (be it stolen from someone else or owned since game start) 
> so I assume that's what you wanted to sell and that's why it didn't work.

I've tried to sell my own rooms (e.g. treasury) build on my own titles, which were (previously) claimed by enemy.

> Are you sure there was no claimed ground tile next to the enemy claimed wall ?

Well, I'm pretty sure:

![odscreenshot_2016-08-18_084150_2](https://cloud.githubusercontent.com/assets/5691178/17763597/b82ba63a-652a-11e6-91d8-647fcc6125ec.png)

Other files - a savegame, short replay and log:

https://github.com/roman-yagodin/bug-reports/tree/master/opendungeons/opendungeons/1250

**Comment by hwoarangmy** [comment]
Thanks, your report seems pretty complete. I will have a look ASAP. But at first glance at your screenshot, it seems the treasuries doesn't provide you with vision so it seems you are not considered as owner of the tiles they are on. Thus, you cannot claim the walls near to them (nor sell them). The strange thing is that your creatures should attack them.

**Comment by hwoarangmy** [comment]
Note to self: I should add a log when a tile is claimed

**Comment by hwoarangmy** [comment]
@roman-yagodin I've had a look at the files you posted and, indeed, the tiles belong to player 2 while the room belongs to you. This seems to have been kept in the savegame. I've tried to reproduce the bug but couldn't (it worked well for me when I tried to claim enemy claimed tiles and then built a treasury).

Do you remember how you achieved this result ?
Have you saved/loaded games or played the level at once until the bug ?
Was the behaviour present before you saved the game ?
When you built the room, were the tiles claimed by your workers ?

**Comment by roman-yagodin** [comment]
> Do you remember how you achieved this result ?

No, and I cannot reproduce it either, as when I load older savegame (before rooms was build), workers behave just as intended trying to reclaim enemy-claimed fortified walls and my newly build rooms are destructible.

> Have you saved/loaded games or played the level at once until the bug ?

I save/loaded several times.

> Was the behaviour present before you saved the game ?

I haven't noticed. Can only guess that it was showed up after loading a savegame.

> When you built the room, were the tiles claimed by your workers ?

I've build rooms on my own titles just after they were reclaimed from enemy by my workers.

**Comment by hwoarangmy** [comment]
ok. Let's keep that in mind and do not hesitate to post the replay and log if you can reproduce it.

**Comment by roman-yagodin** [comment]
I tried to reproduced the issue again and have some progress at this time.

I've loaded game from `2016-08-13_213203-SK-DuelToDeath.level` savegame - before any my rooms was build on reclaimed titles. Playing game don't produce any issues, but saving to 
`2016-08-20_121349-SK-DuelToDeath.level` after building my rooms and then reloading game from the save shows up the issue.

See files here: https://github.com/roman-yagodin/bug-reports/tree/master/opendungeons/opendungeons/1250/part2

There are: `replay_20160820_121143.odr` - replay from `2016-08-13_213203` to `2016-08-20_121349` savegames and related log - `opendungeons.log.2`.

**Comment by hwoarangmy** [comment]
Thanks. Now, we have a better vision of what is happening. I will have a look ASAP

**Comment by hwoarangmy** [comment]
Ok, I've seen what's going on. You have spotted 2 different bugs here.
First, when a room is destroyed, it should be kept until all human player have seen it destroyed. Since you are playing skirmish, you are the only human player and the room (the treasury you destroyed) should have been removed. But it seems it is not.

Second, when the rooms are created, the tiles they are on are associated with the room. In the case, it is associated with the old one (the one you destroyed) because it is created after yours and thus, the tiles don't belong to you.

Note that if the first bug was not present, you would have not noticed the issue. But on a multiplayer game, it could still happen. So, we are lucky the 2 bugs are present ^^

**Comment by Loobinex** [comment]
You must get lucky a lot.
;-)

**Comment by hwoarangmy** [comment]
> You must get lucky a lot.

At least when new bugs are found ;-)

**Comment by hwoarangmy** [comment]
@roman-yagodin The bug is fixed and should be released in the next snapshot. Thanks for reporting. If you see something else or if you want to give some feedback, please do not hesitate.

**Comment by roman-yagodin** [comment]
OK, thanks!
