### ISSUE TITLE
Issues with libstdc++.so.6 in Linux 64-bit binary package

### ISSUE THREAD

**Issue by bark10** [OpenDungeons/OpenDungeons#1259]
I'm having issues running the 0.7.1 Linux64 binary on Trisquel 7.0 (3.13.0-93-lowlatency). I have tested the binary on two different Trisquel boxes (one being a fresh install) and on Ubuntu 15.04 (3.19.0-68-generic x86_64). The binary works fine on the latter, but does not in Trisquel.

Interestingly, binary packages prior to OD-0.7.0 still run fine (on both Trisquel boxes), while 0.7.0 and 0.7.1 produce the error messages below.

http://pastebin.com/GgFZ4UwV

**Comment by akien-mga** [comment]
Thanks, I'll have a look together with #1256. Prior to 0.7.0, I had another script to generate the binaries in my chroot but I sadly lost it, and had to go back to the earlier version we currently have versioned in the git repo. I'll have to compare the libraries I bundled in 0.6.0 and 0.7.1 and see what needs fixed.

**Comment by akien-mga** [comment]
Do you still have that error log? The paste expired.

**Comment by bark10** [comment]
Certainly. Link in initial report has been replaced - this one will not expire.

**Comment by akien-mga** [comment]
Thanks. The issue is that the chroot I used to build the binaries is a Mageia 5 x86_64 with glibc 2.20, which is likely too new for  Trisquel 7.0.
For previous binaries, I was using Mageia 4 x86_64 with glibc 2.18, which gave better compatibility with older distros. I changed the chroot distro version because I lost the previous one when reinstalling the host OS carelessly, and somehow could not get Mageia 4 to install anymore with the usual method. I'll give it another try soon.

**Comment by akien-mga** [comment]
At this point it's unlikely that I'll attempt making new binaries for 0.7.1, but in the meantime they should be old enough to run on most distros...

For 0.8.0 I'll try to come up with a better system to avoid such compatibility issue (like linking with `-static-libgcc -static-libstdc++`).
