### ISSUE TITLE
Execution immediately failed with "Resource with the name MedievalSharp already exists" exception

### ISSUE THREAD

**Issue by Hikawa** [OpenDungeons/OpenDungeons#1271]
OS: ubuntu 16.04
Source commit: 00de4b92af21127a312b23263a96722ae3e56aac
OGRE: 1.10 (custom build)
CEGUI: 0.8.7 (custom build)

Ogre.log: http://pastebin.com/raw/rwLSyBNi

**Comment by hwoarangmy** [comment]
Hi,

It seems like the system loads the font used in the game twice. I've never seen this problem but never used CEGUI 0.8.7. I will try when I can.
Could you please try an older version of CEGUI (0.8.4 if possible since it is the one I use and probably the one we tested most) ?
If not, could you please try Linux binaries so that we know if it comes from your computer settings or from our code or the libraries ?
You can find them here:
http://opendungeons.github.io/downloads.html

**Comment by oyvindln** [comment]
I've used CEGUI 0.8.7 on Ubuntu (16.10) without having this issue, so I don't think that's the source of the problem.

**Comment by oyvindln** [comment]
Changing the addResourceLocation calls in resourcemanager.cpp to not be recursive solved this for me, not sure why they were set to recursive in the first place.
