### ISSUE TITLE
Use polymorphism for render requests instead of a huge switch/case?

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#137]
Everything is in the title.

IIRC, this was discussed on the forums and started by @tomluchowski .

If tom doesn't want/ can't do it anymore, someone else may want to bite this one.
Let's give @tomluchowski a week or two to answer. Afterwards, the task should be considered free to take again.

**Comment by Bertram25** [comment]
No answers so far. I'm considering this task free to take again.

**Comment by hwoarangmy** [comment]
ok. Do you think we should even keep the render manager ? It was probably usefull because of the old thread system. Now that we have only one thread on the client side, I don't see why we would need this anymore.
I can see good reasons to remove it :
- The code will be more readable (you don't have to search for a message in another class when you end up in a function that sends it).
- When an exception will be triggered, you will have the true call stack including the original call . For now, if several functions triggers the same message, if we segfault in the renderer, we cannot know where the message was sent
- At this moment, most of the sent messages use pointers to game entities. That could bring bugs as we are not guaranteed that the entity is not modified during the time when the message is sent and the time when the message will be executed. This point is the most relevant and, even if we choose to keep the renderer, we should deal with it.

The bad points :
- More work
- The actual code works, why shall we change it ?
- If we come back to use threads again, it will be a waste to have to undo this

What do you think ?

**Comment by Bertram25** [comment]
Heya, :)

> If we come back to use threads again, it will be a waste to have to undo this

Just to be clear, if someone ever have to readd thread in the previous fashion (with all the semaphores spread everywhere and all that), you will see me dance with red spotlights and 'Warning! NO! This is wrong!!' panels ;) To me threads are to be dealt with clean interfaces, preventing bugs by design, not simple luck. (And I do think you are rather clear with this yourself. :])

That sensitive point apart, sending render requests to a pile directly, (just like we do for client server message sending) instead of adding them to a render manager that does it, making the request dealt in two steps for nothing may be a good idea.
That said, the render thread is separate AFAIK so we should still make sure to process those render requests the same way/at the same time they were processed using the render manager.
Apart from that, it's ok for me. :)

Feel free to correct me if you see something, though.

**Comment by hwoarangmy** [comment]
> And I do think you are rather clear with this yourself. :]

As you know, I second you on that point. But I tried to bring up all the good/bad reasons I could think about :)

> the render thread is separate AFAIK

Really ? The game engines I've worked on until now used a listener to allow changing the game state within the rendering thread (and Ogre looks much like that with the frame listener). That allows them to not have costly synchronisation during rendering. But if there is a dedicated thread on Ogre different from the one calling the frame listener, it might not be interesting to remove the render manager.

**Comment by Bertram25** [comment]
I've checked some article about that, and I've seen many about threading the Ogre render engine. This means that by default it isn't threaded. Thus my apologies, it must have dreamt that.

While it is possible, it is not done, so indeed we could drop the render manager if it means simplifications. ;)

**Comment by hwoarangmy** [comment]
> Thus my apologies, it must have dreamt that.

No problem :)

> While it is possible, it is not done, so indeed we could drop the render manager if it means simplifications.

The thing is that before doing that, we should check if the performance are the same if they drop. Which can be easily tested in the render manager by calling handleRenderRequest when a render request is sent instead of adding it to the queue.
So, I will try to do that and see how performance goes. Then, if I see no problem, I will make a PR that does that. And if nobody sees any problem, we can do it correctly :)
What do you think ?

**Comment by Bertram25** [comment]
Yep, we can even only make a PR only meant to be tested. :)

It's empirical but we don't have time to do better. I do hope Ogre is batching the rest. :)

**Comment by oyvindln** [comment]
Right now, the render manager also does things it shouldn't, like deleting map objects. It's not ideal that it's tied in with the GameMap given that it's in use before we even load a map.

**Comment by hwoarangmy** [comment]
> Right now, the render manager also does things it shouldn't, like deleting map objects

Yes. When I added the server game map, I added a function to queue deleted objetcs and to clean up that is called at each turn (as for obvious reasons, server game map do not use rendering). When the render manager had its own thread, it was probably good to delete objects there. But now that there is only 1 thread that handles client gamemap, we could use the same as on server side (processed after the rendering phase).
