### ISSUE TITLE
Add the spikes trap in game.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#139]
Adding the spike trap in game will be fun IMHO.

Here is an icon proposal: http://game-icons.net/sbed/originals/trigger-hurt.html
I've adapted the icon:
![trigger-hurt](https://cloud.githubusercontent.com/assets/765917/4234293/68d64236-39b5-11e4-8759-fb324453e617.png)

The trap logic should be adapted so that it is triggered something like only once per 3 turns when one or more creatures steps on it. The damage done should kill any level 1-2 creatures, hurt severely the level 3-5, less the 6-9, and so on...

**Comment by hwoarangmy** [comment]
> I'll adapt the icon to remove the circle and make the spikes higher.

That's what I was going to suggest. And maybe sharper too.

> The damage done should kill any level 1-2 creatures, hurt severely the level 3-5, less the 6-9, and so on...

You can use a static hit damage and that will do. BTW, are you planning on hardcoding traps or to have a file definition like creatures ?

**Comment by Bertram25** [comment]
> You can use a static hit damage and that will do. BTW, are you planning on hardcoding traps or to have a file definition like creatures ?

Like everything, hard-coded first, configurable afterwards once proven working. @Danimal696 will complain soon enough, anyway. ;)

If one wants to soft-code it, a config/trap.def file should be created with info in it for each trap type, IMHO. On the code counter-part, I guess we need more and more a config manager for the entities, equipment, and so on.

**Comment by Danimal696** [comment]
Hardcoded sounds fine for now, as long as the base hit damage is sensible it shouldnt even be changed.
 Just one worry, traps should not be destroyed by hiting them. They should get disarmed after being triggered a number of times, just like in dk1, it was stupid in dk2 when you could possess a creature and smack all traps getting no damage at all, whereas in dk1 you have to either sacrifice your imps and hope they claimed the tile before is triggered again or get some tank minions to suck all the damage until it gets disarmed. It added a nice sapper element and made traps very usefull.

**Comment by Bertram25** [comment]
> it was stupid in dk2 when you could possess a creature and smack all traps getting no damage at all,

I didn't know that one. :) Nice trick, eh eh.

> They should get disarmed after being triggered a number of times,

So you mean that the trap shouldn't be attackable, but removed when the tile is either claimed by another team or triggered a certain number of time? Are you ok with that logic?

**Comment by Bertram25** [comment]
I've adapted the icon, see description.

**Comment by Danimal696** [comment]
> So you mean that the trap shouldn't be attackable, but removed when the tile is either claimed by another team or triggered a certain number of time? Are you ok with that logic?

Yes, maybe trap should add a bit more time to claim tile since claiming its stackable (i think)? and once its disarmed it wont be active again until (we have to decide) a kobold resets it or a new trap is automatically made on forge and a kobold fetchs and mounts it again on the same place (transparent model of unbuilt/disarmed traps on their building place?)

**Comment by Bertram25** [comment]
> Yes, maybe trap should add a bit more time to claim tile since claiming its stackable (i think)?

I agree, more time should be needed. I would have to recheck the claiming logic, but I know we can make a difference happen there.

> and once its disarmed it wont be active again until (we have to decide) a kobold resets it or a new trap is automatically made on forge and a kobold fetchs and mounts it again on the same place (transparent model of unbuilt/disarmed traps on their building place?)

IMHO, the overall best logic for this is:
- The traps icons should be available only when one or more traps have been built in the forge.
  Should we be able to ask for a particular trap to forge?
- When placing a trap, the trap is placed in the unbuilt/disarmed state.
- A kobold will then fetch the trap in the forge and arm the trap where requested.
- Same when the trap is disarmed/empty and one is available.

In the meanwhile, before the overall trap logic is added, we could make them costly and slow?

**Comment by hwoarangmy** [comment]
> They should get disarmed after being triggered a number of times

I agree. Otherwise, they will be so easy to disable that they would serve for nothing. If we want to make them usefull, they need to be as deadly as creatures (if we want to add a specialization for them)

**Comment by Danimal696** [comment]
Regarding trap production, we can take two known paths:
DK1: traps are produced automatically and free by forge workers, they keep an average number of them and fill the less stored (as in more used) ones. Each trap built takes one space on forge, many traps will clutter a forge and made it useless until one of them is used freeing one space. 
Not a bad approach, but since they are free i would made each of them to be very slow manufacturing (even more depending on power/complexety), this forces to have a healthy blacksmith workforce; and they dont have to clutter the forge, a wall object can be made to represent their storage and each 3 forge tiles equal to one storage space.

DK2: traps cost money and are only produced when you place their construction on one place, then blacksmiths rush to the forge, make it and go back to their bussines.

A mix of the two? Traps/doors are free but take a lot of time/workforce, once placed to build or to be replaced, blacksmiths start working on it asap, no traps are stored, they just produce the needed one. Meanwhile, when no trap/door is requested to build they are forging weapon upgrades ("upgrade points"), that are represented into a wall object (it would be a graphical representation of how many "upgrade points" the forge has acumulated) think of a weapon rack that gets fuller of weapons as more points are created. 
Any creature that can upgrade weapon and is dropped on forge tries to update first, weapon then, shield (blacksmiths wont have upgradable weapons to avoid them hogging all upgrades when put to work); if the creature has a low level weapon and there is enougth produced "upgrade points" it will try to update weapon, to the best one affordable. A forge should be able to store a fixed number of "upgrade points" per tile, so a small forge (3x3) can only store enougth of them to upgrade to a weapon a rank, while bigger ones could store enougth to upgrade a weapon to epic rank.

**Comment by hwoarangmy** [comment]
That's an interesting point of view and deserves to be discussed in the forum IMHO :)

**Comment by hwoarangmy** [comment]
Is there some model for the spike trap ? If so, I will integrate it :)

**Comment by Bertram25** [comment]
> Is there some model for the spike trap ? If so, I will integrate it :)

The model is ready AFAIK: https://github.com/OpenDungeons/OpenDungeons/blob/development/models/Spiketrap.mesh + skeleton

I'll have to integrate the icon first if you don't feel like adding it.

**Comment by hwoarangmy** [comment]
ok, I'll rebase after the icon is added then. I prefer to let you integrate these as you know better what goes to credits and stuff as I do :)

**Comment by Bertram25** [comment]
k, will do that asap and as first, then. :)

**Comment by Bertram25** [comment]
Here is the converted icon. What's left is to add it to the texture and link it with the corresponding imageset file. I'll do it if you cannot for any reason:

![spiketrap](https://cloud.githubusercontent.com/assets/765917/4421008/a79e0e06-457f-11e4-9ee7-80930aeabc52.png)

License-wise, there is no change as the icon texture license isn't changed by a CC-BY 3.0 image.

**Comment by hwoarangmy** [comment]
ok, I'll do that
