### ISSUE TITLE
Tileset - Make it configurable

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#14]
Add a file configuring the tileset meshes to load and rotate according to their neighbor tiles.

This file will permit to setup the mesh file to seek, how to rotate it, and will have to support when two tiles type are foreign or not when computing the mesh file to load according to its 8 neighbors. Straight and diagonal ones.

The file will be called `config/tileset.cfg`
It will list every neighbor possibility and give the corresponding mesh file to load.

This is a pre-requisite to biomes support. (Tileset auto total conversion.)

**Comment by hwoarangmy** [comment]
For my information, could you please explain what is biomes support ?

**Comment by Bertram25** [comment]
> For my information, could you please explain what is biomes support ?

Sure :)

A biome is somehow a ground type, e.g: Jungle, Desert, Volcano, ... (Only foolish examples not forcefully meant to get in game.)
This means that we could define a tileset per biome, and thus get total conversions of the terrain tiles used.
AFAIK, it is a desired goal to have levels where you no more are in a "standard" underground level, but in jungle galleries, or in a pyramid underground, ...
This will require quite some tiles, so we have time for that.

**Comment by Danimal696** [comment]
I think these ones could make it in:
-Default dungeon
-Desert/piramid
-Jungle/aztec-mayan piramid
-Ice/viking-dwarf

**Comment by hwoarangmy** [comment]
Ok, I see. Thanks. Then the level should define the wanted tileset.

**Comment by Bertram25** [comment]
Unassigned myself. I'll only keep assignment where I'm actual working on stuff. It's saner IMHO.

**Comment by hwoarangmy** [comment]
I will have a look at this one because it is linked to save game.
But do we really want to define tiles according to its 8 neighboors ? That would mean 256 values + 1 (or 512 if we want to have different ground tiles depending on their surrounding tiles). And that for each tile type (dirt, gold, rock, claimed, water, lava).
That means that a tileset will be defined by 1536 lines, which is memory consuming.

What about defining a tile only by its 4 surrounding tiles ? Or, better, allow to have different meshes for the central tile (if full or not) according to the 4 surrounding tiles (that would mean 32 values per tile, which seems more acceptable to me).

Moreover, in the code and in the meshes, we can see that OD was prepared to have tiles with different fullness (0, 25, 50, 75). Currently, we don't use it (only to differentiate if full or not). Do we want to keep it ? If yes, that would mean 4 times more values (than 256 or 32 depending on what we choose).
IMHO, the tiles are dug so fast that we can drop this to keep only full or not.
@Bertram25 @oyvindln @Danimal696 @akien-mga WDYT ?

**Comment by oyvindln** [comment]
> Or, better, allow to have different meshes for the central tile (if full or not) according to the 4 surrounding tiles 

I support this. I think we should try to keep the tiles relatively simple.

> Moreover, in the code and in the meshes, we can see that OD was prepared to have tiles with different fullness (0, 25, 50, 75). Currently, we don't use it (only to differentiate if full or not). Do we want to keep it ?

I agree with this. (Also, I think the old tiles with different fullness values are still in the Repo, we may want to get rid of them.)

**Comment by hwoarangmy** [comment]
> I think the old tiles with different fullness values are still in the Repo

I confirm. Then, I will remove them, too

**Comment by hwoarangmy** [comment]
@Danimal696 Note that if you agree to choose the tile depending only on the 4 surrounding tiles, a tileset like the current one will be composed of only 6 tiles (including the ground tile) by only using rotations. But the current tileset will have to be fixed as ATM, the tiles do not end up at the coordinates points (0:0, 0:1, 1:0 and 1:1) so they don't connect well.

**Comment by Danimal696** [comment]
im in favor of simplification, that said, i will need a more visual reference for fixing the current tileset to what we want. But it shouldnt pose a big problem to do so.

**Comment by Danimal696** [comment]
you have access to the blend source of the tileset, rigth? yuo can either tell me the ones you want or erase the useless and send me the file

**Comment by hwoarangmy** [comment]
I've already erased the unused tile meshes. I will release the tileset soon so you can have a look by yourself. I've even added another tileset for testing based on the old one that was in the repo ^^
