### ISSUE TITLE
Combat behaviour upgrade

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#154]
As discussed here: http://forum.freegamedev.net/viewtopic.php?p=59460#p59460

Currently, the creature behaviour in fight is rather passive.

In order to fix this, the creature thinking logic before entering battle should follow those rules:
- The fighter creatures should check their "health" + "mood" before going or keep going to combat or fleeing.
- During the fight or before, if HP < 10%, flee to bed.
- Before fighting, check HP + mood (hunger + awakness). If too low, the creature has up to 20% chances of fleeing (never more than 20% or the AI will never fight). Moreover, a creature that chooses to fight will not check its mood until it dies or until the battle is over (or its ennemies are not visible because they flee)
- Note that mood is decreased by hunger, drowsiness, and later, other creatures, lack of pay wage, and other things. For now, hunger + drowsiness can be checked < 10% instead.

Fighting logic should be :
1 - If it is at the range distance, it should shoot (if melee unit, in a neighboor tile)
2 - If too near or too far, move (at its range distance)
3 - During attack cooldown, like every other unit, it cannot move. That would allow not too slow units to retaliate even if a little bit slower than the ranged unit.
4 - Go to 1

The creatures should try to attack the closest ennemy to them.

We can remove Battlefields from code.

**Comment by hwoarangmy** [comment]
I would say :
- When a creature finds out an ennemy, it should check "health" + "mood" before choosing to fight or to flee. Fleeing should be choosen depending on the creature (some are more likely to flee than others). Fleeing probability should be maxed so that even if a creature is sleepy and hungry, it can go fighting (especially since AI do not make dormitory and hatchery ;) ).
- If the creature chooses to fight, mood, should not matter anymore until it dies or its ennemy dies. But if it is too badly wounded (health < 10%), it should flee.

If we go for that, we should decide if we remove from the code everything related to battlefields...

**Comment by Bertram25** [comment]
> Fleeing should be choosen depending on the creature (some are more likely to flee than others). Fleeing probability should be maxed so that even if a creature is sleepy and hungry, it can go fighting (especially since AI do not make dormitory and hatchery ;) ).

True and agreed.

> If the creature chooses to fight, mood, should not matter anymore until it dies or its ennemy dies. But if it is too badly wounded (health < 10%), it should flee.

Yep, that's what I had in mind more or less, anyway.

> If we go for that, we should decide if we remove from the code everything related to battlefields...

I'd say yes, let's go for that, we can always fine-tuned if not already enough later. And yes, the battlefield is gonna die... ;>

**Comment by hwoarangmy** [comment]
ok. That will solve my battlefield rendering issue :)

**Comment by akien-mga** [comment]
Isn't "health < 10%" a bit low for a threshold? I'm not sure how we will balance the game in the end, but I fear that many of the weaker creatures won't be able to reach such a state (e.g. if the creature has 20 HP, it will flee only if it has less than 2 HP, but I guess many creatures could one-shot it when it has 5 or 6 HP).

**Comment by Bertram25** [comment]
> Isn't "health < 10%" a bit low for a threshold? I'm not sure how we will balance the game in the end, but I fear that many of the weaker creatures won't be able to reach such a state (e.g. if the creature has 20 HP, it will flee only if it has less than 2 HP, but I guess many creatures could one-shot it when it has 5 or 6 HP).

Valid point. I've seen this in other RPGs: 
"The enemy has a chance to flee when he loses more than half its current HP in one blow."
Does it sound relevant for you guys?

**Comment by akien-mga** [comment]
> "The enemy has a chance to flee when he loses more than half its current HP in one blow."
> Does it sound relevant for you guys?

I like it. That can make for good strategies: you let a weak creature fight an enemy, and then you drop your dragon next to it to deal the final blow :-D

**Comment by hwoarangmy** [comment]
> The enemy has a chance to flee when he loses more than half its current HP in one blow.

Why not ? But beware of going into too complicated stuff at first. I think we should let it simple as a beginning and we will see what has to be improved (and how) later.

Concerning the ranged unit, I've been thinking that we could have this logic :
1 - If it is at the range distance, it should shoot
2 - If too near or too far, move (more or less at its range distance)
3 - During attack cooldown, like every other unit, it cannot move. That would allow not too slow units to retaliate even if a little bit slower than the ranged unit.
4 - Go to 1

**Comment by Bertram25** [comment]
> Why not ? But beware of going into too complicated stuff at first. I think we should let it simple as a beginning and we will see what has to be improved (and how) later.

I must say I've no opinion on this. I'll need to see this live to be sure anyway. But you're right, let's go baby steps in this sensible area.

> Concerning the ranged unit, I've been thinking that we could have this logic :
> 1 - If it is at the range distance, it should shoot
> 2 - If too near or too far, move (more or less at its range distance)
> 3 - During attack cooldown, like every other unit, it cannot move. That would allow not too slow units to retaliate even if a little bit slower than the ranged unit.
> 4 - Go to 1

IMHO, this logic is fine and can be applied to any creatures. Melee creatures are creatures with range of 1, after all.

**Comment by hwoarangmy** [comment]
> IMHO, this logic is fine and can be applied to any creatures. Melee creatures are creatures with range of 1, after all.

I agree

**Comment by Danimal696** [comment]
Yes, ranged should take their time to reload without moving, if after reloading they see the enemy is near they can flee or attack again. 
Woulndt it be better to have a "fill up" system instead of a "cool down" one? a creature only start filling up its skills when it enters battle, when it gets out of battle it starts dropping or goes to zero.

**Comment by Bertram25** [comment]
> Woulndt it be better to have a "fill up" system instead of a "cool down" one? a creature only start filling up its skills when it enters battle, when it gets out of battle it starts dropping or goes to zero.

As said on forums, we could even have both. (warm ups and cool downs)

**Comment by hwoarangmy** [comment]
To summarize (if everybody agrees, I will update the first post) :
In order to fix this, the creature thinking logic before entering battle should follow those rules:
- The fighter creatures should check their "health" + "mood" before going or keep going to combat or fleeing.
- During the fight or before, if HP < 10%, flee to bed.
- Before fighting, check HP + mood (hunger + awakness). If too low, the creature has up to 20% chances of fleeing (never more than 20% or the AI will never fight). Moreover, a creature that chooses to fight will not check its mood until it dies or its ennemy dies (or is not visible if he flees)
- Note that mood is decreased by hunger, drowsiness, and later, other creatures, lack of pay wage, and other things. For now, hunger + drowsiness can be checked < 10% instead.

Fighting logic should be :
1 - If it is at the range distance, it should shoot (if melee unit, in a neighboor tile)
2 - If too near or too far, move (at its range distance)
3 - During attack cooldown, like every other unit, it cannot move. That would allow not too slow units to retaliate even if a little bit slower than the ranged unit.
4 - Go to 1

The creatures should try to attack the closest ennemy to them.

We can remove Battlefields from code.

**Comment by Bertram25** [comment]
IMHO, this is looking good.

**Comment by hwoarangmy** [comment]
I've been thinking about fight and, after all, do we really want workers to fight at all ? It doesn't seem really logic to me having a kobold destroying rooms. And, even fighting other kobolds doesn't seem to me a good idea.
In fact, I would rather let them work even when there is a fight nearby and flee when damaged or attacked by another unit.
What do you think ?

**Comment by Bertram25** [comment]
I think sincerely the following is agreed:
- Workers don't attack enemy rooms or traps.
- They don't attack fighters.
- They keep on claiming/digging until first blow and then they flee a few tiles away.

The following point wasn't completely clear so here is what I'm proposing:
- When attacked by another worker, they fight unless they are going to die (<30% HP since those are cowards) and then flee. This could create some nice workers struggles when they meet while digging/claiming and is what I would expect.

Would this be ok for you?

**Comment by hwoarangmy** [comment]
ok. But that means I will have to handle fight for workers :(
Nothing undoable :)

**Comment by Bertram25** [comment]
> ok. But that means I will have to handle fight for workers :(

I completely understand your will for simplicity. It does happen sometimes when you're in the middle of a thing and just want it to be complete. But here, it's much more what players will expect, IMHO.
This can be (re)done in several steps, though, if it's better for you. :)

**Comment by Danimal696** [comment]
that points sounds good, kobolds are too much of a shock troopers atm :P, let them behave like the chickens they should be.
