### ISSUE TITLE
Workers handling of far away tiles to claim or dig

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#180]
Workers should search for far away ground tile, walls to claim, gold or dirt to dig once their near-by counterparts are done.

For now, they only rely on their sight in tiles, which is a fine average of 15 tiles.

Later, we could for instance make them search for far away tiles to dig or claim when they are idle for a few turn.

**Comment by akien-mga** [comment]
An example of this issue can be seen in Scream in the dark. If you don't issue order to the workers while they are around the base, they follow the underground path to the east until they are stuck, next to the red seat (screenshot 1).
![od-lostworkers](https://cloud.githubusercontent.com/assets/4701338/5125139/f5ea9f40-70c0-11e4-8492-51a843a29c70.jpg)

If I order them to dig around my base (as shown on screenshot 2), they don't notice it at all and keep running in the water.
![od-lostworkers1](https://cloud.githubusercontent.com/assets/4701338/5125147/082ec56e-70c1-11e4-8ccd-2d2e63f7bc63.jpg)

If I pick one of them and drop it next to the tile that should be claimed, it will of course change its priority and do what it's ask to, so the issue can be worked around.

I also noticed another (related?) glitch: I dropped a worker near to the tile to be digged (but not right next to it, two or three tiles away in the same corridor, as shown in green on screenshot 3). Instead of going towards it, it went all the way to the location shown in red on screenshot 3, and then it went back to the wall tile that it was asked to dig.
![od-lostworkers2](https://cloud.githubusercontent.com/assets/4701338/5125199/6e5ff65a-70c1-11e4-92ee-f661adea960b.jpg)

**Comment by akien-mga** [comment]
I think this was fixed during the 0.5.0 development, no?
_Edit:_ At least it evolved since there was work on the creatures sight and behaviour.

**Comment by Bertram25** [comment]
I think this case is almost non-existent now. As pathfinding has evolved a great deal, and creatures now wander in a saner way when not "seeing" far away things, making them reach a position where they can see things more likely.

A good test would be to start Scream in the Dark and watch the green ally bottom-right. Previously, it was stuck there not evolving much because the workers would reach the higher gold tiles up to the north opponents.

**Comment by Bertram25** [comment]
Assigning to me so I'll do the aforementioned test.

**Comment by hwoarangmy** [comment]
BTW, I've not seen a problem with this bug for ages and I frequently try to let the AI play alone. IMHO, it can be closed
