### ISSUE TITLE
Music handling enhancement

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#23]
At the moment, music handling is very basic.
- [x] Change music tracks handling from integer index to a string based array.
- [x] Add fade in/fade out and cross-fading support.
- [x] Adds support to make the music played configurable in the level a map data.
- [x] Adds support for combat and peaceful music using a cross-fade.

**Comment by Bertram25** [comment]
Heya @Danimal696 :)
For now, I think I can deal with the first three points in the list.
Could you give me a good open sourced combat music link to I can have a go at the fourth one?

Regards,

**Comment by Danimal696** [comment]
hi Bertram, i think this one is good, there is a few others in my sounds topic:
http://opengameart.org/content/the-dark-amulet-dark-mage-theme

Should be enough for testing purposes?

**Comment by Bertram25** [comment]
Yep. thanks!

**Comment by Bertram25** [comment]
The first 3 points are handled with PR https://github.com/OpenDungeons/OpenDungeons/pull/125

I'll add the cross-fade with the battle music once all that is reviewed and merged.

**Comment by Bertram25** [comment]
I'll be on the battle music cross-fade now. :)

Cross-fading support is done, so what's left is to implement the conditions to trigger the battle music and back to the calm music when playing.
I'm proposing to change the music to the battle one when one creature/room/trap of your team is taking a blow.
And trigger back the calm one if 5 seconds passed without any damage to your party occurring.

@Danimal696 @hwoarangmy @akien-mga What do you think, guys?

**Comment by akien-mga** [comment]
That sounds like a sensible way to trigger the battle music.

**Comment by hwoarangmy** [comment]
Seems a good way to handle that but at the current fighting behaviour, 5 seconds may be too short as it is quite usual for creatures to stand looking at each other like retardeds during more than 5 seconds before starting to fight :)

**Comment by akien-mga** [comment]
> Seems a good way to handle that but at the current fighting behaviour, 5 seconds may be too short as it is quite usual for creatures to stand looking at each other like retardeds during more than 5 seconds before starting to fight :)

True enough, but I think we should try to fix the creature fighting behaviour instead :-)

**Comment by Bertram25** [comment]
> it is quite usual for creatures to stand looking at each other like retardeds during more than 5 seconds before starting to fight :)

XD I'll try different values and find one more or less fitting. Once the creatures are less... stupid, we might want lower the counter. if we ever want this to happen, eh eh.

**Comment by Danimal696** [comment]
nice :)

**Comment by hwoarangmy** [comment]
> I think we should try to fix the creature fighting behaviour instead

Yes, that's an evidence. But it might not be that easy :) I've not really looked at the fighting code until now but from what I've seen, they use surrounding creatures to decide if they fight or not. But those creatures do not always go into the fight. And I've already seen that they have huge sight. So, if they consider every creature they can see before going into a fight, it might be hard. Not mentionning the fact that we have to decide how the fight should go. For example, in DK1, ranged warriors used to attack, run, attack, run... Like that, maxed Vampires were almost immortal. They could even beat in 1v1 maxed Horny.
If we keep this behaviour in OD, slow creatures like a maxed Troll could loose to a level 1 ranged fast weakling...
To be honest, I think that fixing creature behaviour will recquire to fix much more things.

**Comment by Danimal696** [comment]
That sounds too complex, i would make it so a creature always do a simple check when seeing an enemy:
can i reach it? -> am i injured? -> do i have low morale? -> if it can reach, is somewhat healthy (more than 40% hp) and not unhappy it charges the enemy; else it runs away. No need to check for anything else.

> ranged warriors used to attack, run, attack, run...

Well, that makes combat more realist, the hit and run tactics is a pretty valid one. It should make the player to keep a balanced army with tankers, flankers and ranged. And new planned values like armor would mean a troll cant be taken down by any low level ranged, even if he never manages to get face to face and kill the ranged because of speed, all damage would be absorved.

By now we should let battle behaviours out, and just center on making them able to smack each other properly, on the long we can add them.

**Comment by hwoarangmy** [comment]
> That sounds too complex

That's the actual (non working) behaviour :)
If everybody agrees, we can simplify like you say. I would just add enemy power so that kobolds don't attack enemies that would one shot them.

> Well, that makes combat more realist, the hit and run tactics is a pretty valid one

I would say that in reality, a ranged unit has to aim and shoot, which can take enough time to get reached by melee units, especially after some shots, That's why archers are good support units but not main fighters :)
