### ISSUE TITLE
Traps that throws missiles should deal damage when they hit, not when they fire

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#233]
That's true for missiles in general as we can imagine some creatures will be able to throw missiles. But for now, only traps use them.

**Comment by Danimal696** [comment]
wouldnt a physics engine be needed here?

**Comment by Bertram25** [comment]
@Danimal696 The visuals aren't actually linked to when damages are dealt, so IMHO, not for this issue.

Overall, we might later want to make cannon ball follow an arc trajectory, but it's low priority since we're not even sure one could notice that detail during the game. (The cannon balls should be rather quick, right?)

**Comment by hwoarangmy** [comment]
> wouldnt a physics engine be needed here?

Depends on what we want to do. IMHO, to stay simple, I would say a missile should hit creatures on the same tile as it is...

**Comment by Bertram25** [comment]
Maybe @Danimal696 is also speaking about creatures' corpse pushed hard from the hit? ;) This one would add something, mwahaha

**Comment by hwoarangmy** [comment]
Well, on server side, we cannot even rely on Ogre to check for collisions. But if you want to do that, please feel free to do so ;-)

**Comment by Bertram25** [comment]
> Well, on server side, we cannot even rely on Ogre to check for collisions. But if you want to do that, please feel free to do so ;-)

Sincerely, it's just extrapolation. I think we have more urgent yet. :) But I'll keep my mind open.

**Comment by hwoarangmy** [comment]
I've been thinking that currently, the cannon attacks every ennemy object including rooms or other traps. Do we want to focus on creatures only ? Otherwise, it would be easy to trigger a trap by creating a room where we suspect there is one...
@Bertram25 @Danimal696 @akien-mga @oyvindln what do you think ?

**Comment by Bertram25** [comment]
I think traps should indeed trigger creatures only or we could have ways to pawn other players on both side (attacker/victim).
I wonder what the others are thinking though.

**Comment by Danimal696** [comment]
only creatures as well

**Comment by akien-mga** [comment]
IMO it shouldn't be an issue that traps attack buildings if we balance the costs properly. Placing a building should be costly, thus making it a bad strategy just to detect a trap. BTW to place a building you would first have to claim the tiles without getting your kobolds killed.

But it's fine for me if we make it so that only creatures trigger the traps.

**Comment by hwoarangmy** [comment]
> Placing a building should be costly, thus making it a bad strategy just to detect a trap

Yes but if we take the example of the boulder, it would be easy to dig until someone's dungeon temple, place a boulder trap and it will go at the dungeon temple killing every tile on its way once triggered ^^

**Comment by Bertram25** [comment]
What will be your vote @oyvindln ?

**Comment by oyvindln** [comment]
I'm leaning towards not allowing building attacks, though I think this has to be playtested to find what works best.
