### ISSUE TITLE
Colored tile models aren't reset between two games...

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#235]
While playing scream in the dark with latest development, I encountered kobolds claiming tiles with the wrong colors:
Only the top-left (light blue) and bottom-right (blue) team were doing this.
The light blue team was claiming dark blue tiles, and the dark blue one was claiming with red ones:
100% reproducible.
![odscreenshot_1413226909](https://cloud.githubusercontent.com/assets/765917/4618719/e2147f58-530c-11e4-9954-a8433fbf6612.png)
![odscreenshot_1413226916](https://cloud.githubusercontent.com/assets/765917/4618727/f212e0e8-530c-11e4-8b11-18e0801220d4.png)

**Comment by Bertram25** [comment]
Maybe this has to do with alliances? I'm not sure though.

**Comment by Bertram25** [comment]
I'll start again: It seems the claimed walls have all been changed at game start.
Then, the kobold are claiming what they can claim. So the bug might just be in the level data.

**Comment by Bertram25** [comment]
Ok, I've got the full way to reproduce:
- Start the game, and start the skirmish level small test map.
- Quit the level without quitting the game and start the Scream in the dark level.
- The bug happens.

**Comment by hwoarangmy** [comment]
I will have a look asap

**Comment by hwoarangmy** [comment]
I've had a look. In fact, the problem comes from the tile colors being cached :
https://github.com/OpenDungeons/OpenDungeons/blob/development/source/RenderManager.cpp#L1282

If the color is found, it is keeped. The color name is constructed with the seat id. Something like MaterialNameColor_1_Claimed.

Colors are defined in the level file. Which means that you can have player seat id = 1 color green on a map (smallmap 2v2) and player seat id = 1 color red on another (scream in the dark). Because it is cached, the first color will always been used. BTW, it has nothing to do about the difference between claimed walls/claimed ground. I've not tried but if you let a kobold claim 1 wall in 2v2 smallmap and you launch scream in the dark, the player bottom left (supposed to be red) will be green for both ground and wall claimed tiles.

Note that with this bug, we can achieve to have same color for 2 enemy players ^^

To fix it, we have 3 solution IMHO :
- Do not let the color be defined in the level file (seat id 1 will always be green, for examle, seat id 2 will be red, ...)
- Reset the materials that can change between 2 games from the render manager.
- Use the color instead of the seat id in the material name to make sure that we use the correct one

IMO, solutions 1 and 3 will be easier. Solution 3 would allow to play with colors as much as we want but can result in having loads of unused materials.

BTW, it's not a regression. It is probably just the first time we have 2 maps defining 2 different colors for the same seat id ^^

@Bertram25 @Danimal696 @akien-mga @oyvindln what do you prefer ?

**Comment by Bertram25** [comment]
Thanks for all the investigation, @hwoarangmy :)

I'm for setting a list of nice looking colors globally and then use the color instead of the seat id when coloring the material. But I wonder whether we can easily free memory here.
@oyvindln What do you think about it?

**Comment by oyvindln** [comment]
I don't mind either way.

**Comment by hwoarangmy** [comment]
> I'm for setting a list of nice looking colors globally and then use the color instead of the seat id when coloring the material. But I wonder whether we can easily free memory here.

Good idea. In the RTS I use to play, 8 player is usually the max number in one game. We should decide if 8 is enough/not too much and set corresponding colors ^^

**Comment by Bertram25** [comment]
> Good idea. In the RTS I use to play, 8 player is usually the max number in one game. We should decide if 8 is enough/not too much and set corresponding colors ^^

This is completely true :) And I agree.

**Comment by Bertram25** [comment]
Ok, I guess those will go into the global.cfg file.
