### ISSUE TITLE
OD_VERSION not defined with MSVS

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#275]
Seen while testing #274 
This results in all levels being unreadable.

**Comment by Bertram25** [comment]
True. I had to define it in the preprocessor options each time. I haven't looked at a way to define it properly in cmake yet.

**Comment by Bertram25** [comment]
As far as I've seen, something like this: 
Line 453:
-set( PLATFORM_C_FLAGS "/W3 /MD /Od /D \"WIN32\" /D \"_WINDOWS\" /Gm /Gy /fp:fast /ZI /EHsc" )
+set( PLATFORM_C_FLAGS "/W3 /MD /Od /D \"WIN32\" /D \"_WINDOWS\" /D \"OD_VERSION=\"0.4.9\"\" /Gm /Gy /fp:fast /ZI /EHsc" )
As a first try.

If this is working, the OD_VERSION CMake variable will be have to be adapted so that it only keeps the actual OD version value "0.4.9" and then append the -D or /D according to the compiler. I'll have a go at it if nobody else has the time to do it before me.

**Comment by akien-mga** [comment]
What about the OD_DATA_PATH and other variables that we pass to the compiler with -D?
Or for example:

```
if(CMAKE_BUILD_TYPE STREQUAL "Debug")
    add_definitions("-DOD_DEBUG")
endif()
```

I don't know if CMake has a better build-in way of handling this argument difference between MSVC and other compilers?

**Comment by Bertram25** [comment]
Yep, those will have to be handled, too.
As for OD_PATH_DATA, it is still working even if undefined thanks to fallback values.

**Comment by Bertram25** [comment]
The next time I'm on windows, I'll deal with this, but this might be not before a few days. ;)
