### ISSUE TITLE
Certain creatures can't attack/be attacked?

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#290]
From here: http://forum.freegamedev.net/viewtopic.php?p=60650#p60650

Might be fixed with newest Danimal's balance upgrade. so issue #288 is a prerequisite of this one.

**Comment by Bertram25** [comment]
I confirm that certain creatures have weird behaviour sometimes.
E.g: On the 2vs2 small test map in single player, the Adventurer and the knight start by fleeing something and go top-right of the starting area bumping against the wall.
Certain tentacles and knights are also not moving at all, even in the presence of other creatures.
All this was with Danimal's new balance applied.

**Comment by hwoarangmy** [comment]
Beware, I've just realized that in the new balance, you have increased creatures HP. I've not looked particularly at knight/adventurer but remember that current HP is in the level file (it was set to there max hp at this time). So, if you have increased the level 1 HP, at spawning, they might have HP < maxHP/3 and, thus, flee... BTW, We should allow in the level file to set HP to "max" so that we don't have to fix every level each time we balance the game.

Concerning non moving creatures, the only thing I've seen so far is a kobold getting attacked and not moving (where it shall flee). But I've not looked why yet.

**Comment by akien-mga** [comment]
I can confirm this issue in @Bertram25's #291.

**Comment by Bertram25** [comment]
> BTW, We should allow in the level file to set HP to "max" so that we don't have to fix every level each time we balance the game.

I'm ok to make the currentHP parameter either provide a value, or be "max". Yeah, it's a good idea. :)

**Comment by Bertram25** [comment]
> Concerning non moving creatures, the only thing I've seen so far is a kobold getting attacked and not moving (where it shall flee). But I've not looked why yet.

i've noted that this was more often happening when several enemies were hitting a worker. Maybe this makes the worker handle its flee behaviour in a wrong way? I'm not sure yet, though.

**Comment by Bertram25** [comment]
Ah, about the flee behaviour, and before adding the "max" currentHP parameter handling, I think we should investigate why the knight and adventurer bump into a wall when fleeing. So we can fix that before hiding that behaviour.

**Comment by hwoarangmy** [comment]
> i've noted that this was more often happening when several enemies were hitting a worker. Maybe this makes the worker handle its flee behaviour in a wrong way? I'm not sure yet, though.

Now that you talk about it, I guess it's the same. As far as I remember, every stuck kobold I've seen was being attacked by several creatures. Nice catch ^^

> we should investigate why the knight and adventurer bump into a wall when fleeing

I've never seen that but yes, we should. What do you mean by "they bump into a wall" ?

**Comment by akien-mga** [comment]
> > we should investigate why the knight and adventurer bump into a wall when fleeing
> 
> I've never seen that but yes, we should. What do you mean by "they bump into a wall" ?

You'll see that when you try the new balance in @Bertram25's PR.

**Comment by hwoarangmy** [comment]
ok. I will see that tonight then ^^

**Comment by hwoarangmy** [comment]
> You'll see that when you try the new balance in @Bertram25's PR.

OK, I see ^^

**Comment by hwoarangmy** [comment]
I've had a look at the bump into wall bug. I think it comes from using mTilesWithinSightRadius instead of mVisibleTiles while choosing a tile to wander.
mVisibleTiles was filled with the closer tiles at the beginning. mTilesWithinSightRadius  seems to be filled with the bottom left tile until the top right tile. When using mVisibleTiles, it made sense to use the last tiles from the vector to choose a tile to wander to. But with mTilesWithinSightRadius, once the BigKnight is on the top right position, the first accessible tile he will find in the list beginning from the last is... The tile he is in. That explains why he doesn't move.
That also explains why he always goes to the top right tile directly (and not randomly).

**Comment by Bertram25** [comment]
Eh eh. Thanks for the bug hunting.
As a fix, I would personally prefer to keep the circularRegion tiles and add a sanity check, so that the wander stay wider. What do you think?

**Comment by hwoarangmy** [comment]
I'm ok with that. BTW, I've noticed yesterday while testing that creatures were much more idle than they used to be. After thinking about it, I wonder if we don't have the same thing with standard wandering. If I remember correctly, a tile was choosen at the end of the visible tiles and set as a destination. It is even worst than flee wandering because in that can, it was assumed than the tile was accessible.
If it has been replaced with mTilesWithinSightRadius, which is almost sure, we might have creatures not moving if too close to a wall (or if the tiles on their top right are not accessible). That would explain the not moving creatures eugeneloza was talking about...

**Comment by Bertram25** [comment]
> If it has been replaced with mTilesWithinSightRadius, which is almost sure, we might have creatures not moving if too close to a wall (or if the tiles on their top right are not accessible). That would explain the not moving creatures eugeneloza was talking about...

Yes! That explains what I saw in Danimal's map. I'll handle it if you want.

**Comment by hwoarangmy** [comment]
> I'll handle it if you want.

No problem if you want to deal with that ^^

**Comment by Bertram25** [comment]
Ok. :)

**Comment by hwoarangmy** [comment]
Concerning the non moving knight, I've had a look and it seems there is a bug with the floodfill. I keep digging and will tell here if I find something

**Comment by hwoarangmy** [comment]
The floodfill bug should be fixed with #303 .
It may also explain why creatures have hard time to attack (but I'm not sure). We should close this issue after making sure creatures attack in a normal way.

**Comment by Bertram25** [comment]
I confirm this is fixed. I'll try cream in the dark to see how th AI does now...

**Comment by akien-mga** [comment]
> I'll try cream in the dark to see how th AI does now...

Take care about this stuff, you'll get fat if you eat too much cream in the dark.

**Comment by Bertram25** [comment]
lol

**Comment by Bertram25** [comment]
IMHO, can be closed. A new smaller issue should be reopened if anything new happens.
