### ISSUE TITLE
Boulder trap behaviour is hard to predict

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#294]
I've been playing around with boulder traps and I find it difficult to use them in their current implementation: they fire only in one direction, but the player doesn't know which direction it is, at least I couldn't find a way to define it when placing the trap.

Then, even when knowing in which direction the trap fires, I'm unsure about what triggers it. It seems it requires a unit to stay on the tile just next to it in the corresponding direction to get triggered. That doesn't happen often, so many creatures cross and walks all around it without triggering the trap, thus making it also pretty easy to deactivate.

Since we evidently don't have the required tools to handle the fact that the boulder trap is monodirectional, maybe we could make it pluridirectional for now, and with a relatively small range (e.g. a radius of two tiles?).

**Comment by hwoarangmy** [comment]
no, boulder trap is already multidirectional. It triggers when an enemy creature stands on one of its 4 neighboor tiles.
But because it is a powerfull trap (capable of killing several creatures in a row), it is pretty slow to re-activate (hardcoded : 100 turns = ~71 seconds). So, after it triggers, there is plenty of time to claim it.

Please also remember that when the trap is created its countdown is 0 so it will not trigger before activation time.

**Comment by Bertram25** [comment]
> no, boulder trap is already multidirectional. It triggers when an enemy creature stands on one of its 4 neighboor tiles.

@akien-mga 
I confirm this behaviour, especially as I tested the new rolling model yesterday.
The 100 turns cooldown might be too much indeed and could be halved, IMHO, but that's the sole change I would do so far.

**Comment by hwoarangmy** [comment]
> The 100 turns cooldown might be too much indeed and could be halved, IMHO, but that's the sole change I would do so far.

When I will have done the trap configuration file, it will be possible to change that there. But I'm not in this right now ^^

**Comment by akien-mga** [comment]
Ok that makes sense. I guess we would need two things then, one that can be done for 0.4.9, and one that would probably be for Later:
- Reduce the hardcoded cooldown (shouldn't it be in the config file too btw?) if there's a consensus about it. I also wonder about the trap activation range: shouldn't it activate also when creatures are somewhat further than the tile just next to it? What about increasing it to a radius of 2? (i.e. to tiles away from the trap in the four directions).
- There should also be some visual feedback so that the user knows about the cooldown. Ideally an animation where the boulder trap gets set by goblins or something, but a small increasing percentage or change in opacity could do the trick.

**Comment by hwoarangmy** [comment]
> shouldn't it be in the config file too btw

It is planned ;)

> What about increasing it to a radius of 2

This has already been discussed and we choose a radius of 1 because the boulder has to be slow and if it triggers too far, as a keeper, you might be able to pickup a unit that would trigger it before it is hit. IMHO, it is not a good thing.

> There should also be some visual feedback so that the user knows about the cooldown

At last, traps will have to be crafted in the forge. In DK, when the boulder trap triggered, you had to build a new one in the forge before it can trigger again. Visually, the trap opacity was low when the trap was unarmed and normal when it was. I think it is a good way to handle things. But because for now forge is not functional, we only set a cooldown (that has to be long to avoid unbeatable traps - even if it may be too long atm).

**Comment by Danimal696** [comment]
shall we copy the original once more? since the trap is not forge-built and mounted by kobold, its fine it has a cooldown (otherwise it could be instant); it can have a 1 trigger radius but it should be invisible until triggered, and triggering once destroys the trap (or at least removes the still ball over the trapped tile)

**Comment by Danimal696** [comment]
hwoarangmy, you beat me to the answer :)

**Comment by Bertram25** [comment]
Here is a useful link to handle opacity in code:
http://www.ogre3d.org/forums/viewtopic.php?p=436777#p436777

I'll have a look sooner or later at this.

**Comment by Bertram25** [comment]
To sum up, I'd propose this fix:
- At least, hide the trap boulder model once triggered and until it's loaded again.
- If and only if the opacity stuff is working, we could show the boulder translucent until it's fully loaded again. (But only for the trap owner's screen, see the next bullet)
- Enemy traps that are hidden (not triggered) shouldn't be displayed on your terrain. (Wait ! This is the beginning of FOW :D) - I'd add this in another issue: #295 
- The traps temporary cooldowns should be added in the future config/traps.cfg (IMHO part of #239) even if it's about rooms.

Would you guys be ok with this?

**Comment by hwoarangmy** [comment]
> Enemy traps that are hidden (not triggered) shouldn't be displayed on your terrain

We should do that in a generic way since most traps (but not all) will be hidden IMHO (we could think about some canon kind that would be visible so enemy knows he should take many creatures before messing with it ^^)

> If and only if the opacity stuff is working, we could show the boulder translucent until it's fully loaded again

If it's not too complex to do, it would be a good thing.

> The traps temporary cooldowns should be added in the future config/traps.cfg

I've added that this morning in #239 . Seems like we had the same idea ;)

**Comment by Bertram25** [comment]
> We should do that in a generic way since most traps (but not all) will be hidden IMHO (we could think about some canon kind that would be visible so enemy knows he should take many creatures before messing with it ^^)

IMHO, definitely not for 0.4.9 since it will require thinking about the whole FOW logic for rooms/traps and creatures, IMHO and it might be more sympathetic than it seems. ;)

**Comment by akien-mga** [comment]
I'm fine with @Bertram25's proposal, it sounds great.

**Comment by Bertram25** [comment]
I'll deal with hiding the trap object, or make it translucent if it's working.
