### ISSUE TITLE
Fog of War

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#295]
This one is a big issue concerning FOW, or more about what a player shall not see until it reaches it. ;)

I won't speak of the visuals here, since we'd need first to add support for fog at all, and later maybe particles making a nice transition between what we see and what we don't.

The issue will thus try to sum up the list of conditions needed to know when to display or hide a tile/creature/room/trap/game entity to a given player.

Also, this shouldn't be dealt with before 0.5.0 IMHO as it's a ground-breaking change.

**Starting proposal:**

**\- Tiles:**
Tiles not seen by creatures of a given player, using the gameMap->visibleTiles() function should be hidden. Once they have been seen, they can stay visible for the given player.

**\- Rooms / Traps:**
Player rooms should be visible from the start, of course. Enemy rooms should be visible only if:
- They are seen by a player's creature for the given turn.
- They are under 4 tiles next to a player's claim tile.
  (This under-4-tiles-I-can-see-you rule shouldn't be done for simple tiles IMHO, as it will require too much computation.)
- Hidden otherwise.
- Hidden enemy traps should be displayed only once triggered.
- Visible traps will act as rooms.

**\- Creatures:**
Enemy creatures should be displayed only if:
- On a claimed tile or up to 4 tiles next to one.
- Seen by a player's creature.
- Hidden otherwise.

Feel free to comment and complete. :)

**Comment by hwoarangmy** [comment]
> Once they have been seen, they can stay visible for the given player.

IMHO, we should aim for the FOW usual strategy games use:
if you loose sight on a tile, it stays in its state until you see it again. If someone digs it, you don't see it until you gain sight again.

Same for rooms. If you see a room, it should be displayed until you get sight again. If it is destroyed while you don't see it, you should not know until you see it again (of course, I'm talking about a room you don't own, otherwise, you would have vision).
Not owned creatures should disappear as soon as they enter the FOW.

**Comment by Bertram25** [comment]
> IMHO, we should aim for the FOW usual strategy games use:
> if you loose sight on a tile, it stays in its state until you see it again. If someone digs it, you don't see it until you gain sight again.
> Same for rooms. If you see a room, it should be displayed until you get sight again. If it is destroyed while you don't see it, you should not know until you see it again (of course, I'm talking about a room you don't own, otherwise, you would have vision).

It's indeed better, maybe a little more complicated to handle. Separating the client game map, from the server one may be of help with this after all. ;)

**Comment by hwoarangmy** [comment]
IMHO, we have 2 choices:
- Send only the needed (what a player sees) to a player. That would mean to relate every events to tile (to know if we should display what's going on on a tile and to which player). That would be the best solution but would change many things on server side and would also add burden to the server
- Let the gamemap know everything like it actually does on client side but do not display it until the player actually sees it. It is just a guess but I believe that's how many games handle multiplayer (and thus, how some players can cheat disabling FOW by installing some hack). That would be easy on server side but complicated on client's because we will have to remember and differentiate last seen state from actual state. Which would more or less mean a 3rd gamemap. Or maybe Ogre can help us with that by not refreshing unseen tiles. This will have to be looked closely before deciding ^^

**Comment by hwoarangmy** [comment]
BTW, concerning map loading, do we want to see the tiles like they are in the file ? (I mean even for unseen ones)
Same for rooms (that would mean that we see every room created at map load time) ?

That might change the way map is loaded...

**Comment by Bertram25** [comment]
IMO, no I don't think so. To me, the server has it all, but the clients will only show what your evil influence can detect. I mean you see tiles and rooms only once your creatures have detected it.
On the other hand, to do like in DK, I'd like to let the ability to hear enemy sounds even from unseen location. I found it cool to be able to murch in the dark to try and detect enemies. But this is open for discussion.

**Comment by hwoarangmy** [comment]
> IMO, no I don't think so. To me, the server has it all, but the clients will only show what your evil influence can detect.

I also think it is good for rooms/traps and creatures. That means that they should not be loaded during map loading on client side...

But concerning tiles, I'm not so sure. Do we want to see 100 fullness dirt tiles everywhere until we see it ? What about water/lava/gold/rock ?

> On the other hand, to do like in DK, I'd like to let the ability to hear enemy sounds even from unseen location.

Yep, I remember that and I agree. BTW, that will also mean that sounds will have to be handled in the creature definition rather than by the creature (since the given creatures would not be on the client gamemap)

**Comment by Bertram25** [comment]
> But concerning tiles, I'm not so sure. Do we want to see 100 fullness dirt tiles everywhere until we see it ? What about water/lava/gold/rock ?

My own evil thought about it was involving an distance fog, making it useless to display tiles but unfortunately for now, the ambient fog doesn't seem to work with my latest tests.
Ambient fog or not, I was wondering whether displaying the neighbor tile from the detected ones, as dirt tiles would be a good idea. What do you think?

> Yep, I remember that and I agree. BTW, that will also mean that sounds will have to be handled in the creature definition rather than by the creature (since the given creatures would not be on the client gamemap)

Hmm, are you sure? If the server does send the server sound playing requests, then we're out of trouble, right?

**Comment by akien-mga** [comment]
> BTW, concerning map loading, do we want to see the tiles like they are in the file ? (I mean even for unseen ones)
> Same for rooms (that would mean that we see every room created at map load time) ?

I wonder about this. Since we have static maps, not displaying the initial map state would provide an advantage to players who already know the map against newcomers. So it might make sense to show the tiles in their initial state with a light as done e.g. in Warcraft 3, so that the player can decide where to dig to reach gold, etc.
Of course the display would not be refreshed until the tiles are effectively discovered by the player, leaving room for unexpected expansion of other players, unexpected neutral dragons to wreak havoc in your corridors, etc.

I'm not strongly for this though, just adding my point to the conversation. I'm fine with hiding everything with a thick fog of war too.

**Comment by hwoarangmy** [comment]
> Hmm, are you sure? If the server does send the server sound playing requests, then we're out of trouble, right?

Well, that was more a reminder, there is nothing tricky there. I was thinking about this:
https://github.com/OpenDungeons/OpenDungeons/blob/development/source/network/ODClient.cpp#L831

> I'm not strongly for this though, just adding my point to the conversation

Yep, that's also the reason why I'm not sure if we should hide everything. If I remember correctly, we were able to see gold tiles in DK, no ?

> My own evil thought about it was involving an distance fog, making it useless to display tiles but unfortunately for now, the ambient fog doesn't seem to work with my latest tests.

Yes, that would be a way to implement FOW on client side. But IMHO, if we could do that on server side, it would be even better.

In any case, I don't think hiding everything is the best way to go because I'm not sure it will be fun to have to go everywhere to find where gold tiles are.
We might want to hide tiles depending on their type. We could display gold/rock tiles. And maybe water/lava ?
But concerning dirt, we could display them all 100 fullness.

@Bertram25 @akien-mga @Danimal696 @oyvindln WDYT ?

**Comment by Danimal696** [comment]
i would only show gold, finding everything else was one of the joys of DK, nothing like unexpectedly digging into a lava sea with dragons :D

**Comment by hwoarangmy** [comment]
> i would only show gold, finding everything else was one of the joys of DK, nothing like unexpectedly digging into a lava sea with dragons :D

Ok. Could you confirm what my failing memory can't: in DK, only gold tiles were shown ?

**Comment by Danimal696** [comment]
Gold, gems and undiggable rock

**Comment by hwoarangmy** [comment]
Thanks for reminding. Then, shall we keep the same behaviour ? From what he said, I guess @Danimal696 thinks yes. It seems good to me too. What about the others ?

Moreover, if we stay on that, we might also consider not loading the map on client side. After all, nearly nothing will be kept (only gold tiles, rock tiles, seats and creature definitions, lights and equipment). So we can go back to what was originally done: the server sending all the information about the game map...

**Comment by Bertram25** [comment]
> Thanks for reminding. Then, shall we keep the same behaviour ? From what he said, I guess @Danimal696 thinks yes. It seems good to me too. What about the others ?

Definite yes to me. Let's only see Gold, Gems (infinite gold), and undiggable rocks.

> Moreover, if we stay on that, we might also consider not loading the map on client side. After all, nearly nothing will be kept (only gold tiles, rock tiles, seats and creature definitions, lights and equipment). So we can go back to what was originally done: the server sending all the information about the game map...

Looks sane. While I'd still send the map filename or at least the map info to the client. IMHO, sooner or later, we will want to add a map preview image in the lobby, right? (This is also partially covering @akien-mga 's notice about knowing the map fairness.)
I can open an issue if all agree about this.

Also, the client might be in need to still know the map size to handle memory correctly, and react in a sane way concerning borders.

**Comment by Danimal696** [comment]
really nice patch, i cant wait to see the fow working ;)
