### ISSUE TITLE
Trap boulder rolling objects should disappear when reaching the map borders

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#333]
As seen here:
![odscreenshot_2014-nov-19 10 55 36_0](https://cloud.githubusercontent.com/assets/765917/5134862/550db916-7112-11e4-98a2-363ac044d645.png)

**Comment by hwoarangmy** [comment]
lol

**Comment by Danimal696** [comment]
or just make sure to always have a stone map border

**Comment by Bertram25** [comment]
> or just make sure to always have a stone map border

If that option is chosen, the border should be added only in the game mode, not in the editor. Otherwise, you will add a border each time you load a level there.

**Comment by hwoarangmy** [comment]
The problem with adding map border is that not all missiles (like the boulder) disapears when they hit a wall. If we do that, they might change direction which is not the expected behaviour IMHO.
But don't worry, I will patch that so that when the missile goes outside the game map, it just gets removed.

**Comment by Bertram25** [comment]
Fine by me. :)
