### ISSUE TITLE
Ranged creatures Behaviour

### ISSUE THREAD

**Issue by Danimal696** [OpenDungeons/OpenDungeons#376]
They try to shoot from its max range, wich is fine, but if an enemy creature charges at them, they just run around trying to get to max range again, making them totally useless. 
Couldnt they run away to max range when the enemy is 2 or 3 tiles away?

**Comment by Bertram25** [comment]
That one might be unkind to players, indeed. Can we consider the current behaviour sufficiently good for the current release to go or should I add it for 0.4.9?

**Comment by Danimal696** [comment]
we only have the wizard as ranged, so it can wait ;)

**Comment by hwoarangmy** [comment]
Well, in reality, even allowing ranged units to shoot when not at max range wouldn't make them stop to run when a melee unit charges them (at most, they will strike once more). And IMHO, ranged units are support for melee. Usually, you don't send a pack of archers without melee ^^

**Comment by Bertram25** [comment]
Ah, so you mean there might be no bug at all. Let's see if I can send a mix of melee + ranged units and see how it turns.

**Comment by Bertram25** [comment]
Btw, I had a few games playing the heroes, and so far, wizards do fine when with knights.
Wizards alone should indeed be a bit awkward with melee units, but this is a bit expected, right?
So is this still an issue?

**Comment by Danimal696** [comment]
i would say yes, any sifth into the battle line send them panicking everywhere (try flanking them)

**Comment by hwoarangmy** [comment]
Note that I am planning trying to allow ranged units to launch missiles instead of attacking from far away (making buggy impression that they are fighting alone). However, that doesn't change anything to the fact that they will try to retreat when attacked by ranged units.

**Comment by Danimal696** [comment]
thats why i proposed they should have a safe zone where they will run (less than 3 tiles) and an effective attack zone (3 - 5/6 tiles), my reason being that if you drop them rigth into the war zone they will lose a lot of time repositioning or just running away if there are enemies on both sides closer than their max rattack range. And they should also be able to figth other ranged 1 on 1, rigth?

+1 to projectiles like the cannons do

**Comment by hwoarangmy** [comment]
I've been thinking about fighting behaviour and I have some propositions:
- We could remove physical/magical attack and replace by physical/magical melee attack and physical/magical range attack
- For range, we could add min range and max range. The fighter would use his attack if within range
- If a creature (fighter) has physical/magical melee attack > 0, it is a melee fighter
- If a creature (fighter) has physical/magical range attack > 0, it is a range fighter
- Note that creatures can be melee figter, range figther, both or none.
- If a creature have melee + range, it will try to attack from range if possible. But if an enemy creature comes to melee, it will switch to melee attack
- If a creature have no attack (for support units for example), it will flee if attacked from few tiles and wait
- If a melee attack is not in range, it will try to get in range before attacking (in the lowest range if a unit came closer or at highest if the enemy is too far)

@Bertram25 @akien-mga @Danimal696 @oyvindln @eugeneloza WDYT ?

**Comment by Danimal696** [comment]
how would this fit if we add skills in the future?
Imagine the mage the wizard has "fire bolt" as lv1 basic attack and learns fireball at lv10,  could it still be done?

**Comment by hwoarangmy** [comment]
I would say that skills should be used like ranged attack: check if one skill can be used depending on range, use it if possible and, if not, go for standard range/melee attack

**Comment by hwoarangmy** [comment]
I have implemented creature skills. ATM, we can use heal/explode.
I am currently trying to merge fighting behaviour into creature skill (after all fighting can be seen as a creature skill like casting a spell).
However, for improving fighting behaviour, we should decide how the creature should position itself during fight. ATM, it tries to go to the closest spot where it can hit (depending on its skills). That means that if a creature has a melee skill (range = 1) + range skill (range = 5), once it has used the range skill, it will go to melee.
That may not be the expected behaviour as I would expect range creatures to always stay at range except if engaged into melee. But that may not be true in every situation. For example, I would expect melee creatures able to cast explosion to cast the spell when they can but go to melee ASAP

@OpenDungeons/developers WDYT ?

**Comment by Danimal696** [comment]
the lazy solution would be to give only melee range skills to melee warriors and ranged skills to ranged ones, also ranged to have always the same (or close) range in all its skills.

Think on warriors having skills like: armor up, shelf-healing, attack up, speed, invisibility....
And mages/archers: firebolt, fireball, poison arrow, granade arrrow...

Great update by the way.

**Comment by hwoarangmy** [comment]
I reopen this issue because there is still a discussion going on and the fighter behaviour is still in work

**Comment by hwoarangmy** [comment]
After thinking a bit more, I've added a new property to creatures: "distance when not fighting". The basic idea is to check if a skill can be used. If a skill is available but the distance is not good, try to go to the best spot (at range max from the enemy).
If no skill is available because all in cooldown, try to stay at "distance when not fighting"

I think that with this simple logic we can achieve what we want (even hit and run if wanted) just by playing with cooldown/warmup.

Note that I've introduced cooldown and warmup for every skill. cooldown is a time not allowing to use the same skill again. warmup is a time the creature will be blocked after using the skill (basically, this can be seen as the required time to play the animation).
