### ISSUE TITLE
Various test configurations

### ISSUE THREAD

**Issue by tomluchowski** [OpenDungeons/OpenDungeons#413]
As in title , how do you imgainge having various game configuartions to be tested , shared and debugged without the console and external configuration files ... ? 
Why do you believe that having GUI in game is better than plain old files ? 
For example , you Bertram once complained about various speed and acceleration of scrolling , and this is a perfect example how auto - starting script executing the console commands could present various scrolling styles ... etc. 
Also did you noticed you would need actually two languages : one the Angelscript -- or other scripting language ; the other being the in-game functions coded into the C++ code base gatewaing certain functionality to the outer layers ( like Angelscript ) , this is half - done -- there is existing game console ; why to scrap all this ? Can't those two languages cooexist together ?

**Comment by hwoarangmy** [comment]
For now, nothing coexists since AFAIK, AS do not work at all. I don't want to talk for @Bertram25 but I think he will agree with the fact that half finished stuff (that we have to maintain when we change something in the API or in the general logic) isn't worth keeping if nobody is working on it (or willing to deal with it in the next futur). Moreover, the stuff that has been removed is not lost. If somebody feels like re-using it, he can go ahead (but all the others coders won't have to bother with this dead code).

Concerning the use of plain text files for IO, as you say, it could be usefull to test. But again, it means a lot of work for the one dealing with that and also for everybody else (for the same reasons as above). Because OD is a free time project with only a few coders, IMHO, we cannot afford wasting time on that kind of stuff. Otherwise, version 0.4.9 wouldn't be here. Moreover, @oyvindln is working on unit tests which is, IMHO, a much better approach than using the console.

Concerning the use of AS, I must say that I would be for letting all this stuff under #if 0. Why ? Because for now, it is just exposing methods that may not be usefull (but that we can't change because they are there). IMO, that's not the way to do that. First we get something working. Then, we expose the needed methods for what we want.
To illustrate what I am talking about, AS was added as a library before the major architecture change that occured with the client-server behaviour. That means that all the care that every coder took to update this code when needed has been lost. And if we change again the logic, it might happen again. Again, because OD is a free time project we should take care of not wasting too much time. And updating half finished stuff that might be dropped for some reason in the end is, IMHO, not the way to go.

**Comment by Bertram25** [comment]
Well, I do think @hwoarangmy really exposed well the reasoning behind what we do, how we do it or don't, and in what order.

I'll add some of my comments, of course ;)

> As in title , how do you imgainge having various game configuartions to be tested , shared and debugged without the console and external configuration files ... ? 

Well, @tomluchowski , first define "various game configurations". Because a game configuration is IMO either just a config entry in which case you test all the possibilities and you're done with it or add options for the different sane behaviour patterns a player would expect. This is vague so I can't tell more.

> Why do you believe that having GUI in game is better than plain old files ? 

I suggest you re-read this (rather vague) sentence. Using text files only instead of a nice looking GUI for user settings or in game experience? Are you serious?

> For example , you Bertram once complained about various speed and acceleration of scrolling , and this is a perfect example how auto - starting script executing the console commands could present various scrolling styles ... etc. 

Nope, again, I complain more about how badly it was designed, making a simple feature very complicated to follow, understand, and fix. The autoscroll itself I was against because it was making the game unplayable for me. (And remember, at that time, OD had a lot of other problems about user input...)

> Also did you noticed you would need actually two languages : one the Angelscript -- or other scripting language ; the other being the in-game functions coded into the C++ code base gatewaing certain functionality to the outer layers ( like Angelscript ) , this is half - done -- there is existing game console ; why to scrap all this ? Can't those two languages cooexist together ? 

We don't scrap it, we're simplifying it. If you look at the previous code, we were using a hardcoded command calling an AS function calling back an hardcoded C++ command triggering some debug behaviour. AS was more or less just checking the arguments number. This is debug code, so it's meant to people developing OD and thus can stay in proper C++.

Now, we would like to:
- Use a rather refined preset of console commands to trigger visual debug stuff, get info, let the players cheat a bit... C++ only.
- Use AS for what it's best: Handle scripted game events and such.

This way, we have IMO a better frontier between the bindings needed by scripters and the code used by developers. Last but not least, this was a team decision if I'm not mistaken.

@tomluchowski Also, please stay pragmatic, let's focus on what's the next need of the game, and not on some nuclear satellite handling code we might need in 12 milestones. This is a spare-time project after all.
