### ISSUE TITLE
Make sure the CMAKE_CXX_FLAGS are actually defined in CMakeLists.txt

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#42]
As reported by several users on the forum, compiling OD does not always work out of the box since most of the time the "-std=c++11" flags is not actually defined.

On the affected systems (among which Mageia 64bit), it seems that the CMAKE_COMPILER_IS_GNUCXX variable is empty, therefore the flags are not added to CMAKE_CXX_FLAGS.

I've found that moving the project declaration ( https://github.com/OpenDungeons/OpenDungeons/blob/development/CMakeLists.txt#L205-L229 ) at the top of the CMakeLists.txt (that is before the compiler flags definition) solves the issue on Mageia.

@Bertram25: IIRC you said something about this triggering issues on @tomluchowski's desktop?

On a side note, the whole CMakeLists.txt could probably use some refactoring; I'm not a cmake expert (yet), but some things look a bit fishy (e.g. listing of source files before project declaration and looking for dependencies).

**Comment by Bertram25** [comment]
> @Bertram25: IIRC you said something about this triggering issues on @tomluchowski's desktop?

@akien-mageia Yep, moving the 'project' statement to the beginning of the file broke it for @tomluchowski AFAIK. That's why we did nothing and added the CMake flags by hand.

IMHO, the whole file needs to be redone anyway and follow more conventional ways of doing it as you said. I'd start it all over based on a better model and see whether things improve afterwards.
Just my two cents, though.

**Comment by Bertram25** [comment]
As I said in #58, feel free to create a pull request that should fix that point.

**Comment by Bertram25** [comment]
And you said you were only dabbling at it? It's working great here :D :+1: 

In fact, it's working so greatly that every warnings are enabled again and I get a lot of them. (Not complaining, we should have got them back weeks ago.)
This is working for me, and I hope it will work for @hwoarangmy too.
If so, I do think we should merge and deal with warnings afterwards.

**Comment by akien-mga** [comment]
Hehe, in my pull request I just moved the whole chunk at the top of the file, it wasn't particularly complicated :-)
I've reverted my changes towards having proper make install instructions since it was a WIP, and I wanted something functional for a pull request. I've saved my work as git patches though, so I'll can use them to proceed with my work on the make install instructions (#58).

**Comment by Bertram25** [comment]
Good strategy! :)

**Comment by hwoarangmy** [comment]
Unfortunately, it doesn't :(
The thing is that to compile with MinGW, the -std=c++11 do not work. I have to use -std=gnu++11. But when I change the flags in cmake after Akien's patch, the flags are re-added after the ones I changed.
When it will work with MinGW, I will test with MSVS so that we are sure that every supported environment works :)
