### ISSUE TITLE
Custom lighting is _really_ resource heavy

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#524]
Since @oyvindln improved the overall lighting/shading/normals application and stuff, the custom light sources that we can set in the editor are really resource heavy.

Greed or Might is a good example of a map where the FPS drop dramatically due to the use of custom lights in several points on interest.

Comparing Greed or Might and Scream in the Dark on my laptop:
- Nvidia GPU (OpenGL 4.4): 40 FPS on Scream in the Dark / 30 FPS on Greed or Might
- Intel HD Graphics 4000 (OpenGL 3.0): 26 FPS on Scream in the Dark / **15** FPS on Greed or Might

**Comment by akien-mga** [comment]
A quick workaround for the time being would be to remove custom light sources from the maps that use them (at least for the final 0.5.0 release). A better fix would be to optimise those lights so that they don't kill the FPS, but that's maybe more for the Later milestone.

At any rate, we can keep the lights for now since it's useful for debugging, but I'm making a mental note to remove them from at least Greed or Might if this bug does not evolve before 0.5.0.

**Comment by Bertram25** [comment]
Ok, setting this to 0.5.0 as something will have to be done, whatever it is.

**Comment by oyvindln** [comment]
The lighting has to be calculated for every light in the scene, which starts adding up very fast when the number of lights increase. Calculating lighting per pixel + normals is obviously going to be slower than per vertex as done previously. Another problem is the fact that we have a dynamic terrain, which means we can't pre-calculate/render geometry like many games do. Though, I've found  some things that can be done to speed up rendering:
- Apply team colour and tile marking/vision using a shader rather than cloning materials
  - Currently we are doing this by setting lighting values (and in the case of team colours, using an extra pass to blend the team colour on top of the texture) , which means that we end up doing lighting calculations for this step. Writing a simple shader that adds colour to alphaed parts of a texture would avoid doing this, which should mean less overhead, though nothing huge. It also means we won't have to mess with cloning materials, which would make things a bit cleaner. 
- Use either static geometry or instancing for tiles and other non-moving objects.
  - This should reduce the number of batches sent to the graphics card, and maybe avoid some boundary calculations if I understand ogre correctly. 
    *Static geometry seems to be the simplest to use, though when I tested it crashed due to some material issue if it was used with RTShader materials. This may be related to the material bug we had though, so it may not be a problem if that is solved. A possible downside is that rebuilding the geometry when something changes could be slow enough to cause lag, I haven't managed to test it properly yet. Other than that it seems pretty simple to implement.
  - Another alternative seems to be to use instancing, though it's most efficient when using many of the same object. Since we have a bunch of different tile types and permutations, it may not be all that helpful. It also seemed complicated to set up, possibly needing custom material settings and shaders.
  - Both of these seem to work best by using the same materials for most of the geometry, so using either of these techniques would involve doing the previous step.
- Disable lighting on keeper hand, drag marker
  - Very minor optimisation, but very straight-forward to do
- "Connect" different tile types.
  - Currently gold/dirt/claimed walls don't connect, and the borders between them are the same as borders with tiles that are dug out. I think it may look better to make them connect, like tiles of the same type, and it would also mean less vertices, as there won't be "canyons" inbetween them. This won't be a huge difference in performance, but it's something we could consider. Maybe we could also treat the outside of the map as a full tile rather than using the border tiles there.
- Make a tile-based lighting system, a.la minecraft and similar.
  - Calculating lighting on a tile-basis could potentially improve performance a great deal, and would probably be a requirement if we want to use a large amount of lights. Though, it would also take a lot of work to implement. 

EDIT:
Maybe it would also be possible to use the terrain system in some way.

**Comment by hwoarangmy** [comment]
> Apply team colour and tile marking/vision using a shader rather than cloning materials

Please also remember that skull flags also use cloning material. If you find something interesting and cleaner, it may be interesting to use the same system (even if it has nothng to do with shaders).

> Disable lighting on keeper hand, drag marker

I think the light on the keeper hand is pretty nice and I use it a lot to have a look on the darkest parts of the dungeon. Removing it would mean to add more lights in the dungeon so performances could not be better.

> "Connect" different tile types.

Seems good to me

> Make a tile-based lighting system, a.la minecraft and similar.

I don't know if it can help but I've added a pre-computed system to help calculating visible tiles depending on how hidden they are from a central tile point of view. If you want to have a look, it's done in TileContainer::visibleTiles. It was really much more efficient than live computation like it was done previously (IIRC, something like 10 times faster).

**Comment by oyvindln** [comment]
> I think the light on the keeper hand is pretty nice and I use it a lot to have a look on the darkest parts of the dungeon. Removing it would mean to add more lights in the dungeon so performances could not be better.

What I meant was disabling lighting calculation form the keeper hand itself, not the light that follows it.

**Comment by hwoarangmy** [comment]
> What I meant was disabling lighting calculation form the keeper hand itself, not the light that follows it.

ok, sorry for the misunderstanding ^^

**Comment by hwoarangmy** [comment]
@oyvindln Concerning the "connect different tiles", I will release soon a PR with the tilesets. In the tileset definition, I will add how tiles should be connected (only for their type or if they should connect with other ones). That would avoid hardcoding it and will let artists do as they want ^^

**Comment by oyvindln** [comment]
[Deferred shading](http://www.ogre3d.org/tikiwiki/Deferred+Shading) seems like a good option if we want to have a lot of lights. It looks a bit complicated to implement though.

**Comment by hwoarangmy** [comment]
Seems interesting but complex, indeed...

**Comment by Bertram25** [comment]
How are performance for you guys since ee56e51299d15c65446ebc250ef9e27a8781d145?

**Comment by akien-mga** [comment]
It's way better performance-wise, the lighting is not as "shiny" as before but it does its job (i.e. a light source behaves similarly to having the mouse pointer permanently in one point with regard to the lighting effect).

So I'd say this one is closed by ee56e51.

**Comment by Bertram25** [comment]
@akien-mga I agree. I've got no more perf problems now on my side. Thanks a lot @oyvindln :)

Btw, dark_silync is working on light list generation atm: http://www.ogre3d.org/2015/03/05/ogre-progress-report-february-2015
