### ISSUE TITLE
The configure seat menu becomes unusable when restarting a game.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#575]
Start a single-player game, then quit the game but not the app and start a new game, the combo boxes in the configure seats menu are empty for certain of them:

![err1](https://cloud.githubusercontent.com/assets/765917/6793647/dfbbd3f2-d1c7-11e4-8e25-2ef64c524493.png)

I tried both with the same map or different maps, and on different dev branches.
Ex: Start The Bridge, and then Scream in the Dark...

**Comment by hwoarangmy** [comment]
I remember having already tried lately and I didn't see such bug.
But the only thing I've changed lately about the configure seat mode is saving seat id instead of the seat itself. I guess I forgot to empty the list between 2 games. I don't see how it explains what you see but could you please try in MenuModeConfigureSeats::activate to clear mSeatIds before filling it and check if it fixes the issue ?

**Comment by Bertram25** [comment]
> could you please try in MenuModeConfigureSeats::activate to clear mSeatIds before filling it and check if it fixes the issue ?

Sure. I'll do. If I'm the sole to get the issue then I'll be on fixing it.

**Comment by hwoarangmy** [comment]
After thinking about it, the configure seat mode is deleted when we launch the game or go back. Thus, I don't know what's going on for you @Bertram25. Maybe have I messed something I didn't see.

**Comment by Bertram25** [comment]
Ok, my apologies. This is coming from the fact that I am using the default hg branch of cegui as a system library. (and an old hg tip, btw)
I recompiled 0.8.3 and reinstalled it. It works fine now.
The default branch can't be considered as stable though, and I have custom changes there regarding combo boxes so it is surely not that important to note.

Sorry again. I'm closing. :)
