### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by oyvindln** [OpenDungeons/OpenDungeons#578]
Right now, only the consoleinterface class has tests. We should be aiming for having as much as possible covered by tests, but it will require some redesign. TileContainer seems to be a good place to start.

**Comment by hwoarangmy** [comment]
Well, I've already thought about that and even tried to add tests to TileContainer but there are so many dependencies that you need to include the whole project. Basically, because TileContainer uses Tile. And Tile uses GameMap. And from one to the other, we end up including everything. That's the bad point of not using abstract layers ^^

**Comment by hwoarangmy** [comment]
I've been thinking a bit more about unit tests. IMHO, our architecture is not adapted to unit tests as @oyvindln tried to implement. Almost every interesting class relies on GameMap and compiling a test means more or less to compile the whole game.
Except testing very simple things, like checking if our Random class works, I guess we cannot do much this way. And certainly not the real interesting tests we might want to do (tests on floodfill, pathfinding, creature behaviour, ...)

That being said, our client-server architecture is very test friendly to test independantly the client and the server (by stubbing one or the other - just like the replay mode does).

My proposition is:
- Merge again the files splitted by @oyvindln so that we have 1 cpp per header file (I think splitting makes easy to miss something when dupplicating code)
- Do not have 1 executable per test. But find a way to start OD in a special mode or something similar to run unit tests. That might be by using scripts (AS? LUA?) or by loading a dll (to avoid embedding unit tests within OD).

@oyvindln your opinion would be welcome if you are still around.
@OpenDungeons/developers WDYT ?

**Comment by hwoarangmy** [comment]
I've been thinking that the most straightforward way to tests would be use the normal executable, launch it on server mode and go for a client stub to make tests (using command consoles for tests needs for exemple for wrapping creatures and this kind of stuff). That would allow to test the server easily and very effectively (since we test the real executable).
However, testing the client side might be a little bit more tricky. But it may be possible by grepping some stuff in the logs to see if it behaves as expected.

@Bertram25 WDYT about merging the sources back as I've proposed ? Any other idea for testing ?

**Comment by Bertram25** [comment]
> Merge again the files splitted by @oyvindln so that we have 1 cpp per header file (I think splitting makes easy to miss something when dupplicating code)

I must say I completely agree. Duplicating cpp file vs 1 header, except for good reason, is considered a bad practice AFAIK.
But are you speaking only of duplicated cpp files or also of abstracted classes needed by unit tests? The latter is fine IMHO and makes us have a more modular model, but it's again theory.

> Do not have 1 executable per test. But find a way to start OD in a special mode or something similar to run unit tests. That might be by using scripts (AS? LUA?) or by loading a dll (to avoid embedding unit tests within OD).

Well, it depends on what you want to achieve. IMHO, there are several things that shouldn't be mixed. Let's do some overdone theory: :>
Unit tests are made to be fully automated, return true or false, and test a small quick thing in the code. E.g.: Some internal/external API, function or method, check bounds, ... 
They should stay small executables easy compiled and run. Here, we already have some potential problems of scope.
What you suggest looks more like automated integration tests and IMHO both test types should live together.

Now the theory part is done, (yeah, I know I sound so much like a bad teacher. ;P), I guess the current unit tests may have a flaw in scope if they're coming in the way of our own code. I'd still need to have a proper look there first, though.
WDYT?

**Comment by Bertram25** [comment]
Another idea I had, is what about using some fabricated replay data, and make a game run very quickly in background testing most of the known game events? It may help triggering complicated crash courses, ... WDYT (bis)?

**Comment by hwoarangmy** [comment]
> But are you speaking only of duplicated cpp files

Yes, I'm talking of splitted files (like Tile.cpp and TileFunctions.cpp). Concerning tests, I guess the easiest will be to remove the broken ones (or maybe all since they test nearly nothing)

> What you suggest looks more like automated integration tests and IMHO both test types should live together.

Yes, that's my point. Our architecture is not adapted for unit tests. Because nearly every entity embeds the gamemap, there is no way to get "a small executable". We will always have to compile nearly everything. That's why I think we should skip unit tests. @oyvindln already spent pretty much time and couldn't achieve more than testing empty shells (and I think there was not much more to do).

However, thanks to the client-server architecture, testing the server is pretty easy. Moreover, we can do that by launching a separated test executable.

> I guess the current unit tests may have a flaw in scope if they're coming in the way of our own code

Splitting classes will cause us to miss some code (it already happened to me). And, again, considering the result is nearly null (who have ever tried the unit tests ?), I think we should merge again the files. It is common for me, when I add a variable (like the max gold for the seat), to look for another one used the same way and to use it at the same place (to make sure I didn't forget a place). And more than once, I ended forgetting the SeatFunctions.cpp. If I am lucky, the feature do not work and it is pretty easy to find why. But in some case, we could have nastier side effects.

> I'd still need to have a proper look there first, though.

Ok. But please tell me if you see something against. If not, I will handle the merging part.

> Another idea I had, is what about using some fabricated replay data, and make a game run very quickly in background testing most of the known game events?

The idea is good and would allow to test the client. But the problem is that transfered data changes pretty often (I would say more than once per PR). And that would mean to update the replay data (honestly, I think it is just not possible)...
However, trying to find some way to play faster the replays may be a good idea ^^

**Comment by Bertram25** [comment]
> Ok. But please tell me if you see something against. If not, I will handle the merging part.

For the merging part, please go ahead. I don't see good reason not to.

> The idea is good and would allow to test the client. But the problem is that transfered data changes pretty often (I would say more than once per PR). And that would mean to update the replay data (honestly, I think it is just not possible)...

Indeed, just spilling the seeds around and see what grows out of it. ;)

> However, trying to find some way to play faster the replays may be a good idea ^^

Yes, that's could be a good way to earn time when reproducing a bug with a replay. :)

**Comment by hwoarangmy** [comment]
> For the merging part, please go ahead. I don't see good reason not to.

Well the reason would be that it will break the current unit tests (even if they are not very usefull).

> Indeed, just spilling the seeds around and see what grows out of it. ;)

That's a very tempting idea. Too bad it is not straightforward.

> Yes, that's could be a good way to earn time when reproducing a bug with a replay. :)

Yes. Even if there are not much needs ATM.
