### ISSUE TITLE
Traps spreading on multiple tiles

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#596]
While playing around with the editor, I noticed that traps can be spread over multiples tiles. If you create a trap (say a boulder trap, i.e. type 3) by drag the mouse over four tiles, it will not create four boulder traps but one big boulder trap with four tiles, e.g.

```
[Trap]
3   Boulder_6   0   4
20  1   0
21  1   0
22  1   0
23  1   0
[/Trap]
```

My question is, how are those traps handled in the gameplay? I remember we discussed such traps a while ago, but I'm not sure about the current implementation. To activate a four-tile trap, do you need to craft four traps and put them all in place? Will all four tiles activate at once?

Or is this simply a bug and traps should stay on one tile for now?

**Comment by akien-mga** [comment]
Actually looking at the .level file it seems the isActivated boolean is specific to each tile, so the only implication of those "multiple-tiles" traps is that there is only one name for the group.

I'll let @hwoarangmy comment on that and confirm that it's the expected behaviour or if it's an uncalled-for feature.

**Comment by hwoarangmy** [comment]
Traps are buildings for historical reasons because they shared so much code with rooms that I made a common parent class. Thus, they can have several tiles. Each one can be activated or not (as you have seen) and can have different health and claim value (if you save the game).
However, they do not absorb other traps like rooms.
That's why I confirm it is the expected behaviour

**Comment by akien-mga** [comment]
Thanks for the explanation :)
