### ISSUE TITLE
OD crashes when launching 2 instances of the game

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#648]
Due to an exception when renaming log files (log file being in use).

**Comment by Bertram25** [comment]
Not for me. Might be windows related?

**Comment by hwoarangmy** [comment]
yep, maybe

**Comment by akien-mga** [comment]
Ah I hadn't thought about this. It doesn't crash on Linux indeed, but it might mess the log files too.
Do you have an idea how this could be fixed?

Maybe by logging to a temp file (e.g. opendungeons-fulldate.log) and doing the renaming when closing OD?

**Comment by Danimal696** [comment]
Happens to me as well

**Comment by hwoarangmy** [comment]
To me, it is windows related. I've never had any problem renaming a file I was using with linux (even a script or executable currently used). With windows, files are open exclusively so that may explain why. Concerning using the same file issue, timestamping seems straightforward but deleting old logs will not be easy. I would say most players will never open several instances so it's minor and not worth fixing.

**Comment by Bertram25** [comment]
I agree it's not worth fiddling since it's not the standard behaviour if it comes to handle timestamps and file copy.

**Comment by Bertram25** [comment]
That said, maybe later add a copy to set the log filename on the command line could be thought of?

**Comment by hwoarangmy** [comment]
> That said, maybe later add a copy to set the log filename on the command line could be thought of?

That's what I was going to propose ^^

**Comment by akien-mga** [comment]
> Concerning using the same file issue, timestamping seems straightforward but deleting old logs will not be easy. I would say most players will never open several instances so it's minor and not worth fixing.

My idea was more:
- initialise the log file as "opendungeons-20150410-174720.log" and write to it.
- in the function that closes OD, do the usual renaming that makes opendungeons.log.N become opendungeons.log.N+1 (2 → 3, 1 → 2, 0 → 1) and rename opendungeons-20150410-174720.log to opendungeons.log

This way we shouldn't have conflicts because the two instances of OD would have different logs (unless they are started in the same second, but we can make the timestamp more elaborate if need be), and the log of the first instance closed would become opendungeons.log, and then closing the second instance would push this new log to .log.1 before renaming its own log to opendungeons.log.

The only two implications are that:
- we need to save the timestamp somewhere to reuse it in the quit function
- if the game segfaults, the log will keep the timestamp (but this way we're sure that we never lose segfault logs ;)).

**Comment by Danimal696** [comment]
what about an error message that warms that another instance of the game is open?

**Comment by hwoarangmy** [comment]
@akien-mga your idea is not bad but if a crash happens, we loose the log and that's not acceptable IMHO.

> what about an error message that warms that another instance of the game is open?

For development reasons, it is required to be able to launch several instances of OD. I will make a simple patch that surrounds by a try/catch logs renaming and prints a message if the log could not be renamed. That should be enough IMHO

**Comment by akien-mga** [comment]
> your idea is not bad but if a crash happens, we loose the log and that's not acceptable IMHO.

No, as I said, if a crash happens the log will just be named "opendungeons-$timestamp.log" instead of "opendungeons.log".

**Comment by hwoarangmy** [comment]
> No, as I said, if a crash happens the log will just be named "opendungeons-$timestamp.log" instead of "opendungeons.log".

When I say "we loose the log", I want to say that we will have a log with an unknown filename that will not be removed. And, as I said, that's not acceptable IMHO because, with time, we might have plenty of them. And, again, there is no real need...

**Comment by akien-mga** [comment]
> When I say "we loose the log", I want to say that we will have a log with an unknown filename that will not be removed.

Ah, my bad, I misread and thought you meant "lose the log", not "loose" :)

So yes your commit fixes the issue of not being able to start two instances on Windows. But are we not hiding the real issue? What happens to the log file when two instances of OD are writing to the same file?
