### ISSUE TITLE
Add support for non-ASCII characters in the chatbox

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#66]
Pull request #59 fixed segfaults when typing non-ASCII characters in the chatbox, and that was indeed the highest priority thing to do in this regard.

In a second step, it would be nice to add support for non-ASCII characters in the chatbox, for example accentuated characters. As to determine which characters we should support exactly, I'll leave it to more experienced developers; I guess support the whole of UTF-8 is probably not that straight-forward, but I don't know if supporting latin-15 characters would be any easier (and if it would make sense if the characters are typed on a UTF-8 system).

Note that the multiplayer mode GUI seems to support some non-ASCII characters in player nicknames (at least "é"), and they get changed to spaces in the chatbox.

**Comment by Bertram25** [comment]
This one is mine!! ;) (I've got something in preparation...)

**Comment by oyvindln** [comment]
We should probably be using a CEGUI window for this.

**Comment by hwoarangmy** [comment]
> This one is mine!! ;) (I've got something in preparation...)

It is open for more that 0.5 year. I guess it is safe to think that nobody is going to steal it from you ;-)

> We should probably be using a CEGUI window for this

I'm not sure about that. In the RTS games I know, chat is usually shown on the screen (equivalent to an Ogre overlay). A CEGUI window would reduce the size of the screen and hide the game...

**Comment by Bertram25** [comment]
> I'm not sure about that. In the RTS games I know, chat is usually shown on the screen (equivalent to an Ogre overlay). A CEGUI window would reduce the size of the screen and hide the game...

To answer a bit of it, I've begun work on this out of fashion and after some readings about utf8 stuff, and I've already started adding a cegui panel for the next gen chat. The "panel" is a staticImage widget without any frame or background, making it look like the old panel, but with color and image within text support, just like the good old Ogre text Overlay. So no real estate lost here.
I've also found how to pass utf8 strings to OgreOverlayPanel->SetCaption() so that we can later translate mouse hover texts without exception faults.

I'll make a PR once I'm satisfied with the code.
