### ISSUE TITLE
Modes handling

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#670]
@hwoarangmy @oyvindln 

Hey there guys :)

We've all been in the frenzy of preparing the release but I'm convinced @oyvindln raised a good thought when we spoke about how we should handle modes.
For instance, I just push a fix for clearing the chat queue on Game/editor mode exit, but that's not ideal because the event queue will for instance be cleared up when you open/close the console.

Thus, we should (after release) take a bit of time to see whether we can improve and more importantly whether we can simplify how we handle modes.

@hwoarangmy spoke about a state machine where several modes could live at the same time and @oyvindln isn't convinced about that.

IMHO, we should make it the simplest possible and I'd first have a look at whether we actually have a case where we need the previous mode when running the new one, and then maybe remove the DiscardPreviousMode parameter.

Feel free to comment. :)

**Comment by hwoarangmy** [comment]
You know, I am someone simple but when I see stuff like:
https://github.com/OpenDungeons/OpenDungeons/blob/development/source/modes/ModeManager.h#L52
A red flag shows up telling "wrong conception, big hack detected".

Then, I see stuff like:
https://github.com/OpenDungeons/OpenDungeons/blob/development/source/network/ODClient.cpp#L229
(and there are lots of them), and another red flag raises telling "wrong conception, object polymorphism should be used there".

And, last, allowing modes to be on at the same time would allow to share menus between ingame and main menu (for example settings). And I'm not talking about the First person mode that was originally planed (even if I am not fond of the idea).

**Comment by Bertram25** [comment]
Good stuff pal. :) Speaking freely that way about the code is IMHO what makes the project vision advance the most.

IMHO, being a simple man, aka liking things simple and slick is a quality, and in many ways, I think your instinct can be trusted.

Now, to speak about the specific hurting parts of the code:

If you speaking about the settings like the game settings, I'd myself say that the the settings is a app-wide "mode" or I would rather say "menu", just like the console itself could be, in fact.
Thus, it shouldn't be part of the modes IMHO.
If you were speaking of the settings being parameters taken from a mode to another, I'd need a case. But for now, we're doing fine without having to pass settings between modes directly, IMHO.

The console "Mode" could also be a component of any mode, or at least the game/editor mode like the gamemap is, and be activated a bit like chat is, since it's quite close functionally speaking. And then, not be a mode anymore.

Last but not least, if we ever add this one, the "First person mode" is IMHO yet another component of the Game(/Editor?) mode and should be handled by it, thus not a mode anymore.

With all the aforementioned changes, then we wouldn't need a mode queue anymore and simply let the current mode request the next one before dying based on user input.

**Comment by oyvindln** [comment]
I think we should consider trying properly doing [component-based design](http://gameprogrammingpatterns.com/component.html), and create "modes" using composition.

**Comment by hwoarangmy** [comment]
IMHO, we should define once and for all what a mode is. ATM, it is clearly not well defined. If we look at how modes are handled, we see they are stored in a vector in the ModeManager. Moreover, ModeManager provides an API that allows to get the current mode. That clearly suggests that modes are meant to be exclusive (I even remember that before I moved map loading to the server, it was done in the game mode activation which clearly suggests that modes are not means to be removed while using the same game map).

On the other hand, we have the console. Even after @oyvindln work about cleaning the stuff, letting the console be a mode clearly suggests that modes are not exclusive.

I remember asking that in the forum some months ago and, back then, it was said that modes were "input grabbers". From this point of view, having the console as a mode was not stupid.

> I think we should consider trying properly doing component-based design, and create "modes" using composition.

I agree but when I look at the code, for the reasons I've already said in this issue, all modes have clearly not the same functions. That's why I'm telling that we should decide and try to stick to what we will have decided (and comment so that it is clear for everybody what modes should be used for).

> Last but not least, if we ever add this one, the "First person mode" is IMHO yet another component of the Game(/Editor?) mode and should be handled by it, thus not a mode anymore.

Again, the problem here is to define what a mode is and what it is responsible for. We all already know that we could do the same without using modes at all. But the goal is to try to have as few links between different parts of the code as possible and modes are a way to do that.

> If you speaking about the settings like the game settings, I'd myself say that the the settings is a app-wide "mode" or I would rather say "menu", just like the console itself could be, in fact.
> Thus, it shouldn't be part of the modes IMHO.

Well, we could say that for almost every mode except the main menu (most games allow to start a new game, load a game, ... directly from their "game mode").

That being said, I am not an advocate of the state machine. It is just an implementation that could fit IMO, like others also could. But if we decide that modes are exclusive, we should not let the console be a mode (but something much closer to the actual chat as it is pretty similar).

**Comment by Bertram25** [comment]
> That's why I'm telling that we should decide and try to stick to what we will have decided

Agreed. Be it a state machine, component based or something else, we should find a consensus first. To sum up: My own suggestion is to adapt the current code and make "modes" exclusive, with specific components + global-scoped components for the settings and a Game/Editor scope for the console.

> I think we should consider trying properly doing component-based design, and create "modes" using composition. 

@oyvindln Your turn. ;) Are you still convinced of a (full) component-based design? If so, then how specifically do you see how it will help us here?

Best regards,

**Comment by hwoarangmy** [comment]
> @oyvindln Your turn. ;) Are you still convinced of a (full) component-based design? If so, then how specifically do you see how it will help us here?

And how do you see what should be done about the console and the intertwined menus (settings, load, ...)

**Comment by oyvindln** [comment]
> Agreed. Be it a state machine, component based or something else, we should find a consensus first. To sum up: My own suggestion is to adapt the current code and make "modes" exclusive, with specific components + global-scoped components for the settings and a Game/Editor scope for the console.

Yeah, that's sort of what I meant with component-based design. The console and other windows can be made separate objects contained in the respective mode instead.

**Comment by Bertram25** [comment]
Ok, so I propose:
- The thing we currently know as "Modes" (that can stay named that way) are exclusives, they are mother input grabbers and are those:
  - Main menu.
  - Skirmish.
  - Client join.
  - Server host.
  - Configure Seats.
  - Game.
  - Editor.
- The Settings window is a global scoped menu, available through a button and/or a shortcut key in the modes giving access to it.
- The FPS mode becomes a member of the Game and Editor modes, or in other words, the GameEditorBase mode. We'll have to look at whether we still want it, and if there is interesting code there, and do the appropriate cleanup.
- The console becomes a member the Game and Editor modes as well, just like the FPS one. The GameEditorBase class shall have responsibility on handling input/gui sheet handling for this one.
- The Get currentModeExcept\* can then be removed.

The last question left maybe is how shall we cleanly pass info from one mode to another. To know that, we'll have to know what info is needed first. I'd suggest the above changes are agreed upon and made first, though.

Ok with it?

**Comment by hwoarangmy** [comment]
I guess what you propose is the easiest to do considering the actual architecture. To pass the data between modes, the most straight forward would be to use a structure that survives through modes, probably the gamemap, as it is done ATM.

Also note that doing it this way will imply that gamemap goes through modes (and, thus, will never be a member of gamemode as we wanted to do). Moreover, the component based design will not be easy to follow as gamemode will not stop growing as it is basically the mode that will do almost everything.

**Comment by Bertram25** [comment]
> Also note that doing it this way will imply that gamemap goes through modes (and, thus, will never be a member of gamemode as we wanted to do). 

That's a fair trade. I'm fine with it.

> Moreover, the component based design will not be easy to follow as gamemode will not stop growing as it is basically the mode that will do almost everything.

Hence, why we separate the gamemode in smaller things, like the tileContainer, the pathfinding struct, ...

@oyvindln ?

**Comment by oyvindln** [comment]
> The thing we currently know as "Modes" (that can stay named that way) are exclusives, they are mother input grabbers and are those:

The various menus could also be components in the "menu mode". Though I suppose some of it can be separate modes as we aren't supposed to have more than one of them active at the same time.

Or, if we want to be really crazy, we could try [FRP](https://en.wikipedia.org/wiki/Functional_reactive_programming)

> To pass the data between modes, the most straight forward would be to use a structure that survives through modes, probably the gamemap, as it is done ATM.

It could still be moved around, though I do at least want to try to reach a design where the gamemap object is destroyed and created rather than having to manually clear things like it is now.

**Comment by Bertram25** [comment]
> The various menus could also be components in the "menu mode". Though I suppose some of it can be separate modes as we aren't supposed to have more than one of them active at the same time.

If we haven't got more than one menu active at the same time, then plain polymorphism is enough, then.  Or is there something components will help compared to that solution?

> It could still be moved around, though I do at least want to try to reach a design where the gamemap object is destroyed and created rather than having to manually clear things like it is now.

It's a fair goal.

**Comment by Bertram25** [comment]
I'll deal with this issue first, so that I can cleanly work on settings afterwards.

**Comment by Bertram25** [comment]
Closed with 78c4e1e3a1ac1974a02e170ed3a53d179878f4a2 54a7772493b79781e3b2924d1af493ddbd410b70 and 2b61e4d3955c7b304d6293fe39a6b33a02eec254
