### ISSUE TITLE
The Bridge: ideas for gameplay enhancement

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#673]
As discussed with @akien-mga , that map could have small bridges on both sides for both seats, some fake gold sometimes to hint the way, for instance, and a rogue portal, for instance on both extremities, but not too far from opponent' side, so that it's always something to guard.

**Comment by akien-mga** [comment]
IMO we should add the multiplayer version for 0.5.0, even without the additions mentioned above. I'll do a quick and dirty multiplayer version without changing the setting too much, and I'll let you do the adjustments that you want for 0.6.0.

**Comment by oyvindln** [comment]
Why do we have a separation between singleplayer and multiplayer maps in the first place?

**Comment by akien-mga** [comment]
> Why do we have a separation between singleplayer and multiplayer maps in the first place?

I guess the idea is that multiplayer maps needs to be "fair" for all players, while singleplayer maps can be designed so that the AI players and the human players have different resources/possibilities. For example Scream in the Dark was designed with the idea that the player would be in seat 1, and all other seats have a pre-built base from scratch.

The distinction makes sense IMO, but I agree that currently we don't really use this feature. Maybe we could drop the file-based distinction, and just add a level parameter that says whether a level is skirmish only, multiplayer only or can be both.

**Comment by Bertram25** [comment]
Because single player maps can be designed to give an advantage to the available seats, while the multiplayer ones should balance the available slots.
See the single player games as one-level campaigns.
The fact that we're reusing content from one to another is because it's making us earn time. But I agree that the single player and multiplayer modes should later have more unique scenario.

**Comment by akien-mga** [comment]
I've renamed the issue since I'll take care of the "make it multiplayer" component in my next PR. The ideas that I discussed with @Bertram25 are valid both for skirmish and multiplayer IMO.

**Comment by Bertram25** [comment]
Ah @akien-mga was quicker than me.
IMHO, it's a bad idea to merge files in the same folder because it will make things messy when we have more levels.

**Comment by akien-mga** [comment]
>  IMHO, it's a bad idea to merge files in the same folder because it will make things messy when we have more levels.

On the other hand it makes maintaining the skirmish and multiplayer versions of a same level quite messy too, because changes need to be made in two files.

**Comment by Bertram25** [comment]
Thanks @akien-mga, I'll indeed make the changes for both maps. The bridge is a bad example as it clearly looks like a lan map adapted for single-player more than the other way around.
I'll add more difference between the two versions to reflect my initial idea. ;)

**Comment by akien-mga** [comment]
>  I'll add more difference between the two versions to reflect my initial idea. ;)

Sounds great :-) Basic multiplayer version incoming for 0.5.0.

**Comment by Bertram25** [comment]
I'm on a

**Comment by Bertram25** [comment]
> On the other hand it makes maintaining the skirmish and multiplayer versions of a same level quite messy too, because changes need to be made in two files.

I'm on a phone, please be indulgent with my writing for that. ;)
Yes, only if the files look too much the same. Which is why we should try to make each experience more unique, IMHO. :)

**Comment by hwoarangmy** [comment]
> it makes maintaining the skirmish and multiplayer versions of a same level quite messy too

It is messy because we choose to use single player maps for multiplayer. But as you have already said, the maps are going to be different (for example, by removing the prebuilt rooms). Thus, the maps will be different and, if you want to change something, you will have to change in both maps, be it on different folders or not.
As @Bertram25 said, skirmish maps should be seen as one level campaigns.

**Comment by Bertram25** [comment]
And yes, we're speaking of level design, which means we're in the production preparation phase already. \O/

**Comment by akien-mga** [comment]
After reading your comments, here's how I envision things:
- we keep the distinction skirmish/multiplayer, since skirmish levels are meant to have some kind of "scenario" like one-map campaign
- for future release, we try to actually produce those skirmish levels that are great to play solo, and multiplayer maps that are awesome to play with friends
- we add an optional parameter in multiplayer maps that make them appear in the Skirmish menu too for those maps that are meant for multiplayer but can be fun playing solo against the AI. That would be basically the same as using the Host menu to create a server with one player + AIs, but IMO it would be nice to access it directly from the singeplayer menu too.

**Comment by akien-mga** [comment]
In Warcraft 3 (playing this currently, this game is still freaking awesome), they also have this kind of distinction: when you select "Custom Game", most games are multiplayer maps that you can play solo against the AI, but there is also a "Scenario" folder (and a "Frozen Throne" folder, I guess those are scenarios from the expansion) with some maps that are more like what we want for our skirmish levels.

**Comment by Bertram25** [comment]
Your summary looks very relevant to me. :)

**Comment by Bertram25** [comment]
Btw, I'll make the planned changes to the level (on both versions), but I do think @akien-mga is right we should add a level option to make certain multiplayer levels available in single player mode and remove certain redundancy.
Can I open an issue about it?

**Comment by akien-mga** [comment]
>  Can I open an issue about it?

+42 :-)

**Comment by Bertram25** [comment]
> +42 :-)

k, I'll do it. Time to sum up a bit what we want on the 0.6.0 topic, btw. :)
