### ISSUE TITLE
Remove level redundancy

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#696]
Taken from @akien-mga 's comments:

Skirmish levels should be designed to be played alone (and therefore not necessarily fair to all seats, which can help create more of a "scenario"), and multiplayer levels meant to be fair for all seats.

Yet, to avoid redundancy in levels as it is for now, multiplayer levels should be made available from the skirmish menu if they are tagged as such by a level parameter (i.e. we should drop the skirmish version of some multiplayer-intended levels, and make it possible to start those multiplayer levels in singleplayer if they have an argument such as "AlsoSingleplayer").

**Comment by Bertram25** [comment]
Ideally to be done before #673

**Comment by hwoarangmy** [comment]
Well, here, I'm not sure it is such a good idea. When thinking about this kind of stuff, I usually think about how it is handled in the games I know. AFAIK, most of them allow to play multiplayer with only 1 player and they do not display common maps for multiplayer and skirmish.
Secondly, we currently dupplicate levels because we don't have many. When we will have more, skirmish will be more or less reserved for scenarised maps where multiplayer will be reserved for "fair" levels.
Lastly, I think it will be messy to display certain maps in the skirmish menu and, if someone wants to edit it, to see it as a multiplayer map. Moreover, if someone wants to edit it and make it less fair for one player because he had a great level concept in mind, it will be changed for both (unless we do some nuclear logic to automatically copy edited multiplayer levels to skirmish if they are open somehow explicitely saying we want to open it for skirmish edit)

**Comment by Bertram25** [comment]
Well, yeah, it is true that one can host a one player server game, resulting in the very same thing than a skirmish game.

I think the main point is that people won't catch that fact easily and reusing the skirmish menu should help with this.
In WarCraft III, players can select multiplayer map after a conscious fashion when clicking on the mutiplayer folder when starting a skirmish.
Maybe instead of adding parameters in the levels and lie to the player about the leve list, we could instead add a combo box, for instance, permitting to let the player list either the single player scenario or the multiplayer ones?

WDYT?

**Comment by hwoarangmy** [comment]
I think it is better to make it clear. And, the combobox is a good solution. The difference between starting a multiplayer game from skirmish menu would be to fill other players with AI (even if stated as "player only seat" ?)

**Comment by akien-mga** [comment]
> I think it is better to make it clear. And, the combobox is a good solution.

The combobox solution would be fine with me.

> The difference between starting a multiplayer game from skirmish menu would be to fill other players with AI (even if stated as "player only seat" ?)

If a multiplayer map has some seats that are "player only", then it can't be turned into a singleplayer map in my opinion. Hence my proposal to make this an opt-in parameter, if we ever wanted to create multiplayer maps that would not be suited for singleplayer.

But actually, I don't really see why we would create multiplayer maps with "player only" seats, that would be faulty by design IMO, since it would force a minimum number of players in a map (e.g. you couldn't play a 3-player map if you have only one friend to play with).

**Comment by hwoarangmy** [comment]
> If a multiplayer map has some seats that are "player only", then it can't be turned into a singleplayer map in my opinion. Hence my proposal to make this an opt-in parameter, if we ever wanted to create multiplayer maps that would not be suited for singleplayer.

Well, if we use a new parameter to tell if the map can be played in multiplayer, we definitely have to replace players by AI. However, we could also state that only multiplayer maps that do not have more than 1 player only seat can be played in skirmish (this way, we don't need to tell if the map is multiplayer only - avoiding description parameters is always good when they are not needed even if in this case, I could defend the opposite).
Just like you, I don't know why one would create a map with more than 1 seat player only but I guess the community you are creating that will make hundreds of maps will have more imagination than both of us ^^

**Comment by akien-mga** [comment]
I've thought a bit about this feature, and I think we could have something like this:
![od-combo1](https://cloud.githubusercontent.com/assets/4701338/7550789/f3d87152-f66f-11e4-8006-447e965f2f82.jpg)

The combobox would let you switch between Skirmish maps, Multiplayer maps (though we probably need a better name for those than "Multiplayer" when you play them solo), and maybe also User maps (could be an easy way to handle the levels in #383).

Note that I've had quick look, and I don't think I would be able to code this feature by myself yet, or at least it would take me a looong time :)

**Comment by hwoarangmy** [comment]
seems good

**Comment by Bertram25** [comment]
@akien-mga Your idea is pretty good. I like it. :)
If nobody else does it, I'll take it once I'm done with the current PR.

**Comment by Bertram25** [comment]
Once this PR is in, mind handling the level part @akien-mga ? :)

**Comment by akien-mga** [comment]
Sure :)

**Comment by Bertram25** [comment]
Thanks. :)
