### ISSUE TITLE
Adjustments to the new spell logic

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#710]
- [x] Make the the spawn worker spell have a 0 cooldown value. 581b02858a1b33fe4ca30305731dd7c0c74c56f3
- [x] Make the spell be casted only if it's relevant. I mean if it has no effect, it shouldn't trigger. 0e50df85297b7d23c2776d99991c9cdb79c06a5b

Question:
Make the heal, explode, and spawn worker spells castable on creatures whatever their tile type is?
Done. Heal and Explode will be castable only on own claimed tiles for now.

**Comment by hwoarangmy** [comment]
> Make the the spawn worker spell have a 0 cooldown value.
> Make the spell be casted only if it's relevant. I mean if it has no effect, it shouldn't trigger.

ok.

> Make the heal, explode, and spawn worker spells castable on creatures whatever their tile type is.

I'm not sure that it is a good idea because it would allow to cast spells behind claimed walls (since they give vision). I'm not sure it is compatible with this behaviour. But maybe with a spell upgrade, they can change from "castable on claimed tiles" to "castable on not enemy tiles (claimed + unclaimed)" and finally to "all tiles".

**Comment by Bertram25** [comment]
> I'm not sure that it is a good idea because it would allow to cast spells behind claimed walls (since they give vision). I'm not sure it is compatible with this behaviour. But maybe with a spell upgrade, they can change from "castable on claimed tiles" to "castable on not enemy tiles (claimed + unclaimed)" and finally to "all tiles".

I'll be honest, I don't think we should make spells that complicated. And I do think different spells should have different cast conditions support.
For instance, I'd like to have heal be castable on ally creatures whatever the tile is, explode on ally claimed tiles, spawn workers and call to war on any visible tiles.
WDYT?

**Comment by hwoarangmy** [comment]
> For instance, I'd like to have heal be castable on ally creatures

Ally creatures ? That would mean that is you want to focus on 1 particular creature, it will be harder since casting the spell may randomly choose a weak ally creature when you wanted to heal your pitdemon ^^

However, I would say it is a player question (rather that a dev question) so let's ask what everybody wants.

@akien-mga @Danimal696 @eugeneloza @oyvindln  WDYT ?

**Comment by Bertram25** [comment]
> However, I would say it is a player question (rather that a dev question) so let's ask what everybody wants.

Sure, you're right. :)

**Comment by hwoarangmy** [comment]
I will take care of not casting spell if no targets. However, I won't close this issue until we decide if we allow casting spells on allied creatures or only owned.

**Comment by Bertram25** [comment]
> I will take care of not casting spell if no targets. However, I won't close this issue until we decide if we allow casting spells on allied creatures or only owned.

Let's open a new issue about this, and close this one. I'll deal with it.

**Comment by Bertram25** [comment]
Extended by #741
