### ISSUE TITLE
384000 mana required while 250000 is max

### ISSUE THREAD

**Issue by eugeneloza** [OpenDungeons/OpenDungeons#718]
To summon a new worker I need 384 ths mana, while the mana caps at 250 ths. This is not a problem, but the message should better read like 'you cannot summon any more kobolds' rather than red 384000 number.

**Comment by hwoarangmy** [comment]
seems fair

**Comment by Bertram25** [comment]
IMHO, this issue is not relevant for several reasons.
The very first one is that we planned to let players unlock higher mana max later on by adding corresponding skills in the skill tree. (Even if it's not quite formally said anywhere. ;])
And secondly, it's pretty explicit you can't spawn a worker when the summon worker spell cost 384000 mana and you only have 250000 (max or not). The text overlay is red with the amount required.

If you guys are ok with it, I'd request to close this as a Won't fix.
But feel free to keep opening anything you think needs improving. :)

**Comment by hwoarangmy** [comment]
> The very first one is that we planned to let players unlock higher mana max later on by adding corresponding skills in the skill tree

Didn't knew that ^^
In this case, it is better to let the mana amound displayed

**Comment by Bertram25** [comment]
> Didn't knew that ^^
> In this case, it is better to let the mana amound displayed

Well, I'm evil (and a mere mortal), that may explain that. ;)

**Comment by Bertram25** [comment]
k, we're two agreeing with this, so let's close.
Feel free to reopen if you see anything relevant.
