### ISSUE TITLE
Unneeded rooms & traps

### ISSUE THREAD

**Issue by eugeneloza** [OpenDungeons/OpenDungeons#720]
Are 'no longer needed rooms and traps' are needed? I.e. we have a library for research. But when all research is done, there is no need in the library so it seems to be practical to demolish it.
The same relates to traps. They cost quiet a handful of money to build but when the battle shifts to other areas they are (hopefully) no longer needed. Can they be 'transported' to a new location, or should they be demolished instead?

**Comment by Danimal696** [comment]
i have been playing dungeon 2 these days and i love their trap mechanics; ill explain:
-Traps and doors are free
-Workshop make only toolboxes
-The traps and doors cost is represented in needed toolboxes (2 for wooden door,  4 for spinning trap...)
-The workers carry the toolboxes to the trap until all needed boxes are there and then start building the trap
-Meanwhile the worshop creatures create boxes until the workshop is full of them

The production at workshop is the only limitation and since workshop creatures are weak if a player wants to focus on traps his military power will sufffer, so it evens traps not having a money cost

**Comment by hwoarangmy** [comment]
well, both mechanisms can be used. I don't particularly prefer one or the other way.

@Bertram25 @akien-mga @oyvindln WDYT ?

**Comment by Bertram25** [comment]
Hey there, :)

There are several interesting things there.

> we have a library for research. But when all research is done, there is no need in the library so it seems to be practical to demolish it.

I think I disagree. Why? Well, you're right that the library is no longer needed for research once you've researched everything. (even if later, with more skills, they will be needed longer.) <- The goal to btw to make it impossible to research everything in a reasonable amount of time.
Also, they're still needed to keep attracting certain creatures. So that's a strategical point of view and not a game design's fault here IMHO.

> The same relates to traps. They cost quiet a handful of money to build but when the battle shifts to other areas they are (hopefully) no longer needed. Can they be 'transported' to a new location, or should they be demolished instead?
> 
> dungeon 2 these days and i love their trap mechanics; ill explain:
> -Traps and doors are free
> -Workshop make only toolboxes
> -The traps and doors cost is represented in needed toolboxes (2 for wooden door, 4 for spinning trap...)
> -The workers carry the toolboxes to the trap until all needed boxes are there and then start building the trap
> -Meanwhile the worshop creatures create boxes until the workshop is full of them
> The production at workshop is the only limitation and since workshop creatures are weak if a player wants to focus on traps his military power will sufffer, so it evens traps not having a money cost

Here, if we go towards the dungeon II's logic, we'll still have the old unneeded traps "problem".
But is this a "problem" or part of the game strategy?

Secondly, we've already done a bit of back and forth with the traps logic (and the creatures creating traps aren't weak at all, btw).
I think the real problem is that traps are costing gold and that gold quickly runs out in levels, making those a very hard part to put in place without luck and serious gold management.

I've got nothing against the toolbox's idea at all. (it's smart :]) but we will have to weaken the creatures making traps in that case.
So are we willing to go that way or do you prefer reducing the traps cost instead to make them less hurting when you buy them?

**Comment by Danimal696** [comment]
traps could also be free but its creation worshop points upped by x4 so they are not so easily layed

**Comment by hwoarangmy** [comment]
There is a philosophic choice to do here. IIRC, there was 3 "ways": creatures, spells and traps. Creatures need gold, spells need mana and if traps are free, they might be overpowered...

**Comment by Bertram25** [comment]
> spells need mana and if traps are free, they might be overpowered...

This is true, as this means that once you have a workshop, you won't stop adding traps.
This is truly making me think that we could have a go at simply reducing the traps price and see how only doing this will change the gameplay.
The toolbox mechanism isn't not incompatible with this idea, but doesn't add much to the gameplay if we keep making trap cost gold.
On the strategical field, adding traps will mean you have less rooms or more slowly since you're using your gold there, and creatures making traps won't be training. IMHO, this is correct and we should move on.

But it's just me. WDYT?

**Comment by hwoarangmy** [comment]
well, in reality, ATM, one creature can easily craft as many traps as you want. In any case, I think we should not spend too much time on balancing until we have a decent number of traps/rooms/spells. The time to play will come soon and that will be the occasion to see all that in action. But remember that creatures now store all the gold they got for payday. That means that gold will be a little bit less a need ^^

**Comment by Bertram25** [comment]
k. IMHO, one more argument to wait and see. If nobody else has strong argument against, I'll close this one in a few days. If anything else pops up, feel free to reopen later. :)

**Comment by Bertram25** [comment]
Closing as won't fix. Feel free to reopen or open a new one if anything feels relevant.
