### ISSUE TITLE
Heroes fight each other and empty space?

### ISSUE THREAD

**Issue by eugeneloza** [OpenDungeons/OpenDungeons#724]
The heroes seem to fight each other and empty space after defeating the keeper.
![odscreenshot_2015-05-03_145224_8](https://cloud.githubusercontent.com/assets/10726162/7444929/0e2b55e8-f19c-11e4-80ad-5ae24c89fdc4.png)
A group of wizards attacking an empty tile:
![odscreenshot_2015-05-03_145043_6](https://cloud.githubusercontent.com/assets/10726162/7444928/0e2aefae-f19c-11e4-9bda-aa4fa3236856.png)
Replay:
https://www.dropbox.com/s/xwfd0hgm82jt6g0/replay_20150503_142216.odr?dl=0

**Comment by hwoarangmy** [comment]
I've not had a look at your replay but for the heroes fighting each others, it comes from them not being of the rogue faction. Because of that, they have mood. And when they are angry for too long (because hunger/tiredness/paydays), they become rogue and fight the other heroes. We should decide what to do about that. If we want to change that we could:
- allow some seats to behave like rogue ie no mood modifiers
- use the rogue seat for portal waves

Concerning the wizards, they are ranged units. They attack at 5 tiles. Are you sure there were no rooms around ? We can see some gold bags suggesting a treasury room...

**Comment by eugeneloza** [comment]
> Are you sure there were no rooms around ? We can see some gold bags suggesting a treasury room...

Absolutely. The treasury gold is 'what remains of the temple'. No more creatures. They just hit an empty tile after defeating me (noticed this in 2 different games)

**Comment by hwoarangmy** [comment]
ok. I will have a look then
BTW, don't you have the log file ?

**Comment by hwoarangmy** [comment]
I've had a look at your replay. I confirm the wizards are attacking rooms. If you have changed nothing, their range is 7 and there is the dormitory not far.
Actually, I think the bug is that they are attacking through the wall. That can be seen here:
![odscreenshot_2015-05-05_010224_1](https://cloud.githubusercontent.com/assets/7493706/7464433/8a5f0196-f2c3-11e4-9848-da7d358e7924.png)

And here, a wizard is attacking the library:
![odscreenshot_2015-05-05_010253_3](https://cloud.githubusercontent.com/assets/7493706/7464480/9f466de2-f2c3-11e4-90f4-a60d2f62ce48.png)

In any case, I'm waiting for you one of the artist to get a nice mesh for a wizard missile (magic). That would allow to create a missile and better see what they are doing ^^

**Comment by Bertram25** [comment]
> In any case, I'm waiting for you one of the artist to get a nice mesh for a wizard missile (magic). That would allow to create a missile and better see what they are doing ^^

I do think a flame particle effect could do the trick. ;)
For instance, we could reuse the cannon ball + flames?

**Comment by hwoarangmy** [comment]
why not. I will have a look

**Comment by eugeneloza** [comment]
Haaa! Now I get it. Really they looked like punching an empty space...
The particles is the way to go. Something like this? https://youtu.be/JEiKX_xXTVQ?t=14m44s

**Comment by hwoarangmy** [comment]
BTW, now that I come to think about it, I'm pretty sure they check what to fight on visible tiles only. That means they cannot attack through walls.
In the first picture, I think they are attacking the tiles where the Knights are (which are more or less 7 tiles away)
