### ISSUE TITLE
Have creatures face each other when fighting

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#73]
Currently fighting creatures are not necessarily facing each other when battling.

They sometime occupy the exact same position (and then regardless of the direction of their battling animation, they can't face each other). In other times they occupy adjacent positions, but their animations are not directed toward each other (for example both creatures can have their animation in the same direction, making as if one creature was hitting the other but the other one is fighting with air).

It's not that clear on my screenshot, but it's pretty obvious in game.
![od-battle1](https://cloud.githubusercontent.com/assets/4701338/3957566/bba351ae-2716-11e4-8027-4d6635bdfd86.png)

**Comment by Bertram25** [comment]
Attack range might be involved.

**Comment by Danimal696** [comment]
Regardles of attack range, the non-existant cooldown between attacks and mainly the battle system that is based on creature on one tile rather than creature position on map and low agresivity make this ugly result

**Comment by Bertram25** [comment]
@Danimal696 Nice to see you around. :)

**Comment by hwoarangmy** [comment]
It might have something to do with the server paradigm. I've seen the same thing when workers dig. When they don't need to move before digging, they do not change where they are facing. And if it is not the tile they are digging they do not dif in the good direction. If I'm right, that's just an optional parameter to give when changing animations (setAnimationState - if the server makes him face the good tile).

In fact, on the client side, creatures are almost only managed by addDestination and setAnimationState. On the client side, they don't even know which creature they are fighting. That's why we need to make sure the server gives all the needed information or we can have this kind of behaviour.
