### ISSUE TITLE
Add the Prison room

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#754]
The prison room is a room where you can place the KO enemies after a battle.

Specs proposal:
The enemies there stay a low health and either:
- Die and become Skeletons (?)
- Turn to your side if you have enough gold to tempt them.
- Later: Be reused for spells needing sacrifice or torture. (By making them eat candies until they also die or turn to your side willingly. ;])

**Comment by Danimal696** [comment]
i think jail should be kind of the store room for the torture chamber/sacrifies for temple, creatures that die in here turn to skeletons, and rats lurking inside of it speed the process(like the spiders in cript)

**Comment by hwoarangmy** [comment]
I'm more or less done with the prison. ATM, enemy KO creatures are brought to prison and cannot leave it (as expected). But what about owned creatures ? Can they go through the prison ? If they cannot, that means the prison could be used like a wall. Moreover, what happens if the prison is attacked and your creatures are on the other side of the prison ?

IMHO, the most simple is to let the default behaviour (owned creatures can go through prison). But that might look weird...

@OpenDungeons/developers WDYT?

**Comment by Danimal696** [comment]
Default behaviour +1; lets not complicate ourselves too much with something so trivial

Questions: how much HP is given to captured and jailed creatures? can we jail our creatures as well? what about jailing capacity? HP drop per time? Mood drooping of creatures?

**Comment by akien-mga** [comment]
Default behaviour sounds fine for a first implementation. If we want to refine creature movements, we should probably do it all at once for all kind of environments and rooms that creatures could go through (so that creatures don't walk _inside_ the dungeon heart for example :))

**Comment by eugeneloza** [comment]
Or, the prison might be freely passable by free creatures with imprisoned creatures chained/caged (i.e. to active spots).

**Comment by hwoarangmy** [comment]
> how much HP is given to captured and jailed creatures?

Note that I've implemented 2 kind of KO:
- "KO to death" => The creature will die after some time if not brought by a kobold to bed (if same seat) / jail (if enemy). That happens during a fight. The KO creature plays the die animation and stays on the ground (it cannot be attacked) with 1 HP
- "Temporary KO" => The creature stays stuned and cannot move/be picked up. After few time, it will wake up and continue its normal life. That happens when the creature is dropped by the kepper. Note that the creature can be attacked while temporary KO (but it cannot move itself). No HP is lost during the process

The number of turns the effects last is configurable.

The KO when drop is interesting because it gives a penalty when you drop your creatures (and, thus, gives a bonus to attackers and makes the call to war spell more interesting).

> can we jail our creatures as well?

Not ATM. But I will have a look.

> what about jailing capacity?

1 creature per active spot. If there are more creatures than active spot (for example if you sell a prison tile or if you drop a jailed creature in the prison while it is already full), the last one will be free (just like if you drop a jailed creature in your dungeon outside prison.

> HP drop per time?

It is configurable. ATM 0.01. That makes 100 turns to die which is more or less 70 seconds

> Mood drooping of creatures?

ATM, no impact (since you cannot jail your creatures). And even if I implement jailing for owned creatures I will not change mood for now (that would require to think a bit)

**Comment by Danimal696** [comment]
very well thougth, nice work, and a chance to put the "sad" animation to work

**Comment by Danimal696** [comment]
Im wondering, should i a make a wall of iron bars and one corner as the models? or would a totally different model be better?

**Comment by hwoarangmy** [comment]
the easiest the better IMO.
