### ISSUE TITLE
Mood modifiers are shown on top of the UI

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#784]
As shown in this screenshot:
![od-mood](https://cloud.githubusercontent.com/assets/4701338/7933688/1abaa09c-0921-11e5-933f-cc3af82e5e8c.jpg)

**Comment by hwoarangmy** [comment]
This might be hard to fix. It was already not easy to display overlays on top of CEGUI (for the keeper hand). But displaying CEGUI between the keeper hand and the creature overlays might be even harder

**Comment by Bertram25** [comment]
@hwoarangmy @akien-mga 

My best guess is that we should determine when the GUI should be rendered here:

``` c++
void ODFrameListener::renderQueueStarted(Ogre::uint8 queueGroupId, const Ogre::String& invocation,
    bool& skipThisInvocation)
{
    if(queueGroupId == Ogre::RENDER_QUEUE_OVERLAY && invocation == "")
    {
        CEGUI::System::getSingleton().renderAllGUIContexts();
    }
}
```

I guess the next step is to determine the queueGroupId we have and probably the invocation value?

Other references:
http://cegui.org.uk/forum/viewtopic.php?f=10&t=5694
// make sure you check the invocation string, or you can end up rendering the GUI multiple times
// per frame due to shadow cameras.
