### ISSUE TITLE
Add a button to grab workers easily in the menu

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#84]
- This button should put in the player's hand idle workers first
- No check for worker level ?
- If no idle worker, should we make a difference between tasks ?

**Comment by hwoarangmy** [comment]
We should also kep in mind that this code will probably be shared with the AI

**Comment by Bertram25** [comment]
Just my two cents, (and we have to start somewhere):
- Take idle first, as you said.
- Take the highest level, since you probably want the best digging/dancing rate.
- If no idle, the order should be something like the reverse of the forced action priority list:
  - Take fighting/fleeing first,
  - Then take claimers,
  - Then take diggers,
  - Then take gold digger/depositers or all the rest if more simple.

**Comment by hwoarangmy** [comment]
That's more or less what I had in mind (except for level as I think I could defend both opinions).

**Comment by Bertram25** [comment]
Do you think we could work on at least that button for 0.4.9?
Easily grabbing workers is the most missing gameplay feature atm, IMHO.

**Comment by hwoarangmy** [comment]
Why not ?
IMO, we only need corresponding icons.
While talking about it, we would also need icons for the other creatures and add them in the creature.cfg file.

**Comment by Bertram25** [comment]
The icon should be ready for workers: (the graphic at least)
https://github.com/OpenDungeons/OpenDungeons/blob/development/gui/OpenDungeonsIcons.png
The one on the bottom left is for workers, and the one next to it is for the same button but for fighters.

We agreed to first have a single button for every fighters and later add a button per creature type. See #85 

I was only talking about workers atm since fighters are much easier to grab since they are 90% of the time between the hatchery, the dormitory and the training hall.

**Comment by Bertram25** [comment]
The related code could also help a lot in improving the AI to optimize a bit how it handles claiming/digging, IMHO.

**Comment by hwoarangmy** [comment]
ok. So, let's do that for the 0.4.9 ^^
