### ISSUE TITLE
Suggestion - New damage/resistance type: Poison

### ISSUE THREAD

**Issue by Danimal696** [OpenDungeons/OpenDungeons#877]
in addition to physical and magical, some creatures could be pure poison damage like the slime, also skills like poisoned projectiles/blows or traps.
Is it feasible?

**Comment by Bertram25** [comment]
If I extrapolate, this means damage resistance to (negative) effects on creatures?
Like Stun, berserk,  ...

**Comment by Danimal696** [comment]
doesnt need to, in fact i think those could have a separate value, something like "Special resistance" per creature, but those would need to use a 0-100% to calculate everything? since it wont just be hp lost due to time acting poison, stunned/berserk time would need to be calculated with the % reduction

**Comment by hwoarangmy** [comment]
> Is it feasible?

Everything is possible ;-)
The question is: is it worth the configuration / balancing / coding ? IMHO, it is not a bad idea as 3 damage types doesn't sound too much.

**Comment by Danimal696** [comment]
actually, i would like for just a select few to dish out poison damage, the other creatures can have a defense value depending on tier or some characteristic, like slimes and uskeletons being inmune, ranger and lizardman very resistant...

**Comment by hwoarangmy** [comment]
I might take this one soon. However, I was thinking that poison might not be the best for a new skill. I would think that an armoured creature would be pretty well defended vs a snake or the usual creatures that uses poison. It could be something like "acid", "fire", "cold" or "electricity".
In any case, note that this is only for the game story as technically, its the same.

@OpenDungeons/developers WDYT ?

**Comment by Danimal696** [comment]
i was thinking of it being a special kind of damage, slimes would deal pure poison damage , spiders some (they currently do a bit of magic damage in replacement of poison), some skills would deal it as well, and there could also be an state "poisoned" caused by poison skills used by some creatures. 
Only a few creatures would have partial or total resistance. 
Traps would benefit as well, think on poison gas trap.

 The idea is to make useful certain creatures and create nemesis for them: slime Vs slime = eternal figth; Skeleton > slime. If not, i dont see much use for slime or other creatures since any mage/warrior will deal much greater damage at the same tier and level

**Comment by hwoarangmy** [comment]
Yes, I agree with the logic. I was just saying that poison may not be the most adapted. But that's not a big deal, we can stay with poison.

**Comment by eugeneloza** [comment]
I'd say there might be a 'strategic triangle' or 'strategic task' behind each damage type.
E.g. physical attacks are strong against unarmored targets but weak against armored, electric attacks are strong against armored targets, but deal overall less damage than mlee. And finally the 'strategic triangle' looks like knight (armored, low-hp) kills ogre (unarmored, high-hp), ogre kills electric eel (armored, low-hp) and electric eel kills a knight.
The poison is a little different in this term: the damage is spread in time. E.g. what is a strategical task of killing an enemy in 30 seconds, instead of killing it instantly? If we're playing RPG we'll face a task of either curing poison (distracting our healers), or curing the character (giving us time to heal for more damage). E.g. if our character is hit by 200 pts of poison damage for 3 turns, we can still heal him, even if he has only 100 hp total. But as for a RTS... I don't really see the temporal damage advantage vs instant damage.
It's only about:
- A unit can be killed, but still kills his enemy in some time by poison.
- Poison requires healing by 'heal poison' spell, thus distracting the keeper (and adding micromanagement)
- If poison is not additive then a single creature can poison entire enemy army (by a lot of micromanagement)

Well, maybe just for diversity reason.

**Comment by hwoarangmy** [comment]
In fact, that's my point. Naturally, if we talk about poison damage, I would think it is something that takes time. But if I'm not mistaken, that's not what @Danimal696 wants (and neither do I). We only want another damage type to make interesting to have some units rather than others. Basically, ATM, there is no interest in keeping creeps when you can have the highest creature of a tier. Adding a new damage type would make interesting to keep spiders rather than tentacles if the enemy keeper have mainly some units or the opposite if he has an other kind of units.
Thus, the 3 damage types (physical, magical, poison (?)) are all instant damages. And that would allow to have some kind of triangle as you are talking about (and I also believe it is what we should aim for).

IMHO, that's one of the weakest points of the original DK. Once you had a level 10 vampire or black mistress, you only had to unleash it in an enemy dungeon to kill everything. I think it would be much interesting to have triangles so that using the good units really makes a difference.

**Comment by eugeneloza** [comment]
Another way to make tentacles&slilmes useful - not limit their number. Or... they can even 'breed' under some conditions (e.g. after killing an enemy and consuming its corpse) to multiply their number - a swarm-like creatures. And maybe even a kind of a spell to summon a slime (or a horde of slimes). Harmless alone, but useful as a support unit (not limiting other creatures, or limiting them by 0.1 instead of 1) and dangerous when a dozen of them is here.

**Comment by Danimal696** [comment]
hwoarangmy, thats exactly my idea, calling it "poison" its not mandatory but i cant think of any other name that fits in there

**Comment by hwoarangmy** [comment]
What about "Acid" ?

> Another way to make tentacles&slilmes useful - not limit their number

The problem is that it is true for every tier. We don't want to favorize tentacles only or whatever but to make combinations better than other. Just like your example, we could say that spiders > tentacles, roaches > spiders and tentacles > roaches (that's just an example). And we should have something like that for every tier ^^
That would increase very much game replayability and make it much more strategic (rather than trying to go ASAP to the strongest units like in DK and DK2)

**Comment by eugeneloza** [comment]
Maybe:
Physical
Magical
Shadow<->Light (depending on side, but similar in effect) / Dark<->Divine / Death<->Life
Psi (mental)

**Comment by akien-mga** [comment]
Yes it should stay relatively abstract so that we can categorize creatures among the 3 or 4 kinds of power, e.g.:
- physical/strength
- magical (offensive, like fireballs etc)
- mental/psi
- divine: this depends whether we want to add some kind of religions/evil cults, or just be content with a typical dark side (keepers) / light side. IMO it's maybe enough if we already have three faction-agnostic powers plus creature antagonisms.

If we insert a third power, there should probably be matching creature stats too.

**Comment by Danimal696** [comment]
isnt that overkill? magic can cover for divine/unholy,  the effect is the same no matter the source (something miracleous out of nothing ), physical is pretty straighforward, and thirdly , acid/poison... to give more strategic options, 
Im not agaisnt adding more damage kinds, but we risk a lot of complexity and worst, rebalancing of stats for all creatures.

**Comment by hwoarangmy** [comment]
Yes, I think 3 damage typs are enough (and I guess we all agree on that). However, "mental/psi" doesn't sound adapted for tier 1 units (I cannot imagine tentacles with strong psi powers ^^). IMHO, acid is the more suited even if it can be discussed (especially because of the hero faction). And I'm not for Shadow<->Light because that would mean to rename everything depending on faction.

**Comment by akien-mga** [comment]
My only concern is that we seem to try to introduce a "third power" just for a couple tier 1 units, so I get the feeling it won't bring us to a "triangle of powers" like @eugeneloza described, which would be IMO a nice addition. What other creatures could use the acid power, and how does it relate to the other two (physical and magical)? Would it be efficient against both mag. and physical defense, but deal only little damage?

**Comment by hwoarangmy** [comment]
> My only concern is that we seem to try to introduce a "third power" just for a couple tier 1 units,

No, it's for every tier. Acid would be independant from physical and magical. There would be a defense like for the 2 others (that are not related). I agree acid seems to be for tier 1 only but the goal of this third power would be for creatures of every tier.
In my mind (and I guess in @Danimal696 too), there would be more or less 3 creatures per tier one being specialized per "power". That would allow to have our triangle.

Note that we may think of something better than acid. But I don't see right now ^^

**Comment by akien-mga** [comment]
Yes then we have the same idea in mind. Just wondering if "acid" fits the bill when looking at the creatures we have currently (would heroes have acid creatures for example? maybe a human assassin of some sort with acid/poison-dipped daggers or arrows, but apart from that...).

Just writing about this, I thought we could extend to "acid" category to anything chemistry (or maybe technology) related. Acid is after all just some bad chemicals that eats through metal and flesh. Just a random thought :)

**Comment by hwoarangmy** [comment]
Well, after thinking more about it, acid may not be better than poison. But what about "elementary" (fire, water, ...) ? That could fit for all...

**Comment by Bertram25** [comment]
Hmm, I guess the aim is to use some kind of degenerative effect when hitting a target?
If we can label it with different names to the player while keeping the same mechanism internally, that could make sense. E.g:
- Slime Acid touch: damage to an enemy + degenerative effect.
- Hero Fireball: damage to an enemy + degenerative effect.
  (Same effect, different strength and name.)
  Of course, the description could make this more interesting.
  WDYT?

**Comment by Danimal696** [comment]
Yes, we can have a pure Acid damage that works like physical and magical, and then acid based skills that eats away at enemies HP or lowers their armors or just deal acid damage.
For heroes some creatures could learn acid skills (acid bolt for mage, acid arrow for archer, acid bomb for dwarves) and even acid based weapons for a certain creature (lets say an asssasin) so its not only restricted to evil creatures.
