### ISSUE TITLE
0.6.0 Balancing tweaks

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#898]
- [ ] @akien-mga is right, library stuff grimoire cost should be doubled, so that it's not that easy to get everything, and this will add more strategy.
- [ ] Why are spikes depending on the cannon trap while they are at same level in the research tree?
  Overall, researches shouldn't depend on same level research tree items but on the one level higher items.
- [ ] Spell heal and explosion cooldown values should be tripled, IMHO. Have a look at haste, too.

**Comment by Bertram25** [comment]
Taken from #896

**Comment by Bertram25** [comment]
Note to self: From what I can understand, a research can be... researched once one of its dependencies has been researched.
See: https://github.com/OpenDungeons/OpenDungeons/blob/development/source/game/Research.cpp#L32
So each research should have the one level higher items as dependencies. :) Hopefully easy enough.

**Comment by akien-mga** [comment]
Regarding the research tree and based on @hwoarangmy's input, feel free to change it how you like it. hwo's version was just to implement the code features, but the current placement of skills in the tree and their dependencies are "au pif" IIUC :)

**Comment by hwoarangmy** [comment]
> From what I can understand, a research can be... researched once one of its dependencies has been researched.

That's what the code does. And that's a bug due to a wrong copy/paste because that's not what I wanted to do ^^ Seems like I've inverted the return false/true.
In my mind, all research dependencies have always been required to unlock the next research. And I believe it is the best solution. I had not seen that because ATM, every research as at most one dependency only. But having 1 or 2 depend on several may be a good idea however.

> So each research should have the one level higher items as dependencies. :) Hopefully easy enough.

Beware, I've always stated when coding that all researches dependencies have to be met to unlock a research. Using it as OR (one dependency being enough to unlock a skill) would require to check all mechanics (especially research filling).

> but the current placement of skills in the tree and their dependencies are "au pif" IIUC :)

You understood correctly ^^

**Comment by Bertram25** [comment]
> In my mind, all research dependencies have always been required to unlock the next research. And I believe it is the best solution.
> 
> Beware, I've always stated when coding that all researches dependencies have to be met to unlock a research. Using it as OR (one dependency being enough to unlock a skill) would require to check all mechanics (especially research filling).

So, I guess that pre-release, we should go toward fixing the logic to use a logical AND, and see whether this could achieve the same effect. IMHO, it is fine if we make every researches of a same level in the same skill area needed before being able to move on to the next level of the given skill area, I mean even in the long term.

> but the current placement of skills in the tree and their dependencies are "au pif" IIUC :)

Eh eh. This should definitely become an official figure of speech. :D 
It's fine to me. I fix that rather easily thanks to all the previous work done. :)

**Comment by akien-mga** [comment]
> IMHO, it is fine if we make every researches of a same level in the same skill area needed before being able to move on to the next level of the given skill area, I mean even in the long term.

I agree. There are basically two approaches in a skill tree:
- Linear skill tree, where you need Skill A1 from Tier 1 to be able to unlock Skill A2 from Tier 2. If you research B1 instead, then you can't research A2, but you can research B2.
- Tier-based tree, where you need to research several or all researches or Tier 1 to unlock Tier 2, and then research any of the Tier 2 skills.

Some games, like Diablo 2, use a combination of the two models, where you are limited to a tier until you spend enough skill points, and after e.g. 5 skill points spent you unlock the next tier, but the available skills depend on the linear paths too.

I think we can go with the tier-based tree and not care about the linearity (apart from our three skill categories of course). It makes sense especially since our skills are not closely related to one another currently.

**Comment by hwoarangmy** [comment]
There have already been some discussion on the forum. For the record:
http://forum.freegamedev.net/viewtopic.php?f=37&t=6079

I had something like that in mind:

![skill](https://cloud.githubusercontent.com/assets/7493706/8984599/d693f596-36d2-11e5-8509-3c839bc07365.jpeg)

But with more links (possibility to have a research that depends on more than 1 research). We could also divide the screen in 3 parts representing the 3 paths with different colors.
The spells in the center would be the most powerfull.
