### ISSUE TITLE
Do we want custom culling ? 

### ISSUE THREAD

**Issue by tomluchowski** [OpenDungeons/OpenDungeons#924]
As in question , I implemented a version of custom made culling and the framerate significantly rised .
There were two mechanism involved  sometimes causing crashes. The issue is whether is worth for me to reimplement them ; would they be merged into final code if I somehow achieve the non-crashing status for my code ?

**Comment by Bertram25** [comment]
> The issue is whether is worth for me to reimplement them ; would they be merged into final code if I somehow achieve the non-crashing status for my code ? 

Good question, actually. Getting better FPS is always tempting, for sure.
That said, we remove the custom culling because it has several flaws, and IIRC more than two crashes root causes. Weren't there also tiles culled while they shouldn't be?

Another thing is I'm pretty sure Ogre already does culling on unviewable tiles (otherwise FPS would be very low whatever the viewpoint), so is it worth it? I know such technical stuff can take time and I wonder whether you'd rather want to spend your time on more requested features than this one, being potentially not functional enough in the end. (Remember that now we have normal maps, fps are forcefully a but lower.)

@oyvindln @hwoarangmy WDYT?

**Comment by hwoarangmy** [comment]
As you say, better FPS is always welcome. However, since it is a pretty technical feature, could you please explain how you want to do it ?
Note that if you go for it, since it is technical, it will require to be pretty well documented (by comments in the code) so that we can all review and fix/improve what needs to be.
Moreover, since Ogre 2 is supposed to have a good culling algorithm (according to @oyvindln ), it might be a good idea to wait a bit (even if it is announced since so long that we cannot know when it will be really released)

**Comment by tomluchowski** [comment]
For large maps ( 400x400 ) I get speedup from 30fps to 44fps . By using the tile culling . 
Do you think it is worth programming time ?

**Comment by Bertram25** [comment]
See #954 for the start of implementation. Missing fixes are there.

**Comment by Bertram25** [comment]
@hwoarangmy Isn't this done, btw?

**Comment by hwoarangmy** [comment]
Yes, done in #1198
