### ISSUE TITLE
Settings should be made easier to find in the main menu

### ISSUE THREAD

**Issue by eugeneloza** [OpenDungeons/OpenDungeons#932]
I've been looking for some time for a way to make the game windowed... Until I've figured out that I have to start the game to do so. I think it's good to have settings menu in main screen, just after the game has started.

**Comment by Bertram25** [comment]
Hi @eugeneloza :) I hope you're doing fine.
Actually, you should find a cog button top right of the main title screen doing exactly what you need to, in the 0.6 or HEAD version.

**Comment by akien-mga** [comment]
Reopening and renaming the issue, as IMO the real problem is that settings are not easy to find. On a screen with hi dpi the cogs icon is quite small, and it's somewhat puzzling not to find the settings among the other menu buttons I think.

I'd suggest to either:
- Add a "Settings" button in the main menu (while still leaving the cog icon, it would be a duplicate but it doesn't hurt)
- and/or make the cogs icon bigger

**Comment by hwoarangmy** [comment]
IMO, a new button in game option is the best. That's also what the games I used to play do

**Comment by Bertram25** [comment]
> IMO, a new button in game option is the best. That's also what the games I used to play do

Oops, sorry for looking abrupt in my answer. I thought it was a more simple thing.
I can easily add a Settings word next to the Cog icon. This way, users will link the two at first glance, and make the button a bit bigger.

WDYT all?

**Comment by hwoarangmy** [comment]
seems good to me

**Comment by Bertram25** [comment]
k, then I'll do it this evening. :)
Ok for your @akien-mga @eugeneloza ?
