### ISSUE TITLE
Models from Summoning Wars

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#977]
I didn't knew this game until @akien-mga talked about it but I've had a look and they seem to have some nice models.
They use almost the same frameworks as we do (especially Ogre) and their game universe is close to ours. I've seen some interesting creatures like a skeleton or a lich.
What do you think about sharing some models with them (from what I've seen, there are still commits in their repo so it is still under development) ?

I guess the main problem is license. Their game is released under GPL. @akien-mga @Bertram25 You know better than I do what would be the implications of using their code. Would it be possible ?
If you are ok, I will try to catch them on IRC and ask them if they would mind sharing some models (always better to ask, even if it is an open source project ^^ )

**Comment by akien-mga** [comment]
Actual I have an untold evil plan to get you all involved in resurrecting the development team of Summoning Wars once OpenDungeons is well on its tracks and has a huge community :D
*evil grin*

More seriously, the project is currently on hold as there is only one active dev + some translators, and the dev (@fusion44) decided to take an understandable break from working alone on Sumwars :)

Sumwars is under the GPLv3+ as we are, so we could easily reuse even parts of its code (which is also why I brought up the name in our discussion about the main menu, since we have available code using OGRE and CEGUI).

As for the art, it's under CC BY-SA 3.0, so we could also reuse some of it (and Sumwars could indeed also use some of our models if development starts again).
There are also source files available for the models, but those are Maya files, I don't know to which extent we could use them (e.g. whether they can be imported in Blender and converted to .blend files without losing info).

**Comment by hwoarangmy** [comment]
Note that from what I've seen in their website, they use CEGUI < 0.8.0 so it might not be that straightforward to move from their code to ours (I guess thay would have upgraded if it was only a matter of changing the libraries).

Unfortunately, I couldn't test because the game segfaults at startup when I've created the character (tested on windows but also on Linux Ubuntu - with a CEGUI 0.8.4 but I didn't want to break my OD env).

> More seriously, the project is currently on hold as there is only one active dev + some translators, and the dev (@fusion44) decided to take an understandable break from working alone on Sumwars :)

That's bad since the game seems pretty nice from the screenshots I've seen but as you say, understandable.

> As for the art, it's under CC BY-SA 3.0, so we could also reuse some of it

Cool.

**Comment by akien-mga** [comment]
> Note that from what I've seen in their website, they use CEGUI < 0.8.0 so it might not be that straightforward to move from their code to ours (I guess thay would have upgraded if it was only a matter of changing the libraries).

The website might be partly outdated. The latest release (0.5.8) did add support for CEGUI 0.8.x and OGRE 1.9.0 IIRC.

**Comment by akien-mga** [comment]
Yes I can confirm it builds against CEGUI-0 (i.e. 0.8.x), see the list of dependencies (BuildRequires) that I use to package sumwars for Mageia: http://svnweb.mageia.org/packages/cauldron/sumwars/current/SPECS/sumwars.spec?view=markup

Last time I tried it it was not segfaulting, but that was already a year ago or so.

**Comment by hwoarangmy** [comment]
> The website might be partly outdated. The latest release (0.5.6) did add support for CEGUI 0.8.x and OGRE 1.9.0 IIRC.

You right, I've just checked and they support CEGUI 0.8.

**Comment by hwoarangmy** [comment]
Yes, I could build it but when I create my character (puch the create button), I get a CEGUI exception. So, I thought it might be linked to CEGUI version.

**Comment by Danimal696** [comment]
Its worth having a look at their model repository

**Comment by Danimal696** [comment]
They have a very poor quality, i think it will be the other way around and they will get to use ours.

**Comment by Bertram25** [comment]
> Actual I have an untold evil plan to get you all involved in resurrecting the development team of Summoning Wars once OpenDungeons is well on its tracks and has a huge community :D
> _evil grin_

Lol ;) Who knows? As for me, I'll go wherever the current OD team will. It's fun to work with you guys. :)

> They have a very poor quality, i think it will be the other way around and they will get to use ours.

Is the issue still valid, then?

**Comment by hwoarangmy** [comment]
> Is the issue still valid, then?

I've made some more tries. The exception came from not entering a character name (I had not seen the edit). After entering one, I could get the game work. As @Danimal696 said, the models character are pretty low poly and the source files are from maya (thus, not easy for us to give them the correct rotations).
However, even if the models are not as good as most of our current ones, we can consider taking some until we have better ones. I'm thinking, for example, at the skeleton. We are lacking artists and that may help to give some time to @Danimal696 (but it will not be a good excuse for this lazy artist to stop working on OD :$ )

**Comment by Danimal696** [comment]
eheh, got me :) , i actually had a look at megaglest looking for replacement. those are half usable

**Comment by fusion44** [comment]
Thanks for the interest in Summoning Wars :P 

I don't think anyone from the former team would have a problem seeing their meshes used in another open source game if it fits the game well. If you want I can try and reach them to get a written agreement. The game was born out of a university project where Maya was used. First (public) commit was in 2008 and the mesh details (and animations) somewhat show their age. And the game was already pretty much in a playable state by then.

Anyway I don't think anyone of the original members would reject the usage of the models for another open source game. Problem is indeed the Maya file format. The game was born out of a university project where Maya way used. Maybe you can use MeshMagik to scale the models up and adjust the orientation.

I've reopened the forum registration. We had to disable it due to a massive spam attack. I'll also try to join the IRC in #sumwars and #opendungeons more often if any questions arise. 

@akien-mga I'd love to get back to open source development but currently I simply don't have enough time to do so :-) Maybe when I'm finished with my Android project I'll be more receptive for evil plans of ressurection :+1: 

_edit_ I forgot, this has been discussed already some time ago on our forums: http://sumwars.org/forum/index.php?topic=433.msg2953#msg2953

**Comment by hwoarangmy** [comment]
Yes. As I've said, I could launch the game after all and indeed, the models are not detailed enough compared to the ones we use. But I've seen the skeleton and the lich do not look bad. I will try to import them to see what they look like ^^

**Comment by hwoarangmy** [comment]
I've had a try integrating the skeleton and that's not that bad ^^

**Comment by hwoarangmy** [comment]
I've uploaded the Lich + Skeleton from summoning wars in #992
