### ISSUE TITLE
Exception when the creature names in a level matches the game's naming engine

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#98]
I just experienced a segfault on TestSingleplayer.level. It happened just when I was modifying an area of marked dirt tiles, but looking at the error log it's seems to be completely unrelated. It seems the server tried to spawn a unit with an already-existing name:

> An internal Ogre3D error ocurred: OGRE EXCEPTION(4:ItemIdentityException): An object of type 'Entity' with name 'Creature_Wizard7' already exists. in SceneManager::createMovableObject at /home/iurt/rpmbuild/BUILD/ogre_src_v1-9-0/OgreMain/src/OgreSceneManager.cpp (line 6832)
> Internal Ogre3D exception: OGRE EXCEPTION(4:ItemIdentityException): An object of type 'Entity' with name 'Creature_Wizard7' already exists. in SceneManager::createMovableObject at /home/iurt/rpmbuild/BUILD/ogre_src_v1-9-0/OgreMain/src/OgreSceneManager.cpp (line 6832)
> **\* ERROR: Internal Ogre3D exception: OGRE EXCEPTION(4:ItemIdentityException): An object of type 'Entity' with name 'Creature_Wizard7' already exists. in SceneManager::createMovableObject at /home/iurt/rpmbuild/BUILD/ogre_src_v1-9-0/OgreMain/src/OgreSceneManager.cpp (line 6832)

**Comment by hwoarangmy** [comment]
Do you have the logs ?

**Comment by akien-mga** [comment]
I forgot to put the logs aside no, sorry. I then tried to reproduce the issue so the logs were overwritten.

**Comment by hwoarangmy** [comment]
Ok, no problem. Then, I will try to guess. I would say that there are 2 problems :
- The TestLevel
- You are unlucky

I've had a look at the TestLevel file. It seems one of the creature is a wizard called... Wizard7. My guess is that because you are not lucky, the 7th creature spawned was... a wizard ;)
So the fix would be to ensure creature names in level file do not follow the engine naming logic. Which is "creature type" + number. Maybe we could suffix all by _lvl or something like that

**Comment by Bertram25** [comment]
> So the fix would be to ensure creature names in level file do not follow the engine naming logic. Which is "creature type" + number. Maybe we could suffix all by _lvl or something like that

Nice catch! Makes sense now. :)
I'd propose this:
Add a "_lvl" suffix to the custom creatures at level loading time as you suggested, but remove it if it is found when saving, so that when we later add save support, we don't end with creature names like 'Wizard7_lvl_lvl_lvl...'
We'll also have to check for name unicity at save time and change the creature names that aren't unique after the suffix removal. I explain:

Load time:
- In the level file: 'Wizard7' -> Turned into 'Wizard7_lvl' at load time.
- obtained while playing: 'Wizard7'.

Save time:
- 'Wizard7_lvl' -> Turned back to 'Wizard7'
- Check for names unicity: Oops, two Wizard7:
  - Take the first one and recreate its name, e.g.: Wizard94.
- Save.

What do you think?

**Comment by akien-mga** [comment]
Can't we have the server browse through the list of already existing creatures and start the numbering accordingly? If the highest creature number is e.g. 27, then the next creature would be e.g. Wizard28. The same could be use at load time for a saved game, without trying to fill the hole maybe (if Kobold14 died but the last creature is Wizard28, then the increment starts at 29).

**Comment by hwoarangmy** [comment]
> Add a "_lvl" suffix to the custom creatures at level loading time as you suggested

That's not what I suggested. IMO, it is the map editor who should do that so we don't have to care about adding or removing the suffix at loading or save time. As I already said, I almost never had a look at the editor and I don't really know how it handles creature names, especially after loading. If it is handled, we could use the same logic.

> Can't we have the server browsing through the list of already existing creatures and starting the numbering accordingly

We could check if the creature name is ClassName + number and use the highest number. That would also work.

**Comment by Bertram25** [comment]
> That's not what I suggested. IMO, it is the map editor who should do that so we don't have to care about adding or removing the suffix at loading or save time. As I already said, I almost never had a look at the editor and I don't really know how it handles creature names, especially after loading. If it is handled, we could use the same logic.

The editor doesn't handle anything at all really. It's more some kind of clone of the game, without the turn updates and with a few custom commands and buttons. It does load a level the same way than the game (which is fine), and hasn't got any tools to setup creature names.

> Can't we have the server browsing through the list of already existing creatures and starting the numbering accordingly

Sounds like the best solution to me. :)

**Comment by hwoarangmy** [comment]
ok, let's do that

**Comment by Bertram25** [comment]
I was thinking about it, and in fact, when creating a new creature instance, could the server check for whether the new creature name is actually unique by checking the other creature's names? This would be permit to avoid such a situation very easily, right?

**Comment by hwoarangmy** [comment]
Yes. Anyway, I'm actually doing a patch for entities names. For some of them (rooms, traps for example), we assumed that the unique numbers to generate the names were synchronised between the server and the client (because the name and the gamemap were set late after the creation due to the architecture). I'm currently getting ride of that so that every entity uses the name used by the server (no need to use their own unique numbers except for map loading). When I will be done, it will be easier to check entities names before creating them and ensure it corresponds to the names on the server side.

Now that we are talking about it, I've seen that battlefields can be displayed. Is there an easy way to do that ? That's the only entity I couldn't check...

**Comment by Bertram25** [comment]
Sounds a good and sane refactoring. :)

As for the battlefield debug entities, here is what i found while rewriting it:
https://github.com/OpenDungeons/OpenDungeons/blob/development/source/Creature.cpp#L2336

I do think more code was once around, but I can't really tell.

**Comment by hwoarangmy** [comment]
ok. Then, it is not functional in the actual code. Was it usefull ? Have you seen how to works and what it is for ?

**Comment by Bertram25** [comment]
> Was it usefull ? Have you seen how to works and what it is for ?

It was used to graphically show the "danger" ratio of each tile of the first spawned creature or nothing it there were no danger. (all that was very hardcoded I suppose).

It was using some sort of bar more or less high depending on the value live.
I may have been useful, and maybe it will be someday if we want to change or improve, or if we break this somehow.
I'd simply say we might want a better solution when we come to this.

**Comment by hwoarangmy** [comment]
Well, I guess it can be interesting when we will mess with fighting behaviour, which will have to be soon. I will have a look if it is hard to re-enable it.

**Comment by Bertram25** [comment]
Np, as for me. Visual live debug info are the best to understand what's happening, IMHO. (I'm doing this on VT, for instance.)

**Comment by hwoarangmy** [comment]
yes, IMHO, the 2 best ways (compatible) :
- visual debug
- log activable debug (through console, being able to change logging level) so that when you see something weird, you can activate logs to see what's happening

**Comment by Danimal696** [comment]
Hi guys, i was thinking, could we do as in DK and have each creature have a different race specific name? Creatures would get a name generated at ramdom (or from a list) and an unique identifier; ex:
Warlock: Saruman , warlock14
Warlock: Ganondorf , warlock15
Lizarman: Hssisofer , lizard3

**Comment by Bertram25** [comment]
@Danimal696 Creature name as we mean here aren't meant to be seen by the player, they are more internal unique ids.
Creating fun random names is IMHO useless, as we'll change the status window to be displayed only for developers only, and replace info view with the skull flag system.

**Comment by akien-mga** [comment]
I like the idea of having random names for the creatures, but as @Bertram25 says it would not be relevant for the status window and the creature IDs.

That said, we can keep the idea at the back of our heads. It would be nice to have random names if we decide to add some RPG elements in a later stage of development (for example if you have a high-level warlock with some great equipement, you would like to be able to differentiate him from wannabe warlocks with a plastic wand :-).

**Comment by Bertram25** [comment]
True, special creatures will need to be visually different, and displaying their name somehow would help. :)
Ok, I won't throw away the idea from my head, sorry for my bluntness. ;)
