### ISSUE TITLE
Traps layed in editor mode are unbuilt in level

### ISSUE THREAD

**Issue by Danimal696** [OpenDungeons/OpenDungeons#988]
their default activation value is 0 instead of 1 in level file, so all of them dont appear in level

**Comment by akien-mga** [comment]
It would indeed be more logical that traps placed in the editor are automatically activated; I guess that's what most level designers would want (and traps can still be deactivated by editing the level file if need be).

**Comment by akien-mga** [comment]
It sounds to me like a job I should be able to handle, so I'll take it. @hwoarangmy If it implies messing with a file you are currently changing in your current PR or incoming one, feel free to snatch the issue from me ;)

**Comment by hwoarangmy** [comment]
No problem. If there is a merge conflict, I will fix it. In any case, my next PR will be huge and might mess with many stuff.

**Comment by Danimal696** [comment]
care to spoil it a bit? :D

**Comment by hwoarangmy** [comment]
You can have a look #992 
Basically, most interesting things are:
- Allow to customize creature behaviour with plugins in the creature config file (like skills). Now, the only default behaviour is to get rogue when furious for too long. Fighting enemies, fighting natural enemies, flee when weak and leave dungeon when furious need to be added if wanted (and the order matters).
- Imported skeleton + lich from summoning wars (skeleton spawn in prison and lich in crypt)
- Creature defense spell (+ corresponding creature skill)
- ranged creatures can now engage natural enemies (previously, they would never hit)
- ranged creatures can now KO enemies (previously, they would always kill)
- Many, many code cleaning

**Comment by akien-mga** [comment]
I tried this but I get a segfault, I guess I need to dig a bit more to understand how this trap creation stuff works out :)

```
diff --git a/source/traps/Trap.cpp b/source/traps/Trap.cpp
index f62a7fb..f42b4eb 100644
--- a/source/traps/Trap.cpp
+++ b/source/traps/Trap.cpp
@@ -803,6 +803,8 @@ bool Trap::buildTrapDefaultEditor(GameMap* gameMap, Trap* trap, ODPacket& packet
         tile->setFullness(0.0);
         tile->claimTile(seatTrap);
         tile->computeTileVisual();
+
+        trap->activate(tile);
     }

```

**Comment by akien-mga** [comment]
Looks like this works better:

```
diff --git a/source/traps/Trap.cpp b/source/traps/Trap.cpp
index f62a7fb..4db524a 100644
--- a/source/traps/Trap.cpp
+++ b/source/traps/Trap.cpp
@@ -291,6 +291,9 @@ void Trap::setupTrap(const std::string& name, Seat* seat, const std::vector<Tile
         // Allied seats with the creator do see the trap from the start
         trapTileData->seatsSawTriggering(alliedSeats);
         tile->setCoveringBuilding(this);
+
+        if(getGameMap()->isInEditorMode())
+            trapTileData->setActivated(true);
     }
 }

```

**Comment by hwoarangmy** [comment]
I would have based on what is done in when reading an activated trap from a file in:
Trap::importTileDataFromStream

You will see that after trapTileData creation, we call "activate".

So, basically, I would have chosen the same location as you did (in setupTrap). But I would have called "activate" because it initializes some more stuff (number of shoots before deactivation and such). It is safer IMHO to to it rather than calling trapTileData->setActivated (this can put the trap in an unexpected state because the other values would not be at the expected value).

Note that I'm talking in a general way because in the editor, it probably doesn't matter. However, if we later want to customize in the editor the trap more (allowing to change number of shots before deactivation or the cooldown), there will be a problem.

To conclude, I would have done a mix of both your changes. You are beginning to know the code pretty well ^^

**Comment by akien-mga** [comment]
Thanks for the detailed comment, calling activate(tile) is indeed a better idea. I had noticed that it did more stuff, but somehow when finding the good place to call it I was fooled by the presence of trapTileData :D

**Comment by akien-mga** [comment]
@hwoarangmy I've fixed the commit.
