### ISSUE TITLE
Depleted gem block

### ISSUE THREAD

**Issue by Danimal696** [OpenDungeons/OpenDungeons#991]
Its not possible create a 0% density gem block in editor mode

**Comment by akien-mga** [comment]
It would require a GemGround tile (maybe similar to GoldGround, but with gem colours).

**Comment by akien-mga** [comment]
Nevermind my above comment, we have the visual: https://github.com/OpenDungeons/OpenDungeons/blob/development/materials/textures/GemsGround.png

I can have a look at implementing support for gems with fullness 0% if we all agree that we want those. Personally I guess they can be useful if we want to trick players into going to a location where it's actually an empty gem tile. To be honest I haven't tested the game extensively since the gem tile was added so I'm not sure if gem tiles are shown in the fog of war?

**Comment by hwoarangmy** [comment]
> I'm not sure if gem tiles are shown in the fog of war?

They should. If not, that's a bug ^^

> Its not possible create a 0% density gem block in editor mode

No, it wasn't planned at first. But that's not a bad idea.

**Comment by Danimal696** [comment]
i confirm they are visible into the fog
